### PR TITLE
Fixed javadoc typo.

### PR DESCRIPTION
**Pull request by gmcferrin**

### CODE REVIEW

**Comment by EvilSeph** [comment]
Javadoc typo fixes are done in batches instead of filling the repo with individual commits.

**Comment by gmcferrin** [comment]
Makes sense - I'll keep that in mind for the future.

**Comment by feildmaster** [comment]
Pulled here: https://github.com/Bukkit/Bukkit-Bleeding/commit/8b18d1fdabfb40b3fb4812cc573795e42a7f5307

**Comment by gmcferrin** [comment]
Closing. Thanks Feildmaster.

**Pull request closed without merging**
