### PR TITLE
Added the API corresponding to pull request # 714

### PR DESCRIPTION
**Pull request by nitnelave**
https://github.com/Bukkit/CraftBukkit/pull/714

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
So remove it. ;)

**Comment by nitnelave** [comment]
I actually don't know how to edit the file once commited (or how to commit another, as it is). I use the fork and edit feature of github, and it did everything for me, and now I can't seem to be able to set up a repository to make another commit...

**Comment by CelticMinstrel** [comment]
Go to your fork and find the file you want to edit, and then you can just edit it in much the same way as you did before (but without the fork part).

Your forks can be found at https://github.com/nitnelave/ if you weren't aware.

**Comment by nitnelave** [comment]
Ok, I get it, I had the right repository, but the wrong branch. Ok, I did the change. I also updated the other commit with the API and the useless method.

**Comment by nitnelave** [comment]
I improved it, I'll put it in a new PR

**Pull request closed without merging**
