### PR TITLE
change comment prefix("# ">>"#")

### PR DESCRIPTION
**Pull request by ghost**
better to show why it would be better
http://i39.tinypic.com/2mgky0n.png

### CODE REVIEW

**Comment by ghost** [comment]
xD, the example is messed up
wait a sec(***\* headers)

**Comment by grum** [comment]
Why?

**Comment by ghost** [comment]
you clicked the tinypic link right?
it would look better, some comments dont need extra spaces
for example a comment in a block of pound sign(#)
http://i40.tinypic.com/wleweq.png
we devs can always add a space if we needed it

**Comment by javajawa** [comment]
Sorry, but habit forces me to:
 # - Hash or Number Sign (http://en.wikipedia.org/wiki/Hash_symbol)
 £ - Pound Sign.

On a standard qwerty US keyboard layout on pared to a UK one, # replaces £.

Otherwise, nice :)

/me goes back to lurking

**Comment by grum** [comment]
It's not for ascii art O.o

also if you want to do sections do:

```
# =======================================
#                 FOO
# =======================================
```

**Pull request closed without merging**
