### PR TITLE
BUKKIT-2849 Added/Removed Sounds for MC1.4.2

### PR DESCRIPTION
**Pull request by attrib**
Added the new Sounds from 1.4.2
Removed Sounds that are not there anymore.
Needed for https://github.com/Bukkit/CraftBukkit/pull/920

Relates to https://bukkit.atlassian.net/browse/BUKKIT-2849

### CODE REVIEW

**Comment by GuntherDW** [comment]
Why did you change the line endings from UNIX to Windows? This makes it kinda hard to see what exactly changed.
Not only that but the "accepted" line ending in the Bukkit project is the UNIX line ending format (just \n's)

**Comment by attrib** [comment]
I fucked up. Sorry.
Fixed this.

**Comment by LB--** [comment]
Don't forget to squash the commits ;)

**Comment by attrib** [comment]
Squashed it. :)
Thanks for the hint, that this is possible in git.

**Comment by amaranth** [comment]
Pulled, thanks.

**Pull request closed without merging**
