### PR TITLE
Unload chunk request

### PR DESCRIPTION
**Pull request by Raphfrk**
This pull adds an unloadChunkRequest() method that allows chunks to be unloaded.

More info can be found at the CraftBukkit pull request.

https://github.com/Bukkit/CraftBukkit/pull/102

### CODE REVIEW

**Comment by FrozenCow** [comment]
Interested to see what you did with CraftBukkit. I just added unloadChunk, which will just unload and remove the chunk from the queues: https://github.com/Bukkit/Bukkit/pull/85

**Comment by Raphfrk** [comment]
Didn't see that one, sorry, wasn't trying to re-do work.

I send the unload operation though the 

c(x,z)

method.

This adds the chunk to the this.a set.  This appears to be the "marked for deletion" set.

The c(x,z) method also ignores unload requests for any chunks that are near the spawn point.  

This is presumably an optimisation by Notch based on the theory that having it pre-loaded would handle dying players better.

**Comment by Raphfrk** [comment]
I was actually considering implementing a garbage collector, but then didn't bother :).

It would scan the chunks every so often and mark any chunks that are far away from any player for deletion.

I may have gone over board on this one.  I wasn't sure of the effects of unloading chunks near players, so figured I might as well block it.

**Comment by FrozenCow** [comment]
Ah yes. It might be a good idea to have both though. I really need to unload the chunk at the time I call the function. Dynmap blocks the main thread when rendering and therefore Minecraft won't unload any chunks, which results in OutOfMemory pretty fast.
But for most uses I can imagine having a 'lazy unload' is better, since CraftBukkit/Minecraft does all the checking for you.

**Comment by Raphfrk** [comment]
I was trying to do the same thing with "circleload" in Server Port.  However, Server Port uses the scheduler, so is able to split the command over many clock cycles.

Maybe we could combine the 2 pulls and have:
 unloadChunk() -> unloads through the standard unload queue

 unloadChunkForce() -> unloads immediately

 unloadChunkRequest() -> checks if near a player before unloading

Sending it through the c() function does mean that it is queued and only 100 are every unloaded per clock tick.

**Comment by FrozenCow** [comment]
Yes, combining that would be a good option. Dunno if its more efficient to create a new pull or to let the Bukkit team use the current pulls to combine them.

**Comment by Raphfrk** [comment]
Reducing load on the team would probably be more likely to get it pulled.

I think my pull is closer to the final combined state.

**Comment by FrozenCow** [comment]
If so, could you also combine it with my master branch? https://github.com/FrozenCow/CraftBukkit/commits/
The save option for unloadChunk is a nice addition I think (to make force-unloading being non-destructive).

**Comment by Raphfrk** [comment]
In theory, you should have separate branches for each feature.

Hmm, maybe you have most of it done already.  Is the save option to allow unloading without saving?

**Comment by Raphfrk** [comment]
This is what I was going to add to CraftWorld.  This gives 2 booleans (use queue and force unload without doing to distance to players check).

```
public void unloadChunk(int x, int z, boolean useQueue, boolean force) {
    if(!force && testChunkNearPlayer(x,z)) {
        return false;
    }
    if(useQueue) {
        unloadChunkQueue(x, z);
    } else {
        unloadChunkImmediate(x, z);
    }
    return true;
}

private void unloadChunkQueue(int x, int z) {

}

public boolean testChunkNearPlayer(int x, int z) {
    CraftServer server = world.getServer();
    Player[] players = server.getOnlinePlayers();
    for(Player player: players) {
        Location loc = player.getLocation();
        if(loc.getWorld() != world.getWorld()) {
            continue;
        }
        // If the chunk is within 256 blocks of a player, refuse to accept the unload request
        // This is larger than the distance of loaded chunks that actually surround a player
        // The player is the centre of a 21x21 chunk grid, so the edge is 10 chunks (160 blocks) away from the player
        if(Math.abs(loc.getBlockX()-(x<<4)) <= 256 && Math.abs(loc.getBlockZ()-(z<<4)) <= 256) {
            return true;
        }
    }
    return false;
```

**Comment by Raphfrk** [comment]
The Bukkit API was:
    /**
     \* Requests that the server unloads the chunk at the specified coordinates
     *
     \* @param x X-coordinate of the chunk
     \* @param z Z-coordinate of the chunk
     \* @return returns true if the unload request was accepted
     */
    public boolean unloadChunk(int x, int z);

```
/**
 * Requests that the server unloads the chunk at the specified coordinates
 *
 * @param x X-coordinate of the chunk
 * @param z Z-coordinate of the chunk
 * @param force Chunk unload is unloaded unconditionally
 * @return returns true if the unload request was accepted
 */
public boolean unloadChunk(int x, int z, boolean force);

/**
 * Requests that the server unloads the chunk at the specified coordinates
 *
 * @param x X-coordinate of the chunk
 * @param z Z-coordinate of the chunk
 * @param useQueue Chunk unload is unloaded using the queue
 * @param force Chunk unload is unloaded unconditionally
 * @return returns true if the unload request was accepted
 */
public boolean unloadChunk(int x, int z, boolean useQueue, boolean force);
```

**Comment by FrozenCow** [comment]
Yes, that sounds good. Also a boolean results sounds like a good addition.
Although not yet sure how to incorporate the save option.
Another thing to be wary about: I noticed when doing some tests with force-unloading chunks, there could be errors for entities that were on that chunk, crashing Minecraft and corrupting that chunk. I'm not 100% sure though, it could have been my crappy test-setup. Although I still think it might be a good idea if testChunkNearPlayer would also check if there are entities on the chunk that could pose a problem.

**Comment by Raphfrk** [comment]
This pull is superseded 
https://github.com/Bukkit/CraftBukkit/pull/104

**Pull request closed without merging**
