### PR TITLE
Added checking if a Material is edible

### PR DESCRIPTION
**Pull request by macalinao**
This makes it a lot easier to check if a player just used food, for example.

### CODE REVIEW

**Comment by aPunch** [comment]
I wish Bukkit would move away from the enum system and more towards something closer to Spout, with ItemFood, ItemSolid, BlockLiquid, etc. so things like this would be less bulky.

**Comment by Afforess** [comment]
In Spout this is one line.

> return type instanceof Food.

**Comment by rpendleton** [comment]
I also wish Bukkit would move away from the enum and do something similar to Spout. They got it right.

**Comment by EdGruberman** [comment]
Would there be any performance concerns of using a class versus an enum?

**Comment by Majiir** [comment]
I disagree that this change adds anything fundamentally useful to Bukkit as an API. It doesn't ask Minecraft directly whether an item is edible, and it doesn't have a well-defined meaning of "edible". (`CAKE` is in the list, but is that material actually edible, or is `CAKE_BLOCK` the better choice? Both? Neither?) Since no other utilities are supplied (like `eat()` or `getHealAmount()`), and such utilities are apparently provided by other frameworks (Spout), I'm not convinced this is a good change.

**Comment by macalinao** [comment]
You can't eat a CAKE_BLOCK...

**Comment by rpendleton** [comment]
You can eat it if you place it, then right click, but I wouldn't consider it food.

**Comment by macalinao** [comment]
That's not eating, that's using the block.

**Comment by Majiir** [comment]
Then how is placing a block considered eating it?

**Comment by macalinao** [comment]
Oh yeah, i forgot you can't eat cake directly... i'll fix that...

**Comment by Dinnerbone** [comment]
> I also wish Bukkit would move away from the enum and do something similar to Spout. They got it right.

@ryankentp We have said many times that we are planning to remove the Material enum for something much more powerful, since near the start of the project. This change will break pretty much every plugin.

Pulled. Thanks.

**Comment by macalinao** [comment]
Awesome!

**Pull request closed without merging**
