### PR TITLE
Add API to set whether or not a player affects nearby mob spawning

### PR DESCRIPTION
**Pull request by jedediah**
Players that don't affect spawning will not activate mob spawners and will be ignored by the natural spawning and despawning algorithms.

Implementation:
https://github.com/Bukkit/CraftBukkit/pull/775

### CODE REVIEW

**Comment by riking** [comment]
Is this satisfied by the Vanish API?

**Comment by turt2live** [comment]
Being invisible != Stopping mobs from spawning

**Comment by riking** [comment]
@turt2live I distinctly remember there being a part of the Vanish API that allowed plugins to specify whether or not a player should affect spawning

**Comment by turt2live** [comment]
It appears that this PR is unrelated to the vanish API. Not everyone wants to make someone invisible to make them ineffective at spawning nearby mobs

**Comment by asofold** [comment]
It is a feature very much requested for admin activity in the context of being vanished. It is similarly unrelated to vanishing as the is the question if players should or should not appear in the other players tab list.

**Comment by riking** [comment]
@jedediah If you want this PR to be completed, please update it to the latest CraftBukkit.

**Pull request closed without merging**
