### PR TITLE
[B] Added Missing Villager Profession. Fixes BUKKIT-5765

### PR DESCRIPTION
**Pull request by xt449**
Issue:
Missing GENERIC Villager profession

Ticket:
BUKKIT-5765 - https://bukkit.atlassian.net/browse/BUKKIT-5765

### CODE REVIEW

**Comment by turt2live** [comment]
You need to follow the [Contributing Guidelines](https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md) to have this reviewed.

**Comment by xt449** [comment]
I would have thought that something this ridiculously simple change would not need 3 paragraphs to explain 1 line edit and 1 new line. Someone else can add this if they really want then.

**Comment by EdGruberman** [comment]
Try not to underestimate what even a single line change can do to break things. No matter the simplicity of the edit or concept, it needs to be clearly articulated and tested properly in order to be reviewed by the development team.

**Comment by xt449** [comment]
I know exactly what this change does. The only thing it does it let bukkit and plugins have support for a villager profession. I'm not sure if you understand, but this is only adding a villager profession. This will not break anything unless there is some code that I have overlooked.

**Comment by EdGruberman** [comment]
The contributing guidelines are designed to avoid all this discussion in the comments and standardize this information. Testing helps to minimize the possibility that you have overlooked something.

These are a few examples as to why the process is adhered to so rigidly. It simplifies all our efforts collectively. This is a team process, we all need to work together.

**Comment by turt2live** [comment]
:(

**Comment by nightpool** [comment]
The only important thing that really needs to be addressed here is not
_what_ this change does—that's obvious from the code. What needs to be
addressed here is an overview of how this interacts with the rest of the
code, both Craftbukkit and NMS, as well as a justification for the change.
Can you point to the place in NMS code where a 'generic' villager is
defined? Are there case statements that need to be updated? All of these
things need to be addressed. (As well as any other concerns the team has. I
don't speak for the Bukkit developers)

**Comment by turt2live** [comment]
Not to mention that the game can actually crash due to this villager type (in some scenarios).

**Comment by amaranth** [comment]
Didn't this get removed in 1.8?

**Comment by xt449** [comment]
@turt2live Crashes may occur from this villager due to version changes breaking trades.

**Comment by xt449** [comment]
@amaranth No it has not been removed.

**Comment by turt2live** [comment]
@xt449 @amaranth  is correct. I was removed in 1.8 from the server-side. The client contains the texture but future versions do not have a way of activating that texture (at least from the server).

**Pull request closed without merging**
