### PR TITLE
Added CreatureSpawnEvent

### PR DESCRIPTION
**Pull request by anpage**
Added the accompanying event for the CREATURE_SPAWN hook in my CraftBukkit pull request.

### CODE REVIEW

**Comment by EvilSeph** [comment]
Ticket reopened because GitHub ate our pull requests.

**Comment by EvilSeph** [comment]
As I understand it, we really didn't want to touch World...but I believe Tahg exposed it already. This is, definitely, an event we want, it just hasn't been a priority. Would you mind updating it and cleaning it up and I'll discuss it with the team? Thanks.

**Comment by anpage** [comment]
Sure thing. I'll do that tomorrow.

EDIT: Oops, I totally forgot. Darn weekends.

**Comment by anpage** [comment]
Okay, that merge brought everything up to date.

**Comment by EvilSeph** [comment]
I've pulled this. But for the future, please do not include merges in pull requests and include minimal diffs and commits please.

**Pull request closed without merging**
