### PR TITLE
Added a Metadata framework for Entities, Blocks, and Worlds

### PR DESCRIPTION
**Pull request by rmichela**
This metadata implementation has the following features:
1. All metadata is lazy. Metadata values are not actually computed
   until another plugin requests them. Memory and CPU are conserved by not
   computing and storing unnecessary metadata values.
2. All metadata is cached. Once a metadata value is computed its value
   is cached in the metadata store to prevent further unnecessary
   computation. An invalidation mechanism is provided to flush the cache
   and force recompilation of metadata values.
3. All metadata is stored in basic data types. Convenience methods in
   the MetadataValue class allow for the conversion of metadata data types
   when possible. Restricting metadata to basic data types prevents the
   accidental linking of large object graphs into metadata. Metadata is
   persistent across the lifetime of the application and adding large
   object graphs would damage garbage collector performance.
4. Metadata access is thread safe. Care has been taken to protect the
   internal data structures and access them in a thread safe manner.
5. Metadata is exposed for all objects that descend from Entity,
   Block, and World. All Entity and World metadata is stored at the Server 
   level and all Block metadata is stored at the World level.
6. Metadata is NOT keyed on references to original objects - instead
   metadata is keyed off of unique fields within those objects. Doing this
   allows metadata to exist for blocks that are in chunks not currently in
   memory. Additionally, Player objects are keyed off of player name so
   that Player metadata remains consistent between logins.
7. Metadata convenience methods have been added to all Entities,
   Blocks, BlockStates, and World allowing direct access to an individual
   instance's metadata.
8. Players and OfflinePlayers share a single metadata store, allowing player metadata to be manipulated regardless of the player's current online status.

### CODE REVIEW

**Comment by cyberdudedk** [comment]
Definitely takes metadata to a whole new level.
So far I'm loving it!

Very thought through and a very detailed implementation.
+1000

**Comment by ZachBora** [comment]
So each Metadata is a List of a basic object, that's what I need. +1

**Comment by RichardRobertson** [comment]
Oh this does look better. Glad @cyberdudedk mentioned this.

**Comment by Afforess** [comment]
+1 Awesome.

**Comment by dredhorse** [comment]
GO!

thanks @cyberdudedk for pointing here...

So I guess I should put our project on hold to implement something like this via a plugin.. would have been a nice project... but a bukkit integration was always better..

**Comment by ZachBora** [comment]
@Afforess Why don't we take spout, and put it in Bukkit itself?

**Comment by Afforess** [comment]
> @Afforess Why don't we take spout, and put it in Bukkit itself?

Because that would be a good idea.

**Comment by cyberdudedk** [comment]
@ZachBora
Because the Bukkit Team doesn't want to, end of discussion ;)
The start of Spout (BukkitContrib) happened because Afforess found it difficult to get anything "new" approved by the Bukkit Team (Whoever that is in this context?)

Is this correctly understood @Afforess?

**Comment by iffa** [comment]
Pretty much

**Comment by nthlpy** [comment]
I actually have had something come up today for which this would greatly simplify.

**Comment by t3hk0d3** [comment]
/sign

Pull it @EvilSeph, or no more cookies for you

**Comment by CruzBishop** [comment]
How has this not been pulled yet? It's epic!

**Comment by rakiru** [comment]
Acrobot said it best:
Pull. This. Now.

**Comment by Zidane** [comment]
Why is it that every really good pull request that would benefit Bukkit so much simply gets ignored?

What happened to the "openess" that used to exist in the Bukkit Project? I am not trying to flame them but comeon now...don't hold us back because you guys just haven't got around to it...let us help if the team is overwhelmed.

**Comment by Rigby90** [comment]
It's not getting ignored, the status of the Bukkit team is kind of all over the place atm.

Grum being away... Tahg had internet/power issues in a storm and such. EvilSeph is dealing with the community and Dinnerbone doesn't have much time AFAIK.

We've got a spreadsheet full of all the pull requests and possible outcomes for them as well as testing and such, however ultimately it relies on one of those 4 to pull it into main.

**Comment by rmichela** [comment]
Could that spreadsheet be made public (read-only of course)? The transparency would go a long way.

**Comment by Zidane** [comment]
I agree

**Comment by rakiru** [comment]
Voting up the making spreadsheet public idea. For an open-source project, there is a lot of secrecy and resistance to community help. I mean, you support the community using what you have as you want, but if we suggest new things or try to help, they are ignored, or at least appear to us as being so. A little more openness would go a long way.

**Comment by cyberdudedk** [comment]
@rmichela Would you be against building this for Spout and submitting it there? It would be pulled almost instantly there if you did. I know it's not Bukkit (yet?) but i'd be a good start. I'm just very sad seeing the current state of Bukkit.
It's been 3 weeks, and we don't even know if Dinnerbone approves the idea (Not necessarily the code, but at least the idea). The last I heard from him when I asked, was "We'll see".

**Comment by rmichela** [comment]
I'd like to give the bukkit team the benefit of the doubt before downgrading the code into a plugin. Much of the utility of my implementation comes from its deep integration with the craftbukkit object model.

@feildmaster's comments above indicate that someone with commit access to craftbukkit has at least read the code. We will see where it goes from here. @Dinnerbone has not made any public statement for or against metadata. If the patch is rejected I will pursue alternative means of distribution.

**Comment by Dinnerbone** [comment]
Another metadata implementation!

Two gripes before I can do a full review:
- Javadoc. Javadoc everything and javadoc it full.
- Code style. Inconsistent spacing etc.

I'll come back for a complete review when I have time, but I'm afraid it probably won't be until shortly after Minecon.

**Comment by chrisyco** [comment]
Is there any use case for lazy metadata? The functional programmer in me is dying of euphoria, but I don't see how this can be used in a Bukkit plugin.

**Comment by rmichela** [comment]
@chrisyco, absolutely! SuperDuperUberPerms registers a metadata attribute called "chatPrefix" that's computed from the result of a database call (because the permissions and group membership are stored in MySQL). However, the server has no plugin installed that uses the "chatPrefix" metadata attribute. By having lazy metadata, the database is never accessed because the metadata is never asked for, thus eliminating unnecessary CPU and IO load.

**Comment by chrisyco** [comment]
Ah, I get it now. So it's less of a static datastore and more like a table full of thunks. I've never seen anything like this in Java before&mdash;sounds very interesting.

**Comment by RichardRobertson** [comment]
Wouldn't storing the string value in the chatPrefix metadata be less RAM than the object/key reference needed to store the lazy metadata container?

**Comment by rmichela** [comment]
ChatPrefix was a simple illustration.

Minecraft servers are primarily I/O bound and then CPU bound. While a simple key value pair based metadata system would save a few bytes per entry, the potential for I/O and CPU savings by using lazy metadata far outweighs those few bytes. Metadata functions like Permissions in that the framework is only an exchange. Individual plugins are responsible for providing values and anything that can reduce the I/O and CPU burden from plugins is valuable. Additionally, lazy metadata allows the retrieved value to be cached within the Metadata framework, freeing the plugin developer from the burden of implementing (or even knowing about) caching.

**Comment by main--** [comment]
This is excellent and I really like it, but in my opinion the LazyMetadataValue needs some improvements: I don't understand why it takes a `Callable<Object>` to generate the values when you just use a String afterwards (with toString()). Why don't you use a `Callable<String>` (which I wouldn't recommend) or store the returned Object? (and make a getter for it, maybe even with some generic type arguments?)

**Comment by rmichela** [comment]
LazyMetadataValue is implemented as it is due the weakness of java generics. If LazyMetadataValue were implemented as a generic class, there would be no way to restrict which type of object is passed as metadata. This opening would allow complex object graphs and plugin specific objects to be added as metadata. Since metadata is designed to persist as long as the server is running, allowing complex object graphs to be added to metadata could completely destroy memory and lead to terrible memory leaks. Allowing plugin specific objects to be added to metadata would force the very dependencies between plugins that Metadata was designed to mitigate.

I chose strings as the internal representation of Metadata because it's the least common denominator between all the primitive java data types. Callable<Object> was chosen over Callable<String> for developer convenience.

**Comment by main--** [comment]
Got it, thanks!

**Comment by RichardRobertson** [comment]
There is too a way to restrict what is added. It just wouldn't happen at compile time. Runtime type checking is always available.

Too bad Java generics aren't actually runtime accurate.

**Comment by rmichela** [comment]
@RichardRobertson - If only Java had a real generic type system rather than compile time hackery with its type erasure.
@chrisyco - Apparently the coding standards of my day job bled in. :)

**Comment by RichardRobertson** [comment]
@rmichela I prefer capitalizing things too. Oracle naming standards are stupid.

**Comment by rmichela** [comment]
@Dinnerbone, would it be possible to get an update on this pull request? I believe metadata would be a valuable addition to the bukkit API. Can I expect it to be pulled in the future or do I need to start looking for an alternate means of distribution?

**Comment by main--** [comment]
Why was this closed?

**Comment by tips48** [comment]
I believe its not in Bukkit-Bleeding and CraftBukkit-Bleeding

**Comment by rmichela** [comment]
This PR has been obsoleted.

https://github.com/Bukkit/Bukkit-Bleeding/tree/Metadata

**Pull request closed without merging**
