### PR TITLE
TimeChangeEvent for time changes through the server (sleeping) and /time

### PR DESCRIPTION
**Pull request by Silverstar**
I would like to have a TimeChangeEvent which should be called if the server changes the time because all players (except isSleepingIgnored players) are in beds.
This is the preparation for it in Bukkit, the patch for CraftBukkit will follow.
Could also be used for /time

### CODE REVIEW

**Comment by halvors** [comment]
+1

**Comment by Silverstar** [comment]
Related CraftBukkit pull request: https://github.com/Bukkit/CraftBukkit/pull/372

**Comment by Afforess** [comment]
Would be handier if it was cancelable and had the amount of time changed in the event.

Additionally, it could be called when world.setTime is used...

**Comment by erisdev** [comment]
I think that, as it is, it's already potentially pretty handy. Somebody cleverer than I could probably use this to make crops grow even while the players sleep. C:

**Comment by Afforess** [comment]
Actually, I disagree. What if this get's fired, but there were only 500 ticks left in the night. Or 1 tick left? It would qualify as the same as a full change. The time changed and the ability to cancel an event are important.

**Comment by Silverstar** [comment]
Well, as you might noticed, I'm not that experienced in java as many other of you. So, I did what I was able to without breaking everything up. Feel free to make it cancelable, add the call on setTime, add the amout of time changend...
I'm not that advanced yet, sorry.

**Comment by Afforess** [comment]
What's advanced about it? Move the code up 4 lines, check !isCancelled(), and if it is cancelled, don't allow the code that changes the code.

As for the time change, it's the same idea, look at the new time it is going to be set to, subtract the current time = time changed.

It's 10 lines of code for both, tops.

Edit:

Give it your best shot - I'll help if it's not 100% right. You will never get better by admitting defeat.

**Comment by Silverstar** [comment]
I'll have a look into it. I'm just not that familiar with that. yet.

**Comment by erisdev** [comment]
@Afforess whoops, missed the bit where delta t isn't available. You're right: at the very least, that bit is a necessity.

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
