### PR TITLE
Location implements Serializable

### PR DESCRIPTION
**Pull request by pyraetos**
This is my first pull request, I got the idea to try this from this forum thread: http://forums.bukkit.org/threads/make-org-bukkit-location-serializable.56521/

Location's field World is now transient, to avoid a non-serializable object from being written. Instead, the private methods writeObject() and readObject() are implemented to save the world as a String. These are invoked, if found, by the JVM when ObjectOutputStream.writeObject() or ObjectInputStream.readObject() is called. They save the world as a String.

Here is the demonstration plugin, which can save and load Locations if the Bukkit it's running on has my Location class:
http://www.pyraetos.net/SerializeLocation.jar

Commands:
    /save: Creates a file called "location" in the CD and writes the player's location.
    /load: Loads the file and messages the player with the new Location's toString()

### CODE REVIEW

**Comment by feildmaster** [comment]
This will not be pulled, if you really want to store a location then store it with your own methods.

**Comment by Afforess** [comment]
> This will not be pulled, if you really want to store a location then store it with your own methods.

Lame answer. I guess making Bukkit easy to use is not a priority.

**Comment by feildmaster** [comment]
There's no way to Deserialize it (automatically, and cleanly) with the name with no errors. I stand with my logic.

**Comment by Afforess** [comment]
throw an IOException then. That's what exceptions are for - exceptional circumstances.

**Comment by Fishrock123** [comment]
Exactly... If the world doesn't exist, it should throw an error...

**Comment by Afforess** [comment]
Right, you avoiding the serialization of locations doesn't make the problem disappear. Now plugin programmers need to write their own code to save a location, and they still face the problem of a missing world - closing the pull doesn't fix this.

**Comment by aufdemrand** [comment]
+1, please pull.

**Comment by Fishrock123** [comment]
Well, we _could_ just make new worlds whenever a plugin reads one that doesn't exist. XD

But, this pull does need a slight overhaul. No spaces between stuff. :(

**Comment by obnoxint** [comment]
Before the trolls continue their flame-bait, writing a wrapper for instances of Location is a breeze.

If you are still feeling lazy, you are free to use this: https://github.com/obnoxint/omc-lib/blob/master/src/main/java/net/obnoxint/mcdev/util/SerializableLocation.java

**Comment by Afforess** [comment]
Calling people trolls only makes you one.

Your wrapper is quadruple the lines of code and creates new objects, which makes it considerably slower, especially if you have a lot of locations.

**Comment by obnoxint** [comment]
No, it makes me identifying them. And I don't understand why you are feeling spoken to.

Besides that, before making wrong statements at least try to think about possible use cases and applications. I offered an alternative. You should know very well what to do if existing things don't suit your taste: do your own. But how so often you contributed nothing.

**Comment by tips48** [comment]
I'd have to agree with Afforess on this one, there's no reason why not to throw an IOException when the world is not found, at the expense of having to use a wrapper instead of a built-in method

**Comment by Fishrock123** [comment]
@obnoxint Huh?

While yours is an alternative, it is not really a _good_ alternative.

A native method is the best, and we do not see any good reason for not having a native method for this, as it is used in many, many plugins.

**Comment by aufdemrand** [comment]
Yes, there are alternatives... we're all using them... but no reason why this (or some for thereof) shouldn't be included in bukkit API.

**Comment by EdGruberman** [comment]
This looks to be a brilliantly simple pull request that addresses a common desire...  Why the resistance over the exceptional case of a world name not matching?

**Comment by Wolvereness** [comment]
> Lame answer. I guess making Bukkit easy to use is not a priority.

That's trolling.

> ... Why the resistance over the exceptional case of a world name not matching?

It's not exceptional though. It's fairly unpredictable for a plugin author. Special casing it themselves will allow them to control the failure behavior (whereas, if they are serializing it, they couldn't afford the entire thing to fall over because of one corrupt Location). Really, doing this in a plugin is as simple as sub-classing Location, implementing serializable, and providing constructors. As far as serialization implementation goes, it's not supposed to fall over this easily.

> Your wrapper is quadruple the lines of code and creates new objects, which makes it considerably slower, especially if you have a lot of locations.

I'm slightly surprised (not really...) you have the audacity to say that. The only part of that particularly problematic is the regex split, which is not generally referred to as performance intensive unless done in excess. If you really cared, there are plenty of other places that use it at a much higher frequency.

**Comment by tips48** [comment]
Location loadedLoc = null;
try {
    loadedLoc = (Location) objectInputStream.readObject();
} catch (WorldNotFoundException ex) {
    loadedLoc = defaultLocation;
    System.out.println("Location could not be loaded, used the default location");
}
Why is this so bad?

**Comment by turt2live** [comment]
I think it's a matter over how lazy developers can get. 

There really shouldn't be an argument over this, if the team doesn't want to do it, they don't have to.

**Comment by Wolvereness** [comment]
> Why is this so bad?

Because it falls over completely in the cases where there are lists or arrays, or nested variables (two fundamental ways of how serialization works). Deserialization is not in some small scope where you simply write self-contained objects in a specific order to a file. Pushing Location to do something it should not is not good coding practices.

**Comment by Afforess** [comment]
> There really shouldn't be an argument over this, if the team doesn't want to do it, they don't have to.

This is a community project, unless the Bukkit has declared martial law and I missed the announcement.

> Because it falls over completely in the cases

There's nothing wrong with throwing exceptions in unexpected circumstances.

> Pushing Location to do something it should not is not good coding practices.

The ability to easily serialize location is hardly something I would consider outside the scope of the class.

**Comment by Wolvereness** [comment]
@Afforess You have some amazing knack for [card stacking](http://en.wikipedia.org/wiki/Card_stacking). You selectively quote what I said in an attempt to refute it, but ignore my reasoning for saying it. When you become more forthcoming, I can continue this discussion.

/edit @Afforess I will humor you:

> You failed to counter a single point, and so seek to distract everyone from your failure by changing the subject.

Okay... The whole point of my post was that there was nothing to counter.

> There's nothing wrong with throwing exceptions in unexpected circumstances.

I'd be stupid to argue against that point. Yes, it's good to throw exceptions when something is _unexpectedly_ wrong. However, you fail to refute my point that it is an _expected_ issue (missing worlds), which should be explicitly thrown. It does not relate to input and output and so it does not fall under IOException (a closer exception would be IllegalStateException). If we were discussing something outside the scope of serialization, an explicitly thrown exception would be applicable. However, this would break the concept of serialization, where we shouldn't expect to fail.

> The ability to easily serialize location is hardly something I would consider outside the scope of the class.

Didn't I just explain this in the post you quoted?

**Comment by Afforess** [comment]
By accusing me of manipulation, you yourself are manipulating. You failed to counter a single point, and so seek to distract everyone from your failure by changing the subject.

**Comment by Fishrock123** [comment]
```
"it is an expected issue (missing worlds)" (Please forgive my inability to quote)
```

How are missing worlds expected? This means one of three things: 
Either, The data you are reading from is corrupt. 
Or, The plugin developer made a mistake in his code to save stuff.
Or, the world was removed.

I don't understand why this exception would normally even happen under good plugin programming unless the world was removed?

As for Deserialization, (of which I am not overly knowledgeable) isn't the same thing simply happening when plugin developers use the alternatives? If so, what is the difference? Is it just that this pull is broken?

**Comment by Wolvereness** [comment]
> I don't understand why this exception would normally even happen under good plugin programming unless the world was removed?

That's exactly the point @Fishrock123 , you should not _expect_ a world to always exist. Worlds are regularly created, deleted, renamed. It's up to the individual plugin to decide how to deal with these occurrences, and in turn, the serialization of world specific objects.

/edit: To quote, start a line with >

**Comment by Fishrock123** [comment]
Therefore, if the world does not exist, throw an exception so that the plugin can catch it and continue on, warning the server owner if need be.

How is this a problem exactly? **We have to do the exact same thing** in a more complicated mannar anyways. 
If the world does not exist, my plugin does not use it.

**Comment by Wolvereness** [comment]
> ...**We have to do the exact same thing** in a more complicated mannar [sic] anyways.

If the _proper_ solutions already are more complicated, then this _fix_ would be a regression.

**Comment by Fishrock123** [comment]
I mean that we have to manually read world name, x, y, z in usual alternatives. Idk if this is _proper_ but it certainly is un-elegant.

**Comment by turt2live** [comment]
[Figure 1](https://github.com/turt2live/AntiShare/blob/master/src/com/turt2live/antishare/inventory/ASInventory.java#L167) The expected case a world may not be there when I request it.

Not that hard to deal with yourselves.

**Comment by Fishrock123** [comment]
Exactly, this shouldn't be a problem since we have to deal with it anyways.

**Comment by kitskub** [comment]
Honestly, I can understand both sides of this. However, I have to lean towards the idea that this should be pulled. While I agree that worlds should be expected to be created, modified, deleted, or otherwise during most plugin code, when when deserializing a location, the expectation is that a world is there. If it isn't, then this matches the criteria for an exception.

If this is pulled, it makes the end use cleaner for plugins by eliminating code that has already had to be suplicated across several plugins. If this is not pulled, the duplicate code continues.

In the end, I believe making location serializable will not just make some code slightlly faster v.s. parsing locations to/from strings, but it would also make the handling of persistent locations uniform.

**Comment by Afforess** [comment]
> Okay... The whole point of my post was that there was nothing to counter.

Clearly everyone else here disagrees. I suggest you either come up with a logical, eloquent argument against this pull, or rethink your position.

> However, this would break the concept of serialization, where we shouldn't expect to fail.

Serialization fails all the time. Hell, Java included a serialization version field to try and help developers minimize failure - but also makes failure part of the specification.

> If the proper solutions already are more complicated, then this fix would be a regression.

Huh? If this solution is less complicated than the way plugin developers are stuck with now, this pull request is an improvement.

**Comment by EdGruberman** [comment]
Perhaps the disagreement here comes from a lack of understanding the goal/focus of Bukkit?  I used to want Bukkit to have everything convenient in it also.  However, now that I've worked with it a bit more, it really seems to focus far more on simply providing a readable API to the obfuscated Minecraft code.

I almost wonder if things like this pull request here wouldn't make more sense in some wiki/tutorial compilation of common classes people might use in their plugins?  If there was some "plugin developer common classes" repository that might really help?

---

I am however confused on the argument of "to serialize or not to serialize" and I figure this is a good forum to pursue that understanding in.  Can someone help me understand the goals of serialization in Java more?  Are the following assumptions correct?
- serialization should be designed to save and load without exception
- when the architecture of a project dictates an object is by it's nature transient it is generally considered unwise to serialize that object as it breaks serialization goals

**Comment by Afforess** [comment]
> serialization should be designed to save and load without exception

Incorrect. The Oracle docs even use an example that throws exceptions during serialization.

http://java.sun.com/developer/technicalArticles/Programming/serialization/

**Comment by Wolvereness** [comment]
If the data saved is still intact and svuid number are the same, deserialization should not fail. The solution to missing worlds should be up to the plugin developer, as every plugin is different. Failing an entire deserialization because of a missing world is unacceptable for the API. It may be easier for plugin authors, it may be less code for plugin authors, but it's still not correct. Another point of interest is that Vector does implement serializable.

**Pull request closed without merging**
