### PR TITLE
Implements a chunk generator API

### PR DESCRIPTION
**Pull request by Raphfrk**
This adds the ability to use a custom generator for additional worlds.  The default world generator cannot be overridden with this pull.

There is a matching CraftBukkit pull.
https://github.com/Bukkit/CraftBukkit/pull/283

The plugin must create a class which implements the API and then submit an instance to the createWorld method.

The generator class must provide the following functionality
- Spawn point location

The standard spawn point generator searches for sand blocks.  If the generator generates no sand, then the spawn search will cause a memory overflow.
- Initial block data (pass 1)

The generator should fill the chunk with structural blocks.  

Complex blocks like chests and workbenches are not allowed at this stage.

Also, lighting sources should not be placed at this point.
- Decoration (pass 2)

In this stage the chunks can be decorated.  The generator can use the standard API calls to decorate the block.  It is guaranteed that a 2x2 grid of chunks will be available.

Decoration happens well away from the player's sight.
- Name the generator

This sets the directory in which the generated world is placed.  Names may not begin with "DIM" (to prevent clashes with Notch's generators and must have at least 2 characters (as a zero length string is effectively the default world).

### CODE REVIEW

**Comment by SpaceManiac** [comment]
+1'd

**Comment by Rigby90** [comment]
hmmm I believe Dinnerbone was working on the same thing and had it to this stage, not sure as to why it wasn't pushed etc. So not sure if theres anything else that needs covering before this is made a viable pull etc. 

Hopefully a response is just around the corner as I'm looking forward to this implementation... and have been for a few months now.

**Comment by Raphfrk** [comment]
I also submitted an easier version that was based on events and that wasn't pulled, as events were seen as to messy.  Hopefully, this one is closer to what they want.  I think it is closer to Dinnerbone's implementation.

Maybe I need to ask about it in IRC.  I have a few pulls awaiting consideration and I sometimes lose track of what the responses were.to various pull requests.

**Comment by RoyAwesome** [comment]
+1 please do this

**Comment by Raphfrk** [comment]
An official version makes this pull obsolete.

**Pull request closed without merging**
