### PR TITLE
Add player collision API

### PR DESCRIPTION
**Pull request by jedediah**
Add an API to control whether players can collide with other entities, such as mobs and projectiles

Implementation:
https://github.com/Bukkit/CraftBukkit/pull/776

### CODE REVIEW

**Comment by riking** [comment]
I'm not quite clear on the history of (Craft)Bukkit, but I think this might be from before the Vanish API.
Does the Vanish API do what this was asking for? Or is there something else that accomplishes this?

Also, has no teecket

**Comment by jedediah** [comment]
I added this and the affects spawning API so that a player could be made truly incapable of interacting with the game, which is crucial for spectators in PvP. Last I checked, Bukkit was not able to do this. These patches are still in use by SportBukkit and so I assume they are still required. There is no ticket because nobody ever told me I was supposed to make a ticket or where to make it. I justed forked, made the changes I needed, sent a PR, and left the rest up to you guys. When I get another free moment, I will find your bug tracker and make a ticket.

**Comment by turt2live** [comment]
The readme in the git root should help you out

**Comment by riking** [comment]
@jedediah The Vanish API is **PERFECT** for in-Minecraft game settings, I suggest you look into it.

**Comment by steveanton** [comment]
The vanish API only determines visibility and does not affect mob spawning. The only way to do this is via this patch.

**Comment by ryantheleach** [comment]
is the only difference between this and vanish, mob spawning? if so the names don't seem to match, and it should mesh better with the vanish api.

**Comment by gmcferrin** [comment]
@jedediah If you still want this implemented, please update it for the latest version of Bukkit.

**Comment by amaranth** [comment]
I seem to remember this having some serious issues client side because it assumes it collides with things. I can maybe see this still being useful despite that flaw but only when paired with the vanish API. Being able to shoot an arrow through someone and hit the player behind just doesn't look right when none of the 3 players involved actually see the arrow hit the final target.

**Comment by authorblues** [comment]
The value of this is only really clear when paired with the vanish API, and I would be content to only see this available in conjunction with the vanish API. How that would work precisely is unclear.

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/CraftBukkit/pull/776#issuecomment-24046845

**Pull request closed without merging**
