### PR TITLE
Superperm wildcard sub nodes.

### PR DESCRIPTION
**Pull request by ElgarL**
... sub nodes.

It allows for sub node tests without being forced to register every node, but also allows for easy negation.

This is mostly usefull where you need to test block id's as part of a permission.
Registering 4096 child nodes for each parent is cumbersome and also quickly brings bukkit to it's knees.

This allows you to assign a parent node to cover all sub nodes, yet still be able to negate specific child nodes.

Eg.
Grant the permission (true) 'towny.wild.build.*' (grants that specific node and all possible sub nodes of it).

Negate (set to false) the permission 'towny.wild.build.1'

All tests on sub nodes like 'towny.wild.build.52' would return true, where a test on 'towny.wild.build.1' would result in a false response.

```
/**
* Check this permission assignment including parent wildcards.
* If this permission has been assigned (true or false) it's value will be returned.
* If the permission is not directly assigned a node search for a parent wildcard will
* be performed, returning it's set value.
* If neither is found then the permissions default value will be returned.
*
* @Param inName
* @Return permissions set value if found, or the parents default value if using a wildcard.
**/
```

### CODE REVIEW

**Comment by NodiusC** [comment]
Nice, also, /me points at a [Pull Request](https://github.com/Bukkit/Bukkit/pull/590)

**Comment by jrtc27** [comment]
Would it not make sense to ascend the permissions node hierarchy rather than working down from `*`?

**Comment by ElgarL** [comment]
Ascending the heirarchy will not work as this is to support negated unregistered (undefined) child nodes, so they have no true hierarchy, and to support undefind child nodes.
for example..

'towny.wild.build.52' is never registered as a node so there is no heirarchy to test against.
However, with this code it does fall under the 'towny.wild.build.\* parent so can be tested and return true as with every other permutation of a child (without it ever having to be registered).

When you are testing block permissions (4 per block) you quickly get into a very high number of nodes which require registering.
To account for all the block Id's which MC supports (4096) with 3 possible permission branches, thats over 48,000 permission nodes.

**Comment by jrtc27** [comment]
I mean something like this:

towny.wild.build.52?
If not, then test towny.wild.build.*?
If not, then test towny.wild.*?
If not, then test towny.*?
If not, then test *?

Typically, the more specific wildcard permissions (e.g. towny.wild.build.\* rather than *) will be more commonly used, so this could be slightly quicker.

**Comment by ElgarL** [comment]
So reverse order.

Would do the same thing. I don't think it matters much (if at all) which order you test in, as the parent they have could be at any level.

**Comment by Wolvereness** [comment]
This changes the code to be much more inefficient on a call that is intended to be high-frequency. Also, where are permission nodes defined to use periods to indicate successive levels? _It's a convention we use._

Also, javadoc in wrong place. The interface Permissible would be the applicable place

**Comment by DrakiaXYZ** [comment]
I'm fairly sure the Bukkit team has stated that Permissions are no longer "node based", they are strictly Strings. Most plugin devs implement their own node-based usage (I do myself, it's just common sense) but that doesn't mean Bukkit itself will ever support said usage.

**Comment by jrtc27** [comment]
Plus I suppose the plugin could itself do this.

**Comment by ElgarL** [comment]
Every permission system does this already and always has done, until bukkit added superperms. It's bukkit that came in later and decided to change an already existing system. The convention has ALWAYS been to use periods to define successive levels.
All this does is add to superperms the abilities all other permission systems benefit from, and always have.
It brings bukkit in line with the already existing norms.

I agree it has a greater overhead. A very minimal one, and one with is already present in every other permission system and plugin which do this. It's a case of deciding wether the added functionality and compliance to norms is a greater benefit than the possible few extra ticks it takes to process.

**Comment by Wolvereness** [comment]
@ElgarL, the solution to this problem is very simply to let the plugin author just define nodes that end in .*

If you have a lot of permission nodes to add, then just simply declare them inside the children node of the parent permission. The plugin.yml is versatile to compensate for a memory leaking and slow implementation of asterisk nodes.

**Comment by ElgarL** [comment]
Sorry, that isn't the solution. A lot of permission nodes bring bukkit to it's knees. Upwards of 10 second lag when assigning perms on a world change etc.
The only solution is to allow .\* to cover unregistered nodes. So bukkit responding true when a .\* node is defined.
The current way around it is perms plugins doing this test (as they do), but superperms simply does not support this so it will always fail.

**Comment by resba** [comment]
@ElgarL Sorry, that is the solution. The . convention that we use in bukkit perms is purely that: A convention.

The simplist solution currently is to define the nodes in the plugin with .\* and then declare children nodes of the parent permission as @Wolvereness mentioned.

**Comment by ElgarL** [comment]
You mean that is the way it currently works. It's not a solution.

You do realize MC can now handle upto 4096 block ID's?
As the number of used block ID's increase so will the demand on permission nodes. Just ONE plugin registering 2000 permission nodes for block ID's will cause bukkit to fail with MAJOR server lag when updating permissions, if it's not future proofed. I have tested this and proven it a fact.

The only way to account for UN-registered nodes (not in plugin.yml or manually registered) is to support the wildcard.
Of course it's upto you bukkit devs, but this is a suitable soloution, and one which has proven to work since before there were any superperms. At some point you are going to be forced to implement some solution to this issue, when it becomes apparent there is an issue.

**Comment by feildmaster** [comment]
So you're forcing people to name their permissions with periods for your goal of \* to work?

**Comment by khobbits** [comment]
I don't see how 'force' enters this, and I don't think this needs to introduce/affect/add '*', just 'node.*' as a supported way of automatically including sub-nodes.

Another possible use case (sandcastles only on a beach)?:
- regionProt.mybeach.build.*: false
- regionProt.mybeach.build.12: true
- regionProt.mybeach.build.24: true

Registering each perm with the current system is not feasible, since 'mybeach' is a player created region, and 150+ block id's for each of say 100 player regions would cause a bit of a slowdown, not to mention there is also use/break/interact perms as well.

150x100x4 = 60k nodes.

If we pushed that to meet future proofing and all allowed item ids..
4096x100x4 = 1.6 million perm nodes.

**Comment by ElgarL** [comment]
@feildmaster Everyone DOES use periods. We have always used periods for permission node definitions.

**Comment by feildmaster** [comment]
That's not true though. You're assuming everyone does.

**Comment by feildmaster** [comment]
Also, in your example you create thousands of permissions. Doing it in a 'straightforward, we always do it like this' way.

However, what if you reversed your thinking? Instead of adding permissions of what they can, and can't do, assume they _can_ do anything, and create permissions when needed to specify they _can't_ do such a thing.

This reduces burden and stress from creating permissions you may or may not really need/use.

**Comment by khobbits** [comment]
I don't see how that makes any difference feildmaster, the point being is that all the perms would need registered no?

At the end of the day you would be checking to see if the perm exists any time any block is broken/used/interacted with?

In some 'staff' or 'special' areas you might want to closely control things, for example only allow people to make signs, in a shopping area, while in most others would only want to block a few things, like lava/tnt...

**Comment by feildmaster** [comment]
Which is a per-use case. You don't need to register 4096 permissions so you can check for a SINGLE permission.

**Comment by DrakiaXYZ** [comment]
Stargate has unlimited networks, but I only register a few permissions, it's very easy for a plugin to check permissions without registering every possible permission combination...

**Comment by khobbits** [comment]
So your suggesting the idea of just not using any negative nodes what so ever, we are back to nodes being set or not set?

This suggestion was about allowing for mass negation of perm nodes.

**Comment by feildmaster** [comment]
by breaking the current logic of permissions, and forcing a certain way to handle things.

And it was not for mass negation, it's for... "I want support for *"

**Comment by DrakiaXYZ** [comment]
I don't get why it would be so hard in a plugin to just support:
    stargate.network
    -stargate.network.whatever
That's exactly how I implement it, no need for \* nodes, no need for thousands of registered permissions, just a simple two-check process.

**Comment by ElgarL** [comment]
@feildmaster this change breaks nothing and doesn't force anything on anyone. it addsa new feature. One which superperms has been lacking since it's inception. No one will have to change a thing about how they do their perms.

This however does allow you to use.

towny.wild.\* to grant ALL possible sub nodes of towny.wild

Then you can call a SINGLE perm test to see if you actually have a node by testing 'towny.wild.blah.2'
If nothing has been defined or negated that test will return true (with the new system).

With the current system that test woudl fail and return false.

This means you actually have to perform THREE tests just to see if you have that node.
test for towny.wild.\* to see if you have all perms.
Test hasPermission("towny.wild.blah.2") and because it will always return false, you also have to do a test of isPermissionSet("towny.wild.blah.2")
If the first and thirdtests return true with the  second test returning false you don't have that permission, it's actually negated.

With the new code it would be a single test of hasPermission("towny.wild.blah.2)
No one has to change anything about any of their plugins. Everything still works exactly as it does now, but superperms now has an added feature to support unregistered nodes.

@TheDgtl, you know every permission you need as you are using defined nodes for defined objects. Other plugins, such as towny, have to test permissions based upon whatever block or item the person happens to use. In the future this could be any of 4096 different objects, with multiple types of actions they can perform. That amounts to a lot of combinations of possible tests required.

**Comment by resba** [comment]
Let's put it this way: Bukkit's permission system doesn't define subnodes using "." by design. We did this for a reason: So people didn't have to be bound to a specific way of formatting permission nodes. We use "." as a convention and that means it is **not required by the system to define a subnode**-- it's just easier to read that way.

Changing the code to the way you have it now will force developers to conform to a specific way of formatting permissions when the system was specifically **designed** to discourage this.

**Comment by ElgarL** [comment]
@resba I guess you didn;t look at the code then.

This pull does not alter the standard response a player will get from a perms test. It does NOT make the '.' a requirement to define a sub node. The whole system of super perms will still operate exactly the same as it does now.
This simply ADDS an extra feature where if using '.' to define sub nodes you CAN use a '.*' wildcare to cover all possible sub nodes.

This binds no one to any convention. Anyone can use '.,_|?#' or whatever they so choose to be their node delimiter. It just adds an extra ability when using the period. It in no way forces anything on anyone.

**Comment by mbax** [comment]
If you're not adding wildcarding for any delimiting, or a lack of delimiting, then this pull is ridiculously narrow-minded.

**Comment by turt2live** [comment]
People will take it as force though.

Although you've mentioned your intentions are not to force the delimiter, people will see that SuperPerms now uses '.' and will update their plugins (if required) thinking that their permissions are no longer supported by Bukkit.

**Comment by dumptruckman** [comment]
This PR would BREAK one of my plugins.  I have a sss.\* node that does NOT include sss.silk_touch.

There's also a more elegant solution.  Use config to define the list of blocks IDs and the name of a permission node to go along with those IDs.  Case closed.

**Comment by ElgarL** [comment]
@dumptruckman as has been explained earlier, registering ALL block ID's overloads Bukkit and causes it to fall on it's ass.

**Comment by feildmaster** [comment]
I'm going to deny this in saying.. Searching for "_if_ wild cards are present" by parsing heavily over a string is in no way going to happen.

If you can think of a better way to do this, please try to come up with one and bring it to our attention.

There is _never_ a reason to register thousands of permissions and parsing for "possible" wild cards is not going to happen. This check is... "If they have this permission."

How is this better than _you_ checking..
if they have this permission, or this wild card permission?

You just made the permission look up even harder in your attempt to... bypass registering thousands of pointless permissions.

**Pull request closed without merging**
