### PR TITLE
Fix sitting support for Ocelots

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
anyone?

**Comment by Fishrock123** [comment]
Needs associated CraftBukkit pull, and a leaky.bukkit.org ticket.

**Comment by ghost** [comment]
It isn't needed as the methods are already implemented in CraftBukkit(as in Wolf), just needs to add the method to Bukkit ;)

**Comment by EvilSeph** [comment]
Fixed in house, but thanks for the contribution!

**Pull request closed without merging**
