### PR TITLE
Added Value.java to org.bukkit.util - adds a universal way of storing many different objects to bukkit. Many many uses and will provide a universal interface for plugins to take advantage of

### PR DESCRIPTION
**Pull request by codename-B**
Added Value.java to org.bukkit.util - adds a universal way of storing anything to bukkit - useful for economy, prefixes, transitionary permissions etc.
- The integral part of data, that's a huge word.
- @author Nijikokun nijikokun@shortmail.com
- @author codename_B benbenben001@gmail.com
  *
- example usage of key for economy plugin playername.balance
- example usage of key for prefix plugin playername.prefix

### CODE REVIEW

**Comment by codename-B** [comment]
https://github.com/Bukkit/Bukkit/blob/master/README.md

Does not conform to this - just need to figure out HOW it doesn't conform.

**Comment by Raphfrk** [comment]
You should add a Plugin field too.

For example, 

```
public static boolean putValue(Plugin plugin, String key, Value value) {
```

This allows all Values associated with a particular plugin to be removed.  The value store itself would still be universal.  When a plugin is disabled, all values associated with the plugin could then be removed.

Also, the entire cache should be wiped when a reload happens (if you remove all mappings on disable then that happens automatically).  Otherwise, you may have objects associated with the wrong class loaders.

If the Value stored the plugin, then it shouldn't be to hard to keep track of which keys are associated with a particular plugin.

You could have a HashMap<String, HashSet<String>>, which maps a plugin name to the associated keys.  When a new key is added and it changes the associated plugin, you remove it from the HashSet of the old plugin and add it to the new HashSet.

Btw, to compress commits into one commit you can use

git rebase -i HEAD~2 (or larger number if you want to compress more than the last 2 commits into 1)

This brings up a text editor, you then change the first word on each line to s, except for the oldest commit and save.  You are then given the option to change the combined commit message (another text editor window).  

You can then use 

git push --force origin <branch name>

to overwrite the branch, in your case, I think it is origin master

**Comment by Afforess** [comment]
The only use I'm seeing for this is the ability to retrieve data after a /reload w/o having to serialize it to a file or database and then deserialize it on reload.

I mean, this data is all transitory, so it's not any different from a plugin using a hashmap internally, and calling up that plugin...

Unless I'm missing something.

**Comment by Raphfrk** [comment]
> The only use I'm seeing for this is the ability to retrieve data after a /reload w/o having to serialize it to a file or database and then deserialize it on reload.

I assumed that it was for plugin to plugin comms.  Also, keeping data between reloads is dangerous, since all objects (except Bukkit and standard java objects) will have new class loaders.

I see it as being useful as a patch to the Bukkit permissions system.  It would allow non-boolean permission-like data.  Ofc, in that case, ideally, it would be a direct patch to permissions.  Also, it doesn't allow parent/child inheritance like the permission system.

**Comment by Afforess** [comment]
> I assumed that it was for plugin to plugin comms. 

You still have to know what data you're looking for, so it's not revolutionary.

> Also, keeping data between reloads is dangerous, since all objects (except Bukkit and standard java objects) will have new class loaders.

Gotta love classloaders...

**Comment by codename-B** [comment]
It's all standard java objects there anyway - String, Float, Integer, Boolean etc, but making it clear onDisable() might not be a bad idea. In that case, why don't Bukkit permissions clear onDisable()?

Bukkit permissions persist after a /reload - the only way to get rid of them is to specifically unset the permission, this is no different.

The point was that several chat plugins could agree on Value.getValue("playername.prefix").getString() for example. I was trying to push for a standardised interface via Bukkit services - then realised that they would have to use my namespace for the service provider, so we came up with the idea of a standardised store of raw data, accessible to any plugin.

This would also be useful for economy plugins as a quick store of balance Value.getValue("playername.balance").getDouble() for example, but that would need some more framework around it.

I may add an unsetAll() method however, but possibly after Bukkit permissions gets it's unsetAll() method, as I want this to emulate permissions functionality, but without the hierarchy structure, and with more flexibility in the data stored.

**Comment by codename-B** [comment]
Then again, to make it even easier on devs - I could always add a setPrefix(Player player) and a getPrefix(Player player) method - but that may be too specific.

**Comment by Afforess** [comment]
> It's all standard java objects there anyway - String, Float, Integer, Boolean etc, but making it clear onDisable() might not be a bad idea. In that case, why don't Bukkit permissions clear onDisable()?

If this cleared onDisable I would not see even the slightest usefulness of the system. Currently, I can see a small value in a cache that persists while the server is alive. Otherwise, how is this different from me making a hashmap in a plugin? This is going to end up just like Bukkit Services, unneeded bloat that ultimately few need and fewer use. The use cases seem tenuous at best.

**Comment by Afforess** [comment]
What I WOULD like to see is a way of storing serializable data to entities and blocks. If we could do player.getData(Object) or block.setData(object) that got serialized when server saved them (not into the nbt files...possibly a separate yml?), that would be very useful.

**Comment by codename-B** [comment]
The whole point was that this is better than Bukkit services - you don't need the same namespace - you just need the same String key; which was the shortcoming with Bukkit services - and why it's not used. I have written 3-4 plugins using Bukkit services now, and it's all well and good, but it's no different to having your own class instantiated in the plugin itself, except for there's only one of them instantiated via Bukkit services which has no real advantage other than memory usage.

This would overcome that and be very easy to use - I speak from experience, I was trying to get every "info" plugin out there to use my Bukkit services interface so that there would be a standardised store of data for plugins like CraftIRC3 and MCStats3 (two which use the Bukkit services provided by my plugin).

It's much prettier to just use the same String key, than it is to have someone elses namespace in your package.

Also, this is different to you having a HashMap in your plugin as you can access the data here from any plugin.

**Comment by codename-B** [comment]
Afforess - I have a library for serialisable Block and Location objects.
That's seperate to this, though if I did pull that, this would be updated to support those serialised objects.

**Comment by Afforess** [comment]
> The whole point was that this is better than Bukkit services - you don't need the same namespace - you just need the same String key; which was the shortcoming with Bukkit services - and why it's not used. I have written 3-4 plugins using Bukkit services now, and it's all well and good, but it's no different to having your own class instantiated in the plugin itself, except for there's only one of them instantiated via Bukkit services which has no real advantage other than memory usage.

All well and good, but it's still an uncompelling feature. Couldn't a standardized plugin be made to do this? Maybe it's just me. :/

**Comment by tips48** [comment]
Ooooh, love it :D

**Comment by codename-B** [comment]
Afforess - if a standardised plugin is made to do it - people will want to make their own versions of the standardised plugin.
I know this because I made bInfo as a standardised plugin - and out came uData and mInfo within a week, all equally incompatible.

Bukkit needs this - as a way for there to be a universal store of raw data with easily usable keys.

**Comment by CelticMinstrel** [comment]
I don't really see the point of this either... if your reason for doing this is to replace your info interface, then why did you not simply put your info interface into Bukkit, perhaps in the services package? As you said, the trouble with services is that you need someone else's namespace for the interface.

**Comment by Afforess** [comment]
> Afforess - if a standardised plugin is made to do it - people will want to make their own versions of the standardised plugin.
> I know this because I made bInfo as a standardised plugin - and out came uData and mInfo within a week, all equally incompatible.

Encourage submissions from the community, merge the 3 projects. Didn't we just cover this? http://xkcd.com/927/

**Comment by codename-B** [comment]
CeltricMinstrel - this is more likely to get pulled than my services interface. It has more flexibility than simply strings, which is all my services interface handles. It's not to replace it, but to allow other plugins to easily emulate what it does.

Afforess - I spent about an hour trying to convince Nijikokun to use Bukkit services to do it. We eventually arrived at the idea for this, because he wanted to do more than players in his.
The projects are unmergable because each dev wants to do things in their own ilttle way. I could just make one giant plugin that's a mix of all three and release it and give people the option to choose which they want to use via a configuration option, if this doesn't get pulled, that's what I may have to do.

I've told the dev of mInfo to pm me his source code and I'll add it for him - I suppose I could just decompile and post the new one on his plugin page.

What I could do is just make a generic namespace for this, edit it, and add it into all their plugins.
This would be no different than it getting pulled into Bukkit of course, but it's a lot less likely to be supported, and you lose the ability for data to persist between reloads.

**Comment by Raphfrk** [comment]
> This would also be useful for economy plugins as a quick store of balance Value.getValue("playername.balance").getDouble() for example, but that would need some more framework around it.

You would need to make that atomic though.  Well, maybe not for get balance, but for increment/decrement/transfer.

There is an AtomicReference, which is effectively an atomic object.

You would have to update your set method to have inputs for the old and new values.

Your HashMap would have to be changed to something like

```
ConcurrentHashMap<String, AtomicReference<Object>>
```

One a key is added, you would have to make sure not to change it.  ConcurrentHashMap has a putIfAbsent method for that purpose.

> What I WOULD like to see is a way of storing serializable data to entities and blocks. If we could do player.getData(Object) or block.setData(object) that got serialized when server saved them (not into the nbt files...possibly a separate yml?), that would be very useful.

That would be what the persistence system was supposed to do ... but is a major hassle.

The serialization system is much easier to get to work.  You just have to remember to reset the ObjectStream after each object is processed.  At one point, I almost went with using SQL but with byte BLOBs.

If yml was being used, you could use a hex string as the value.

**Comment by xZise** [comment]
And this better? For example your suggestion with `playername.prefix` is only working if everybody uses this. Maybe those values should stored similar to the permissions and extend Player with a `getValue()` method … or what I would prefer `getStringValue()`, `getIntValue()`, `getDoubleValue()`.

Fabian

**Comment by Afforess** [comment]
> And this better? For example your suggestion with playername.prefix is only working if everybody uses this.

That was my point too. >.>

**Comment by codename-B** [comment]
xZis Afforess the point I'm making is if this is there - it is going to be easy to get everyone to conform to playername.prefix
The reason people aren't using a standard bukkit services interface for things like prefix/suffix is because it's quite complex - which is fine for people who have a vague idea what they're doing, but to everyone eles it's just a "WTF?" moment and then they move on.

This provides VERY simple methods for partial persistence. If I added ObjectOutputStream and ObjectInputStream onDisable onEnable to make it a form of persistance, would that increase it's value in your eyes? It is something I have considered. I may work on including my Bukkit object serialisation in this too.

However - I will add some new methods to this - tweak some things based on suggestions and we'll see where it goes from there.

**Pull request closed without merging**
