### PR TITLE
YamlConfiguration support for ConfigurationSerializable inside collections

### PR DESCRIPTION
**Pull request by GICodeWarrior**
For example, .set("foo", List<? extends ConfigurationSerializable>) is properly saved and loaded with this change.  This addresses https://bukkit.atlassian.net/browse/BUKKIT-425.

This also fixes a couple issues with ItemStack serialization.

### CODE REVIEW

**Comment by Killili** [comment]
I have the same problem, i hope this gets accepted soon.

**Comment by Dinnerbone** [comment]
A Location can't be serialized like this because the world doesn't exist as most configs are loaded.

**Comment by GICodeWarrior** [comment]
OK, I have updated it to make world lookup lazy.

Do the rest of the changes look good?

**Comment by Dinnerbone** [comment]
And now we're introducing the prospect that Location.getWorld may be null, and may never change. I'll have to ponder about that, can you split it apart from the pull request and we'll come back to it later? I'll review the rest.

**Comment by GICodeWarrior** [comment]
Done.  New pull request for location support.
https://github.com/Bukkit/Bukkit/pull/471

**Comment by Dinnerbone** [comment]
Thanks!

**Pull request closed without merging**
