### PR TITLE
Use event class instead of event to prevent the event from staying in memory

### PR DESCRIPTION
**Pull request by ScoreUnder**
...when using plugin profiling.

(And all associated entities / players / NetServerHandlers / packet queues / AxisAlignedBBs / etc.)

### CODE REVIEW

**Comment by feildmaster** [comment]
This is breaking.

**Comment by ScoreUnder** [comment]
It also frees up a ton of unused resources :/... I honestly doubt anyone has ever touched the TimedRegisteredListener class in a plugin.

The alternative, returning null in getEvent() instead of removing it altogether - would that be viable?
-=-=-
Edit - should no longer be breaking

**Comment by Wolvereness** [comment]
@ScoreUnder changing a return to 'null' is still breaking. Admittedly, I'm in favor of just removing that particular method, but at the same time... Plugin timing should not be left on, so in turn, this should be a non-issue anyway.

I will say I would really like to not rely on the 'first' event (not sure how feasible it would be without actually sitting down and examining it), and instead use the event class that the method signature requests. Again, I haven't looked into this, so I'm not sure exactly how the reporting data is handled or the entire relevance of the type of event.

**Comment by md-5** [comment]
That's the part that I want to point out.

> It also frees up a ton of unused resources :/... I honestly doubt anyone has ever touched the TimedRegisteredListener >class in a plugin.

**Comment by ScoreUnder** [comment]
~~@md-5 Not sure what you mean - RegisteredListener does not declare getEvent(), and nothing in Bukkit subclasses TimedRegisteredListener, so to use getEvent() they will need to explicitly use the TimedRegisteredListener class.~~

And just for the record, I run my server with plugin profiling always on - means if the server gets hit hard by lag I can reset timings, wait for the samples to build up, and write them to a file to see if any specific plugin was the cause

**Comment by md-5** [comment]
> And just for the record, I run my server with plugin profiling always on - means if the server gets hit hard by lag I can >reset timings, wait for the samples to build up, and write them to a file to see if any specific plugin was the cause

Same, and I believe we clarified the top part on irc.

**Comment by riking** [comment]
Is this still needed and/or relevant?
Does it have a ticket?

**Comment by riking** [comment]
Line 30: remove the linebreak, make it `} else if .... {`.
Remove the old method and make it all breaking, instead of returning null.
When firing an event, check the previous event class; set the event class to the closest common superclass of the two and store that - this means that getEventClass should return the most common supertype of all events that were fired over the lifetime of this listener.

**Comment by ScoreUnder** [comment]
Abra kadabra presto updatio

**Comment by riking** [comment]
@Wolvereness You approved the idea without writing up your reason again.

@ScoreUnder This looks good, but I'd like to see a unit test verifying the behavior of the newEventClass code, for future reference, as the surrounding code doesn't do a great job of explaining what it's doing, and the code itself does an even worse job of explaining how it's doing it (in TimedRegisteredListener).
Although this may just be because I learned how to write a unit test recently.

Additionally, the behavior of hasMultiple does not match its Javadoc, nor did it previously. I'm aware that it was like this already, but we should change the javadoc on it to say "multiple KINDS of events".

I don't think any of the Bukkit API uses the `@since` tag, do they? Because it might be appropriate here, as most plugins using this will probably need to be rewritten, and it may be a good idea to tell them when it broke.

**Comment by riking** [comment]
@ScoreUnder Can you add the unit test?

**Comment by ScoreUnder** [comment]
Given the new logic a name (method), and in the process reduced unnecessary runtime type checking (asSubclass).

I'm not too big on unit tests, so please tell me how it looks.

**Comment by riking** [comment]
Sure, that looks good. Could've been multiple tests, but whatever.

**Comment by riking** [comment]
Just noticed this still doesn't have a leaky ticket linked, can you take care of that?

**Comment by Wolvereness** [comment]
FFR, the test case uses incorrect line-endings.
https://github.com/Bukkit/Bukkit/commit/e7f3d552215a9d117a4616801e14e715d4425efb

**Pull request closed without merging**
