### PR TITLE
Added setRecipients() to PlayerChatEvent

### PR DESCRIPTION
**Pull request by oliverwoodings**
Implemented a setRecipients() method to PlayerChatEvent. This will solve the issue that people have at the moment of plugins like HeroChat (that implement chat rooms) just cancelling the PlayerChatEvent when they only want to send a message to a few people.

The issue with this is obviously that other plugins can't edit the message either. So if, say factions, wanted to add the faction of the player in, it woulnd't be able to because the event is cancelled.

By using setRecipients and setMessage there will be no need to cancel the event anymore and other plugins can then add in their own stuff whilst chat plugins can still manipulate the player list so rooms are possible.

### CODE REVIEW

**Comment by Afforess** [comment]
Can't one just use getRecipients().clear() and then add the people they want? Come on people, lists/sets are references, treat them that way!

**Comment by oliverwoodings** [comment]
I just realised how retarded I am.

**Comment by Afforess** [comment]
Yeah - I don't mean to be harsh, but this isn't the first instance of this coming up. IIRC, someone tried to add a similar feature (e.g setDrops) to the getDrops on EntityDeathEvent, when it's a list that is already mutable.

**Comment by sunkid** [comment]
There is nothing wrong with setter methods even if the getter gives you a mutable object. It's just a little utility method after all, which IMHO adds to a cleaner, more intuitive API. :)

**Comment by Afforess** [comment]
Really? IDK I'd call memory waste (it is memory waste if you create a new object to replace the existing set) a "utility". Plus, you lose the "final" modifier, which is safer & more efficient.

**Comment by sunkid** [comment]
It's only memory waste if the garbage collector does not take care of it!

The final modifier does have some use here. It doesn't in the case of the EntityDeathEvent you brought up.

**Comment by Afforess** [comment]
sunkid: Assuming a perfect world, where the Java GC takes care of it the nanosecond Bukkit releases it, it's still a waste of CPU. Creating objects is not instantanoues, and PlayerChatEvent is called frequently.

**Comment by sunkid** [comment]
Even if you had the data to show that "getX().clear(); ..." is more efficient than "setX(...)", I would still argue that the API is cleaner with both setters and getters where applicable. We'll just have to agree to disagree on this, I am afraid.

**Comment by Afforess** [comment]
I think clear uses a linear search to remove the values - but it may depend on the type of set. Anyway, I guess so.

**Comment by Dinnerbone** [comment]
We are not adding setters for exactly the reason that this issue was created; people think that's how you should alter the list.

It completely destroys the idea of being friendly with other plugins, and that's far from what we want. You already have complete access to do whatever you want with the list, use that.

**Comment by sunkid** [comment]
Your last two sentences are contradictory ;)

**Comment by Dinnerbone** [comment]
No, you misunderstood. Destroying the list to add a user is 100% unfriendly to other plugins. Clearing a list because that's actually what you intended to do, isn't.

**Comment by Afforess** [comment]
Thank you Dinnerbone - excellent to see another reasonable individual - and good point too.

**Comment by sunkid** [comment]
As long as events are passed to plugins sequentially, any preceding plugin can already do what they want with any lists they have access to, as you pointed out. The following plugins have to take what they get, no?

**Comment by Dinnerbone** [comment]
Yes. But you're missing the big key here; intending to clear the list = ok, that's what you want to do. Clearing the list because you see a setter and you think that's how you add a new entry or remove a single entry = not ok. That's not what you wanted to do.

As it is currently, you can clear the list if that's actually what you want to do. You can't if it's not what you wanted to do. This is perfect.

**Comment by sunkid** [comment]
Hmmm... no, I don't see the point. If I want the list to change, I use the setter or as is now, I use the list directly. What is the difference? Unless someone seriously misunderstands what setters do (as you seem to be saying), the result is the same: subsequent plugins will see a different list of objects and anything preceding plugins have done may be changed.

**Comment by Dinnerbone** [comment]
A setter replaces the list with a new one. Any changes to the previous list most likely become nullified (unless the author is smart, in which case they shouldn't be doing this anyway.).

Altering the list directly preserves all changes and does exactly what they wanted, so everyone is happy.

The issue is moot. People can do what they want as it is. We aren't adding a setter.

**Comment by sunkid** [comment]
Altering the list directly only preserves changes I want to preserve. If I want to preserve elements of a prior list, I can incorporate these into the new list passed to the setter. Anybody else holding on to a pointer to a prior list is none-the-wiser.

I see the philosophical point ("we don't give you a setter, so be smart what you do with the list you get", if I understand you correctly), but I don't buy the argument that setters are harmful or politically incorrect to use when changing the list directly is an option and supported.

**Comment by Dinnerbone** [comment]
You can do everything you want so you don't _need_ a setter. We don't provide an optional setter because people think that's how you're supposed to alter the existing list. Nobody's hurt, people are educated.

**Comment by sunkid** [comment]
You don't <i>need</i> getters either, just make the field public! ;)

Seriously, there is no education in leaving out a setter when you can still do the same stuff you can do with it. If you want the lists to not be modifiable, make them that. If you want plugin authors to play nicely, write a white paper. If you want resulting lists to honor all plugin modifications, your setter would have to be damn smart. Alas, given the level of sophistication of plugin coders out there (myself included), your well-meaning attempt at education is most definitely getting lost.

Unfortunately, I don't have a good alternate solution to what I completely agree is a problem. It's the same as asking folks to play nicely with the priority levels they set for event listeners, I think. You can only do so much to further interoperability while still allowing for flexibility and performance. All I am really saying is that leaving out a setter does not communicate that to me.

**Comment by Afforess** [comment]
Sunkid - it's a litmus test of sorts. If the plugin developer can't figure it out, they probably shouldn't be messing with it in the first place.

**Pull request closed without merging**
