### PR TITLE
[B+C] Improve and simplify sender.sendMessage. Adds Bukkit-4480

### PR DESCRIPTION
**Pull request by kezz**
**PR Justification**
At the moment we have two functions that _sorta_ do exactly the same thing. I thought, why not replace this with one function that encompasses all the features of the first two, and even adds more.

**PR Rundown**
This PR replaces both of the current `sender.sendMessage(String([]) message)` functions with one, namely `sender.sendMessage(String... messages)`. As the JavaDocs say, I've also added the ability for developers to send new-line messages by simply doing `sender.sendMessage()`.

**Related Links**
Bukkit PR: [893](https://github.com/Bukkit/Bukkit/pull/893)
CraftBukkit PR: [1188](https://github.com/Bukkit/CraftBukkit/pull/1188)
JIRA ticket: [Bukkit-4480](https://bukkit.atlassian.net/browse/BUKKIT-4480)

### CODE REVIEW

**Comment by riking** [comment]
This change as it stands is bytecode-breaking because you remove the one-String method.
I suggest only changing the array method to varargs, which is bytecode-compatible.

**Comment by kezz** [comment]
@riking Ah yes. I'll put back the single string method (but deprecate it)

**Comment by mbax** [comment]
You're going to deprecate one of the most commonly used methods, at what gain?

**Comment by kezz** [comment]
@mbax ease of use really. `sender.sendMessage("hey", "You", "How")` seems easier.

But if you guise don't like it I'll just close this :smiley:

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/CraftBukkit/pull/1188#issuecomment-20570314

**Comment by riking** [comment]
A change that has a hope would be to change JUST the array method to varargs.

**Pull request closed without merging**
