### PR TITLE
[B+C] Added SpawnReason for creature spawned by nether portal. Fixes BUKKIT-3148

### PR DESCRIPTION
**Pull request by KODZIO**
##### The Issue:

There is no clear way to detect when Pig Zombie (or other entity, if ever so) is spawned by Nether Portal.
##### Justification:

Allows developers to easier detect when entity is spawned by nether portal. Right now Bukkit returns spawn reason as spawned by using spawning egg when pig zombie is spawned by nether portal. This makes confused a lot of developers and requires finding a way around that problem.
##### PR Breakdown:

This PR is adding a clear way to check if entity was spawned by nether portal and fixes problem with wrong spawn reason when pig zombie is spawned by nether portal.
##### Testing Results and Materials:

[SpawnReasonTest plugin](http://www.mediafire.com/?mpr9xzgbxh1z8sp) - Prints EntityType and SpawnReason in console when CreatureSpawnEvent occurs.
[SpawnReasonTest plugin source code](https://github.com/KodekPL/SpawnReasonTest) - Source code of SpawnReasonTest plugin.
[Pig Zombie Grinder Map](http://www.mediafire.com/?i973jkyzcl3zlzj) - Map with pig zombie grinder makes checking spawn reason of pig zombie spawned by nether portal easier.
##### CraftBukkit PR:

[Bukkit/CraftBukkit#1237](https://github.com/Bukkit/CraftBukkit/pull/1237)
##### JIRA Ticket:

[JIRA Ticket #3148](https://bukkit.atlassian.net/browse/BUKKIT-3148)

### CODE REVIEW

**Comment by ST-DDT** [comment]
Isn't there a EntityTeleportEvent?
Or are these PigZombies just randomly spawned by the portal and did not move through?

**Comment by turt2live** [comment]
What about the end portal? I think mobs can fall through that

Edit: And yea... why a spawn event?

**Comment by KODZIO** [comment]
Pig Zombie just randomly spawn in portal frame, CreatureSpawnEvent catches that. That starts to happen in Minecraft 1.3.1. Just try the map I included, it works even when nether world is disabled.

@turt2live When entity teleport through portal (Nether/End), then EntityPortalExitEvent is triggered.

**Comment by turt2live** [comment]
I have never heard of a case where pig zombies just spawn on the portal frame - How can I replicate this?

**Comment by KODZIO** [comment]
@turt2live Download map that I included in testing materials. Pig Zombie massively spawn in nether portals frames allowing people to do gold farms. They spawn even without nether world being enable.

**Comment by turt2live** [comment]
I never knew that that was a feature... Guess it is though: http://www.minecraftwiki.net/wiki/Zombie_Pigman#Farming

**Comment by KODZIO** [comment]
Updated to latest changes in Bukkit. CraftBukkit PR does not need any updates.

**Comment by turt2live** [comment]
Somehow the update you did failed. 

The git log is all messed up and there are merge conflicts. Please repair this.

**Comment by KODZIO** [comment]
I have no idea what could it be, I don't use git that much, but I will check it out soon.

**Comment by turt2live** [comment]
I managed to fix it on my end :)

**Comment by turt2live** [comment]
Pulled with some modifications, thanks!

https://github.com/Bukkit/Bukkit/commit/574f7a8c6cb5ac2746831b0a4f5277cc203a41bf

**Pull request closed without merging**
