### PR TITLE
Added service register and unregister events.

### PR DESCRIPTION
**Pull request by zml2008**
This allows plugins to be notified when services are registered or unregistered, similar to the plugin enable and disable events.

Corresponding ticket is BUKKIT-816

### CODE REVIEW

**Comment by feildmaster** [comment]
Oh I like.

**Comment by t3hk0d3** [comment]
+1

However should be updated to new even system

**Comment by zml2008** [comment]
Updated for the new events system

**Comment by EvilSeph** [comment]
Pulled, thanks!

**Pull request closed without merging**
