### PR TITLE
Fix site.xml, rev 3

### PR DESCRIPTION
**Pull request by lukegb**
Pull me.

### CODE REVIEW

**Comment by resba** [comment]
Support!

**Comment by codename-B** [comment]
So why isn't this pulled yet?

**Comment by Rigby90** [comment]
Because they've been busy with other things and this is only for convenience, if you take a look at the JD pages these links already exist.

**Comment by md-5** [comment]
I though luke was a Bukkit team member, shouldn't he get access?
But anyway look at the backlog of PRs everyone is busy.
This would probably be a cut and paste not a pull anyway.

**Comment by lukegb** [comment]
Committed in cd5e45b4157e234e5fd9f20f34f3693b498da283 and 60458c437fec1669dceb64874ae491af1d40ea35

**Pull request closed without merging**
