### PR TITLE
locationFacing() - ticket #14 on redmine

### PR DESCRIPTION
**Pull request by taylorkelly**
Returns a new Location with the same coordinates, but facing the paramaterized Location.

### CODE REVIEW

**Comment by Raphfrk** [comment]
The method is already in Location, so maybe call it just facing?

Also, there is a function

Math.atan2(y, x)

This gives the arc tan of y/x, but it correctly handles all 360 degrees.  It would save you having to correct for the signs for yaw.

**Comment by taylorkelly** [comment]
fixed :)

**Comment by Dinnerbone** [comment]
Possibly call this setFacing and have getFacing return the current location they're facing?

**Comment by taylorkelly** [comment]
This doesn't change the Location it's called upon, so having it be setFacing doesn't make sense; it returns a new location at the same coordinates, but the new one is facing a given location.

If instead of this, you wanted it to actually modify the location, that could work too.

Edit:
-.- I always accidentally hit "Comment and Close"

**Comment by Dinnerbone** [comment]
Reopened.

I'm just thinking for consistency, we don't set X by making it return a new location. But reconsidering, I'm not sure now. :D

**Comment by Raphfrk** [comment]
There is no specific location a location is facing, it is a line.  

Actually maybe it should just use Vectors.

loc.getFacing(loc2)

would return a vector pointing at loc2.

loc.setFacing(loc.getFacing(loc2))
and
loc.setFacing(loc2)

would actually point the player at that location.

**Pull request merged**
