### PR TITLE
Add interface for setting a pig zombie's anger level

### PR DESCRIPTION
**Pull request by CelticMinstrel**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
[Corresponding CraftBukkit pull request](https://github.com/Bukkit/CraftBukkit/pull/375)

**Comment by xZise** [comment]
Why could you only set the anger to a boolean and you return a int. I suggest either to use only booleans, or to define what which anger level mean.

Fabian

**Comment by CelticMinstrel** [comment]
...I set anger level because that's how pig zombies work. Their anger is not a boolean but an integer that, if I understand correctly, counts down in certain circumstances. The only reason I added the extra function taking a boolean is because some people might not care about that detail. Notice that there's also a setAnger taking an int.

Only using booleans would not be a good option, because the anger isn't a boolean for pig zombies.

**Comment by xZise** [comment]
Yes if they are working via ints. And I'm sorry :( You are indeed added the setAnger(int) method to define a specific integer anger level. But maybe also return a boolean if a pig zombie is angry?

Fabian

**Comment by CelticMinstrel** [comment]
I suppose there's no real reason not to have the boolean isAngry method in addition to what I have here.

**Comment by xZise** [comment]
And when is a pig zombie angry? If the anger is greater zero or greater 400. So now I have to guess/search any documentation is there is one.

Fabian

**Comment by CelticMinstrel** [comment]
As the CraftBukkit portion of the pull request makes clear, the pig zombie is angry whenever the anger is greater than 0... but that's also the intuitive thing to expect, is it not?

**Comment by xZise** [comment]
Not really, as you set the anger to 400 if you set the pig zombie to angry. And I didn't saw the additional commit for isAngry(). Without the commit there is no definition when the pig zombie is angry. I only wanted to suggest to make it usable and easy to use.

Fabian

**Comment by CelticMinstrel** [comment]
Well, 400 is because that's the minimum natural anger a pig zombie will get from being attacked.

**Comment by Afforess** [comment]
Looks handy. Any word, @EvilSeph?

**Comment by EvilSeph** [comment]
Pulled, thanks!

**Pull request closed without merging**
