### PR TITLE
setTexturePack is now deprecated & added setResourcePack

### PR DESCRIPTION
**Pull request by Guichaguri**
https://github.com/Bukkit/CraftBukkit/pull/1272

### CODE REVIEW

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

I don't see justification for this, nor do I think there will be any (you're welcome to catch up on the contributing and we will consider reopening the PR). However, we're talking about the difference between "texture" and "resource", which is rather trivial, and the implementation is the same anyway.

**Comment by Guichaguri** [comment]
Is not only the name of the method, the channel changed from MC|TPack to MC|RPack.

**Comment by Wolvereness** [comment]
Then report the bug, make a PR that only contains that fix, and follow the contributing guidelines.

**Comment by Guichaguri** [comment]
Can I change the name of the method in the same commit? The TexturePacks are now ResourcePacks.

**Comment by riking** [comment]
It makes no sense to change the name, that's a needlessly breaking change.

**Pull request closed without merging**
