### PR TITLE
Added PluginExceptionHandler and method to call from SimplePluginManager

### PR DESCRIPTION
**Pull request by alkarinv**
Added the ability for plugins to have a method to handle their own
uncaught exceptions during Bukkit Events. Similar to a per plugin
Thread.UncaughtExceptionHandler

### CODE REVIEW

**Comment by Wolvereness** [comment]
1) This can already be emulated by a plugin.
2) Your implementation is restrictive.
3) Your implementation is unsafe.
4) There is no justification. I include this because I assert that a proper (read: the) justification warrants a different (read: more proper) solution.

**Comment by alkarinv** [comment]
You seem to like terseness so,
1) how exactly? there is no way to globally catch errors/exceptions for plugins
2) restrictive? is it because the implementing class must be a Plugin? if so its easy to make it more general
3) How so? You are already trusting the plugin to properly execute the bukkit Event, not sure how this is any different.  
4) What do you mean by a more "proper solution"?  Do you mean more general?  Do you mean it should be handled by a central Bukkit class?

**Comment by Wolvereness** [comment]
1) Forwarding event handlers with try{} catch {} blocks. Not quite a revolutionary concept here. Additionally, I recommend actually looking into the plugin manager / event API you are using.
2) Sure, you can claim it's easy, but that begs the question; why didn't you? I made an assertion, you seem like you clearly understand it, but you don't make a logical counter point.
3) I don't need to justify something that is correct; I recommend attempting to sabotage your own implementation from a plugin's perspective.
4) I don't need to argue against something that you haven't presented. Your lack of justification is point enough; when you include a justification we can continue discourse.

/edit: On a final note, I do enjoy terseness.

**Comment by alkarinv** [comment]
1) Not sure what you mean, are you saying wrap every event method with a try/catch?  There is a reason java has a global exception handler, and I think it would be useful for plugins as well.  I did look into the plugin manager, and I couldn't find anything similar.  The closest is AuthorNagException, but that is only during loading, and isn't general

2) Because the solution works and I wanted feedback as to whether it would even be accepted even if I wrote a more general version.  From what you are saying it's a good thing I didn't write more.

3) We are coders here, if a plugin wanted to sabotage something they could have done it inside the Event itself, why wait for their own exception. You trust the plugins enough that you simply wrap callEvent() with a try catch.... exactly what I have done.  If you are talking about some sort of infinite loop situation with Events then that is something I could fix.

4) My justification is that a single method to handle exceptions is a useful concept.  It's useful enough that most modern languages have a way to tap into it (python, java, ...). For plugins, it could be used to write to a log, notify admins if they wanted to know in game when a plugin was causing problems, or many other uses.

What I'm looking for is IF properly implemented would this be something that would be accepted.

**Comment by Wolvereness** [comment]
1) You can implement your own handler....
2) To do what you want to, this is not the API you are looking for.
3) compare https://github.com/alkarinv/Bukkit/blob/a23e5317c5ce185cd8f7df9b25652a2fe6810adc/src/main/java/org/bukkit/plugin/SimplePluginManager.java#L491 and https://github.com/alkarinv/Bukkit/blob/a23e5317c5ce185cd8f7df9b25652a2fe6810adc/src/main/java/org/bukkit/plugin/SimplePluginManager.java#L497
4) Writing a log, notifying admins, etc. is more along the lines of a crash report API. It's usefulness is limited to the scope a different change. You need to justify your particular solution.

**Comment by alkarinv** [comment]
1) A handler that is an intermediate step between bukkit and all events doesn't sound like a very efficient solution. I think most people would rather handle after the fact.
2) alright
3) Yes, my bad. It should definitely be catching Throwable.
4) A crash report API sounds like overkill.  I thought a general method would be a good way for an easy way for plugins to handle their own errors.

I've got it, this is not a change you are interested in.

**Pull request closed without merging**
