### PR TITLE
[B] Adds the ability to get the amount of hunger and saturation a Material restores. Adds BUKKIT-3909

### PR DESCRIPTION
**Pull request by aidangoettsch**
Justification for this PR:

We have isEdible()

However it would be useful to be able to pull how much hunger or saturation an item is worth without using NMS or hard coding the values.

Having this function would mean that some plugins might not need to be updated every time a new food item is added.

PR Breakdown:

This PR adds the ability to get the hunger and saturation a Material will add, using Material.getHunger() and Material.getSaturation(), respectively. 

Testing Materials:

JAR: https://dl.dropbox.com/u/4258783/HungerCallsTest.jar | Source: https://github.com/yayestechlab/HungerCallsTest

JIRA Ticket:

BUKKIT-3909 - https://bukkit.atlassian.net/browse/BUKKIT-3909

### CODE REVIEW

**Comment by aidangoettsch** [comment]
I also fixed the gitignore to ignore the .DS_Store files below root because everyone hates the .DS_Store files. :)

**Comment by Crazy-Uncle-Harris** [comment]
Oh good now i Don't have to submit my own request for that over here

**Comment by gmcferrin** [comment]
If you wanna do the DS Store thing, make a new PR

**Comment by Crazy-Uncle-Harris** [comment]
Ok ill do that then.

**Comment by aidangoettsch** [comment]
@gmcferrin ?

**Comment by authorblues** [comment]
One PR per issue.

**Comment by gmcferrin** [comment]
@yayestechlab This is an incredible poor way of doing this. Don't hardcode the values, pull them from the NMS code instead.

**Comment by authorblues** [comment]
As @gmcferrin said, if the NMS object is an instance of ItemFood, the work has been done for you already. There is no need to hard code anything in: https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/net/minecraft/server/ItemFood.java#L69-L75

**Comment by aidangoettsch** [comment]
I will create a new PR. Closed.

**Comment by aidangoettsch** [comment]
@gmcferrin How, NMS is not available in Bukkit

**Comment by authorblues** [comment]
Define an API in Bukkit, Implement it in CraftBukkit. CraftBukkit has access to NMS.

**Comment by aidangoettsch** [comment]
@authorblues ?

**Comment by authorblues** [comment]
You have to make a parallel C+B pull request. On the Bukkit side, you would define an interface that will be exposed via the API. In CraftBukkit, you would give the implementation of that API. CraftBukkit has access to NMS. This is how almost all PRs are written that add API.

**Comment by aidangoettsch** [comment]
The problem I have is that Material is an enum, not an interface

**Comment by authorblues** [comment]
I'm getting dangerously close to having to write this PR for you. https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/Item.java. For objects instantiated with the ItemFood constructor, the 2nd parameter is the food level, and the 3rd parameter is the saturation. Hopefully you can take it from here.

**Pull request closed without merging**
