### PR TITLE
Add Villager Effects

### PR DESCRIPTION
**Pull request by jascotty2**
Not certain on the final name/description, but these should be added to the API

### CODE REVIEW

**Comment by riking** [comment]
Do these work? Have you tested them? Where's the leaky ticket? What's the problem this is solving?

**Comment by jascotty2** [comment]
i am not aware of any leaky ticket for this

just was experimenting with villager effects and discovered that these were not defined in the API

i have tested that these data values are correct, but after looking through the packets, i think "VILLAGER_HAPPY" and "VILLAGER_ANGRY" might be better enums than "VILLAGER_TRADE" and "VILLAGER_HIT"

**Comment by Black-Hole** [comment]
There are also other values for EntityEffect missing: http://wiki.vg/Protocol#Entity_Status_.280x26.29

**Comment by turt2live** [comment]
closing in favour of #907

**Pull request closed without merging**
