### PR TITLE
Basic command to get information about a command

### PR DESCRIPTION
**Pull request by xZise**
Hello,
I added a command (like /plugins or /version) to get information about a command. For example:

<pre>>cmd w
01:04:13 [INFO] Commandinfo for 'warp':
01:04:13 [INFO] Registered by xWarp v2.12.0 b9
01:04:13 [INFO] Warp commands
01:04:13 [INFO] Aliases: xwarp and w
01:04:13 [INFO] Usage: /warp help - Displays the help for xWarp
>cmd foo
01:04:19 [INFO] Commandinfo for 'foo':
01:04:19 [INFO] Alias for: reload and plugins
</pre>

So you quickly see, which command has registered `/w` and if there is another plugin registering it first, you could see it quickly and could create an alias (thanks for this btw!).

I also extracted a static method, to get a `String` of a `List<String>` which previously was used only by the `/version` command. Maybe this could be moved somewhere else, if also other plugins/classes want to use this method.

Fabian

### CODE REVIEW

**Comment by deadbirdi** [comment]
Maybe instead of adding new commands you could just improve the help command so it could also give information about specific commands.

**Comment by xZise** [comment]
Actually the help command is the minecraft server help command so it doesn't know about any other command, then these from minecraft.

Fabian

**Comment by deadbirdi** [comment]
Oh I see. Well would there be a way to implement the help command as a new command and maybe have it overwrite the default one.

**Comment by xZise** [comment]
Maybe, but while the help command describes how to use the command, this command here gives the info about the command. I mean, when you type “/help warp” then you normally not expecting:

```
Commandinfo for 'warp':
Registered by xWarp v2.12.0 b9
Warp commands
Aliases: xwarp and w
Usage: /warp help - Displays the help for xWarp
```

Instead the help should show only the usage message. But it is up to the Bukkit developers how they want to have it.

Fabian

**Comment by xZise** [comment]
I updated the pull request which is now showing a little note, if the command is a vanilla command and running with the new command structure.

Fabian

**Comment by xZise** [comment]
Okay I now make everything a little smoother:
1. It is now recognizing vanilla/fallback commands.
2. It shows now a nicer message if there are no aliases for a command.
3. Without any parameter it list all registered commands (sorted).
4. There is a little note when your parameter was an alias.
5. And when there is no command registered it won't crash anymore – OOPs.

There are a lot of utility stuff. At the moment I left them in the CommandCommand class because I don't know how you want to organize them (in another pull request I used a Util class for this).

Fabian

**Comment by xZise** [comment]
Okay, I opened a [leaky issue](https://bukkit.atlassian.net/browse/BUKKIT-823) and updated the source code to the current head.

Fabian

**Comment by md-5** [comment]
The new help api will replace this

**Comment by feildmaster** [comment]
So I take it this can be closed now?

**Pull request closed without merging**
