### PR TITLE
Adds a method to ban a player

### PR DESCRIPTION
**Pull request by CruzBishop**
I can't seem to get the diff to work nicely on this. Sorry!

This adds to the API to allow banning of a player (I will be using it in my plugin, DefaultCommands, unless someone else has a request approved, of course)

CraftBukkit: https://github.com/Bukkit/CraftBukkit/pull/380

### CODE REVIEW

**Comment by CruzBishop** [comment]
Updated

**Comment by Afforess** [comment]
I can't believe this wasn't part of Bukkit from day one. What say you, @EvilSeph?

**Comment by CruzBishop** [comment]
Thanks, Afforess. I spent about 2 hours going through every single class in Bukkit trying to find a banning method, and couldn't believe it when there were none

**Comment by CruzBishop** [comment]
Going to redo this later

**Pull request closed without merging**
