### PR TITLE
Implement ping method

### PR DESCRIPTION
**Pull request by maxammann**
This implements a ping method by accessing the field "ping" in the EntityPlayer object.

https://bukkit.atlassian.net/browse/BUKKIT-2437

Is it updated?

Yep it updates automatically.

What is ping?

The ping is the time, it takes to send a package to the server and receive it.

Is it accurate?

It is almost. This equals the ping value which you can see in your server list if you hover the connection symbol.

Here is a test:

From ingame:
19:32:33 [INFO] p000ison - 7
19:32:35 [INFO] p000ison - 48
19:32:37 [INFO] p000ison - 43
19:32:39 [INFO] p000ison - 47
19:32:41 [INFO] p000ison - 62
19:32:43 [INFO] p000ison - 59
19:32:46 [INFO] p000ison - 59
19:32:47 [INFO] p000ison - 53
19:32:49 [INFO] p000ison - 61
19:32:51 [INFO] p000ison - 53
19:32:53 [INFO] p000ison - 46
19:32:55 [INFO] p000ison - 50
19:32:57 [INFO] p000ison - 41
19:32:59 [INFO] p000ison - 44
19:33:01 [INFO] p000ison - 66
19:33:03 [INFO] p000ison - 54

Direct ping:

Antwort von ****_: Bytes=32 Zeit=23ms TTL=56
Antwort von ***__: Bytes=32 Zeit=11ms TTL=56
Antwort von *_**_: Bytes=32 Zeit=21ms TTL=56
Antwort von ***__: Bytes=32 Zeit=16ms TTL=56
Antwort von *_**_: Bytes=32 Zeit=14ms TTL=56
Antwort von ***__: Bytes=32 Zeit=13ms TTL=56
Antwort von *_**_: Bytes=32 Zeit=18ms TTL=56
Antwort von ***__: Bytes=32 Zeit=14ms TTL=56
Antwort von *_**_: Bytes=32 Zeit=15ms TTL=56
Antwort von ***__: Bytes=32 Zeit=14ms TTL=56
Antwort von *_**_: Bytes=32 Zeit=14ms TTL=56
Antwort von ***_*: Bytes=32 Zeit=17ms TTL=56

Why do you need it? 

I think it can help to check if the connection to the player is not good. This can help for example plugins which prevent cheating (like NoCheat)

It seems like the first ping is always a bit less, but the other values are ok.

### CODE REVIEW

**Comment by SagaciousZed** [comment]
I can tell you now that this needs an associated ticket in leaky listed.

**Comment by maxammann** [comment]
k done: https://bukkit.atlassian.net/browse/BUKKIT-2437

**Comment by Wolvereness** [comment]
What is ping?
Why do you need it?
Is it accurate?
Is it updated?

I don't see this getting pulled without a **good** answer to these questions. These should be documented in the javadoc and the PR/ticket.

**Comment by maxammann** [comment]
Here is a test plugin: http://dl.dropbox.com/u/20831395/TestPlugin.jar

It prints the ping for every player every 2 sec.

**Comment by maxammann** [comment]
A update for the javadocs will follow.

**Comment by Wolvereness** [comment]
Just as a note, none of the questions were answered...

Everyone should know that "ping" is time, but that doesn't explain what unit, and if it's 1 or 2 directional. Saying that it is updated doesn't explain how often, or if anything in particular triggers an update. Accuracy is the closeness to what is expected; does ping return their ping 30 seconds ago or half a second ago, is it equivalent to what we expect a normal "ping" operation to be, does it trigger the ping operation and wait for a client response, can the client fake the time? On that final note, why is it useful to an anti-cheat plugin if it can be faked easily?

**Comment by gravitylow** [comment]
Have you determined that it can be faked easily or are you just asking that question in the case that it can be? 

What I had detailed in my plan to implement something like this into AntiCheat was just to use it to generate a small window of leniency among players with higher pings. It wouldn't say "oh, this guy has a really high ping let's let him fly all over the map" but more just bump up the limits of how fast he can walk by enough that checks won't be failed by acting normally, even while he has a high ping. Abnormal behavior would still be treated as a hack.

**Comment by olliestanley** [comment]
@Wolvereness Actually he did say the unit, he said it is the same as what you can see in the server list.

**Comment by LB--** [comment]
Is there something wrong with holding the Tab key in game for a moment? This seems like it should be more of a clientside mod, since the client does grab accurate ping times.

Edit: Nevermind, derp moment.

**Comment by gravitylow** [comment]
Is there something ..... wrong with that? No... Not visually, but the point of Bukkit is to let developers access and use this stuff in their code, and you can't currently get a player's ping within a plugin, which is what this is for.

**Comment by mbax** [comment]
Can you add a link to the Bukkit PR here, a link to the JIRA ticket on the Bukkit PR and a link to both PRs on the JIRA ticket.

**Comment by amaranth** [comment]
Are you sure you really want this? I can fake pretty much any ping number I want (outside of timeout numbers) with a couple lines of code in my client. I certainly wouldn't use this data for anything like an anti-cheat system.

It is basically only useful for informational purposes but the most effective place to present this information is also the place CraftBukkit disables showing it due to the amount of packet spam.

**Comment by maxammann** [comment]
k I think we can close this, since it very easily fake-able.

**Pull request closed without merging**
