### PR TITLE
Add Block API for getting sky light and emitted light levels 

### PR DESCRIPTION
**Pull request by mikeprimm**
These allow access to the lower-level lighting data, which can be used for both light color sensitivity (redder emitted light vs bluer sky light), as well as other light-type-sensitive functions (sky light level approximates visibility of the location from above, predicting light levels after dark or during storms, etc).

(Accidentally closed first request - see https://github.com/Bukkit/Bukkit/pull/390 for previous discussion)

Corresponding pull in Craftbukkit - https://github.com/Bukkit/CraftBukkit/pull/515

### CODE REVIEW

**Comment by xpansive** [comment]
Is the sky light independent of the time of day? Is there a way to get the light level as if it was always day?

**Comment by mikeprimm** [comment]
Yep - that's what this value is.  Its the static map data (that is only recalculated when block changes call for it) that corresponds to the light level from the sky at full daylight - its scaled down based on the current actual sky lighting (so if it is 12 during the day, it would be 1 at night (when sky light is 4 - or 11 below daylight level of 15).  The current light level of a block is the maximum of the emitted light level and the the current sky level (e.g. max(getEmittedLightLevel(), current-sky-level - getSkyLightLevel()), where current-sky-level is 15 during a sunny day, 4 during night (and some other values when its storming - I don't recall).  Also, if  you want to mess with the red-from-emitted, blue-from-sky colored lighting (since 1.8), you need the two values - can't figure it out from getLightLevel().

**Comment by xpansive** [comment]
Great, thats just what I need :D. I gurss I'll just use the nms code until this gets pulled.

**Comment by mikeprimm** [comment]
Pull request migrated to Bukkit-Bleeding branch SkyAndEmittedLightAPI - https://github.com/Bukkit/Bukkit-Bleeding/tree/SkyAndEmittedLightAPI

**Pull request closed without merging**
