### PR TITLE
[B] Fixes the EXTREME_HILLS_EDGE biome not being included in org.bukkit.block.Biome. Fixes BUKKIT-5433

### PR DESCRIPTION
**Pull request by ryanlarkin**
The Issue:

This PR is meant to be addressing EXTREME_HILLS_EDGE biome not being included in org.bukkit.block.Biome.

Justification for this PR:

Without this change the biome EXTREME_HILLS_EDGE cannot be found in
the Biome class.  This is a problem because if a plugin developer wants to
get a list of all biomes that exist his list would be inaccurate.  This could make a command that is changing to or getting info of a EXTREME_HILLS_EDGE not preform the correct logic. 

PR Breakdown:

This PR adds EXTREME_HILLS_EDGE to org.bukkit.block.Biome.

Testing Results and Materials:

To test my fix I created a simple plugin that when enabled gets the enum constants of Biome and uses a simple foreach to print out all of the values.

JAR File: http://download1509.mediafire.com/kqdui4addcmg/m4ax8p17gu48s97/PluginTester.jar
Source Code: http://download1638.mediafire.com/4an5n665btjg/069949o8w8whh9g/Testing.zip

JIRA Ticket:

BUKKIT-5433 - https://bukkit.atlassian.net/browse/BUKKIT-5433

### CODE REVIEW

**Comment by Black-Hole** [comment]
It's already there: SMALL_MOUNTAINS

**Comment by ryanlarkin** [comment]
ICE_MOUNTAINS_SPIKES doesn't seem to be there though.

**Comment by Black-Hole** [comment]
It's there, too.
Please compare the number of biomes with http://minecraft.gamepedia.com/Data_values#Biome_IDs (exculding the -1). Or modify your plugin to show the biome at the current location, compare that to the debug (F3) screen.

**Comment by ryanlarkin** [comment]
I count am counting the biomes (excluding -1) on the Minecraft Wiki and in the Biomes class and there are 62 on the Minecraft Wiki table and 61 in the biome class so this is why I am confused.

**Comment by Black-Hole** [comment]
It looks like an error in the wiki. There is no extended biome for net.minecraft.server.BiomeBase.ICE_MOUNTAINS
There is also a check in CraftBukkit, so it won't compile if there is a biome mapping missing.

**Pull request closed without merging**
