### PR TITLE
Add Hopper interface, adds BUKKIT-3749

### PR DESCRIPTION
**Pull request by DeltaWhy**
Implementation for Hopper: https://github.com/Bukkit/CraftBukkit/pull/1056
Currently there is no TileEntityDropper in CraftBukkit or in mc-dev, otherwise I would implement that too.

### CODE REVIEW

**Comment by amaranth** [comment]
Dropper should probably just extend Dispenser and automatically get the dispense() method from it. We'll have to update the CraftBukkit side of CraftBlockDispenser to know about droppers though. Also your CraftBukkit PR seems to be missed the implementation of the Dropper API you've added. Oh, and you missed a space in InventoryType. :D

**Comment by DeltaWhy** [comment]
@amaranth I wasn't able to implement the Dropper API because the dropper is a different tile entity from the dispenser, and that file hasn't been added to CraftBukkit yet.

Should I change Dropper to extend Dispenser or should I just remove it until I (or someone else) can actually implement it?

**Comment by amaranth** [comment]
@DeltaWhy Get in touch with me on IRC if you need any files missing from CraftBukkit for a PR. For now you can probably just drop the Dropper interface, it'll need some thought as to how to set it up. It is essentially a dispenser that only uses one DispenseBehavior class and a hopper that can only put things in a container (when powered) and not take them out.

**Comment by DeltaWhy** [comment]
@amaranth Alright, I removed Dropper. I might take another shot at it but I'll make it a separate PR.

**Comment by amaranth** [comment]
Pulled.

**Pull request closed without merging**
