### PR TITLE
JAVADOC: Document rather strange behaviour in Inventory.addItem and use ...

### PR DESCRIPTION
**Pull request by cybertiger**
...Java terminology for Java

### CODE REVIEW

**Comment by Wolvereness** [comment]
Javadoc updates are handled at https://github.com/Bukkit/Bukkit-JavaDoc

**Comment by riking** [comment]
How do we mark that the behavior is not intentional and that you shouldn't rely on it?

**Comment by authorblues** [comment]
The point @riking mentions is the crux of my point: the behavior you are experiencing seems to be, to my understanding, undefined behavior based on ill-formed input to the function. What this means is that its behavior might be consistent (meaning that you can explain and deduce how it will behave), but there is no guarantee that it won't change.

Undefined behavior should never be mentioned in the API docs.

> implementation specific can only really be applied to when there is more than one implementation.

This is an incredibly poor way to look at the situation. The API is meant to be implementation-agnostic. I could, in theory, create my own version of CraftBukkit that makes use of the Bukkit API, which would allow Bukkit plugins to automatically behave properly with it. This actually already exists: Spigot, SportBukkit, (the now nonexistent) CraftBukkit++

**Comment by cybertiger** [comment]
Either the implementation is wrong and should be fixed or the documentation is incomplete and should be fixed, or both. I've stated I have no preference. You have failed to state any preference and dragged the discussion off topic.

> Undefined behavior should never be mentioned in the API docs.

More importantly behavior should not be left undefined in the API docs, for exactly the same reasons. Also a slightly pedantic point, if you define undefined behavior in the documentation, it would no longer be undefined.

I guess what you meant was the implementation is self inconsistent and wrong and should be fixed, and then the Javadocs should be updated to exactly define the behavior with regards to which version of getMaxStackSize() is used (or vice versa, but the order really does not matter).

**Comment by authorblues** [comment]
It isn't my intention to be off-topic. I was just wondering if this is truly undefined behavior or not. Describing what the implementation does under the case of ill-formed input (if that is what the case is) isn't really something that should be documented. I'm not really familiar with this use-case, but is it common for people to make use of ItemStacks that exceed the getMaxStackSize() value?

**Comment by riking** [comment]
@cybertiger The implementation is wrong and should be fixed.
@authorblues It actually IS common for people to do that... which causes resistance to fixing the implementation.

Perhaps another method is needed - e.g. addItemForce() or addIrregularItem(LItemStack;)V which never splits stacks and caps the size at 127 or 128 (127 is the largest number that will render in the client).

**Comment by cybertiger** [comment]
@riking 

Yeh, I'd go with 

public enum StackSize {
    INVENTORY,
    ITEM,
    BOTH
}

addItem(StackSize maxStackSize, ItemStack... stacks)

and @deprecate the existing addItem function and say it's deprecated because it's behavior is likely to change to the equivalent of addItem(StackSize.BOTH, args) in the near future, rather than the current screw up.

Or something like that, not gonna PR it until 1.5 is out if I do at all.

**Comment by riking** [comment]
I'd rather not require an enum in the arguments to that function... I was thinking of a function that stated that it would never split a stack.

**Comment by authorblues** [comment]
What is the need for creating stacks that exceed the maximum size? That just seems hairy.

**Comment by riking** [comment]
@authorblues I can point to the many custom maps that give you 64-stacks of splash potions to spam at the enemy (so you don't need some kind of auto-refill client mod to keep attacking) - Sethbling's Super Craft Bros. is the most recent example.

(Side note: he uses command blocks to do this, Creeper class.)

And if a custom mapmaker will want to do it, a plugin maker will want to do it.

**Comment by AmoebaMan** [comment]
Potions are a big culprit.  Max stack size is ordinarily one per, but many servers like to give players stacks of multiple splash potions.

**Pull request closed without merging**
