### PR TITLE
New FURNACE_SMELT and FURNACE_BURN event

### PR DESCRIPTION
**Pull request by yetanotherx**
Per bug #558 (http://bugs.bukkit.org/issues/558), I have implemented a new FURNACE_SMELT event that fires when an item is created in a furnace. It's my first attempt at editing Bukkit, so I hope I did everything right here. I'm making 2 pull requests, as I had to edit both Bukkit and Craftbukkit. Link to other request: https://github.com/Bukkit/CraftBukkit/pull/215

### CODE REVIEW

**Comment by cyklo** [comment]
Have you tested this? It appears to be incomplete. Without patching JavaPluginLoader.java and without an onFurnaceSmelt(FurnaceSmeltEvent event) in BlockListener.java, I don't believe plugins can hook into this.

**Comment by yetanotherx** [comment]
Yes, I forgot to add them in the previous commit. Everything should be there now. I've tested this and it is indeed working.

**Comment by maxx001** [comment]
This is exactly what i need for my server. I see it implements the Cancelable and thus it should be possible to prevent certain items to appear after the smelting process is completed right?

**Comment by yetanotherx** [comment]
Yes, it does cancel the smelting. One issue that I'll fix is that cancelling the event resets the state to the way that it was before. If an event is cancelled:

Intended behavior: 1 iron ore/0 iron ingots becomes 0 iron ores/0 iron ingots
Actual behavior: 1 iron ore/0 iron ingots becomes 1 iron ores/0 iron ingots

I'll fix this when I return tonight.

**Comment by yetanotherx** [comment]
This has been fixed in CraftBukkit.

**Comment by yetanotherx** [comment]
I've added a fURNACE_BURN event for when fuel is consumed

**Pull request closed without merging**
