### PR TITLE
Added Villager Profession API

### PR DESCRIPTION
**Pull request by aPunch**
This pull request adds an enum for Villager Professions. You can get a villager's profession by using Villager.getProfession(). There are also ways to get a Profession by name and by ID using static methods in the Villager.Profession enum.

Associated CraftBukkit Pull Request: https://github.com/Bukkit/CraftBukkit/pull/668

### CODE REVIEW

**Comment by jrtc27** [comment]
Why are you bothering to use `Validate`? It just requires a simple `if (name != null)` around all of the code (including `return`), and then return `null` outside the `if` statement to return `null` if `null` is passed in.

**Comment by aPunch** [comment]
It's what the Art enum uses, so I figured I should use that to remain consistent. I can change it if asked by the team.

**Comment by jrtc27** [comment]
Fair enough, just struck me as unusual :)
***goes to create pull request for Art enum to not use Validate***

**Comment by feildmaster** [comment]
@jrtc27 The team prefers validate.

**Comment by jrtc27** [comment]
Ok :)

**Comment by aPunch** [comment]
Closing and moving to bleeding.

**Pull request closed without merging**
