### PR TITLE
Implement PlayerItemConsumeEvent

### PR DESCRIPTION
**Pull request by ammaraskar**
JIRA ticket: https://bukkit.atlassian.net/browse/BUKKIT-2349

### CODE REVIEW

**Comment by riking** [comment]
Can we get a dev to look this over?

**Comment by AmoebaMan** [comment]
It's been 5 months since the pull request was opened, not a single dev has bothered to reply here, and Bukkit STILL has no way of us handling this.  Why the hell has this been ignored so much?

**Comment by EdGruberman** [comment]
The Javadocs need to clarify exactly what this event does.  When is it fired? After item consumption has fully completed?  What happens when you cancel it?

Does this fire after item is gone (server side, client side, both?) but before effect is applied? Does cancel only cancels effects?

This should all be clarified.

**Comment by EdGruberman** [comment]
Also, can you add a setConsumed(ItemStack) method and setApplyEffects(boolean) to allow plugins to adjust the result of the event?

Lastly (I think) can you update the commit name to include "Adds BUKKIT-280" and PR comment to point to https://bukkit.atlassian.net/browse/BUKKIT-280 ?

**Comment by amaranth** [comment]
Thanks but I've implemented this in a different way.

**Pull request closed without merging**
