### PR TITLE
Item Durability fixes

### PR DESCRIPTION
**Pull request by jascotty2**
Iron Sword durability fixed (was set == wood sword),
 and fishing rod can actually be used 33, not 65

### CODE REVIEW

**Comment by xZise** [comment]
Nice fixes, but the second commit should be in a separated request.

Fabian

**Comment by jascotty2** [comment]
.. i didn't realize the second commit would be compounded onto this pull request..

**Comment by xZise** [comment]
Somewhere here github notifies you, that any commit on the master branch will be added to this here. Because of this it would be the easiest to create a new branch (`git branch <branchname>`) and commit any changes onto this branch (change to the branch via `git checkout <branchname>` – you could see the selected branch via `git branch`).

Fabian

**Comment by EvilSeph** [comment]
Applied manually, thanks!

**Pull request closed without merging**
