### PR TITLE
Add Fish Hook to PlayerFishEvent [#Bukkit-1025]

### PR DESCRIPTION
**Pull request by andrepl**
This patch adds a reference to the Fish entity (ie. bobber/hook) to the PlayerFishEvent.  This allows plugins to determine its location after casting as well as simulate bites.

CraftBukkit PR: 
https://github.com/Bukkit/CraftBukkit/pull/1045

Ticket:
https://bukkit.atlassian.net/browse/BUKKIT-1025

### CODE REVIEW

**Comment by jrtc27** [comment]
Whitespace issues. Make sure you're indenting with 4 spaces, and no trailing whitespace.

**Comment by andrepl** [comment]
Ok thanks, I'm cleaning it up now and trying to figure out how to squash them into one commit.

**Comment by tonybruess** [comment]
Commit message needs proper capitalization and something like "Fixes BUKKIT-1025".

Thanks!

**Comment by andrepl** [comment]
How's that?

**Comment by riking** [comment]
Perfect, methinks :)

**Comment by Wolvereness** [comment]
This is breaking and should be corrected, with fallback behavior clearly defined.

**Comment by riking** [comment]
Oh.. yeah, missed the constructor removal part.

**Comment by andrepl** [comment]
Added back the original constructor and made the other suggested changes.

**Comment by authorblues** [comment]
Squash the commits (revert your old changes, don't add them back with an additional commit). One of the core principles for Bukkit PRs (for any PR really) is minimal diffs. Also, you have yet to add the [@Deprecated annotation](http://docs.oracle.com/javase/1.5.0/docs/guide/javadoc/deprecation/deprecation.html#annotation), as suggested.

**Comment by riking** [comment]
FIX DEM TRAILING SPACES https://github.com/andrepl/Bukkit/pull/1

also squash as @authorblues said

**Comment by andrepl** [comment]
Okay updated again, squashed and whitespace removed.

**Comment by authorblues** [comment]
This looks good now. Non-breaking, clean, properly deprecated, and minimal diff. I'm signing off on this.

Let me just add that, as said previously, `Fish` is possibly the worst name for that class ever. Entirely misleading.

**Comment by andrepl** [comment]
Totally agreed.

**Comment by riking** [comment]
Hm, is there some kind of queue for breaking changes?

**Comment by authorblues** [comment]
@riking What do you mean by queue?

**Comment by riking** [comment]
@authorblues Some kind of list of changes that will occur at the next breaking API change

**Comment by authorblues** [comment]
They are so few and far between that I doubt it highly. In fact, though I haven't been keeping a close eye on the commit history, I don't believe there have been any breaking changes recently. Breaking changes usually only happen for fixing blatant errors (a method performed its function incorrectly, correcting that function is technically a breaking change for anyone relying on incorrect behavior), but most code removal goes through an extremely long term [deprecation cycle](http://jd.bukkit.org/rb/doxygen/da/d58/deprecated.html).

**Comment by riking** [comment]
@authorblues I don't think there's any easy way to deprecate a whole class while forwarding to the new one.

Also, if a "breaking cycle" gets declared, we could finally fix that TNT event :3

**Comment by authorblues** [comment]
If you're talking about deprecating an event in favor of a new one, you'd have to continue firing the deprecated event for quite some time. Deprecating classes/interfaces in general, on the other hand, happens literally all the time. You can usually just inject the deprecated class in between the new class and its old inheritors.

As for that TNT event, I don't expect we will be seeing progress on that in either of our lifetimes, but we can dream :smile:

**Comment by riking** [comment]
Anyway, back to the subject of this change. It looks ready for an official comment to me.

**Comment by riking** [comment]
Please include a javadoc explaining why it was deprecated to the old constructor (using the @deprecated tag inside the javadoc).

**Comment by andrepl** [comment]
Updated

**Comment by authorblues** [comment]
Use the @deprecated tag. Look at my javadoc [here](https://github.com/Bukkit/Bukkit/commit/be85e489796e66263dd9899e80b3174ff5b3bbd3#L1R538) for an example.

**Comment by riking** [comment]
Pulled

**Pull request closed without merging**
