### PR TITLE
Add equipment API for EntityLiving.

### PR DESCRIPTION
**Pull request by oloflarsson**
The corresponding CraftBukkit PR: https://github.com/Bukkit/CraftBukkit/pull/938

### CODE REVIEW

**Comment by feildmaster** [comment]
Make it a new "EntityEquipment" class, and I'll consider reviewing a revised PR.

**Comment by oloflarsson** [comment]
I actually think this approach of mine makes sense. Note how HumanEntity currently has these two methods:

public ItemStack getItemInHand();
public void setItemInHand(ItemStack item);

Those two were moved one step lower (from HumanEntity to EntityLiving) and additional methods were added. Would you suggest deprecating and moving those two to such an "EntityEquipment" class as well? And how would that class be retrieved?

I frankly cannot see what's could have been done better. I spent a whole day on this. Then the RP is closed using worlds like "consider" and "review". It sure is not easy trying to contribute.

I could use NMS directly but OH: Someone made a strange choice which may render that approach almost impossible: https://github.com/Bukkit/CraftBukkit/commit/8f12382e8efc8c39a919af9180dd884caf3720ff

This PR of mine is a prime example of why NMS access is a necessary evil. It takes too long time for features to be added to the Bukkit API.

**Comment by BangL** [comment]
@oloflarsson i am starting to love you.

**Comment by me4502** [comment]
You could have a getEquipment() and setEquipment(EntityEquipment) as that's how a lot of the API works, maybe that's what @feildmaster meant.

**Comment by LB--** [comment]
All mobs, not just human mobs, can have equipment. Not all mobs can display it of course, but vanilla behavior currently is that the armor does act as armor and the item in the hand does act as a weapon, even for e.g. spiders.

With players, however, the armor and hand items are overridden by the player's actual inventory. At least, in all my tests, the items in the hand and armor tags had no effect at all versus the items in the inventory armor slots and currently selected hotbar item.

Just a reminder of things to consider.

**Comment by feildmaster** [comment]
I don't want a million functions added to a single already huge class. (Apparently I wasn't getting notifications for this class, which is the reason I haven't replied yet)

I believe I was clear with the reason I closed the PR. I want it to act like https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/org/bukkit/craftbukkit/inventory/CraftInventoryPlayer.java

**Pull request closed without merging**
