### PR TITLE
Basic Plugin Dependencies

### PR DESCRIPTION
**Pull request by Raphfrk**
This adds a new field to the yml file called "depend".

```
 depend:
   EventLink.jar
```

If this field is included, then those jar files will be added to the class loader for this plugin.

This allows a plugin to extend classes from other plugins.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
I'd rather this worked from plugin name. A jar can be named anything.

**Comment by Raphfrk** [comment]
Well, maybe that isn't a bad thing.  That would allow linking to something like

../helperFiles/someLibrary.jar

Ofc, that is maybe a potential security issue :).

In order to make it work with plugin names, it would need to scan all the other .jar files first to get the plugin -> filename mapping.  Alternatively, it could just append .jar to the given name.

**Comment by erisdev** [comment]
Well, Bukkit is going to load all the plugins in the plugins directory anyway, so you're going to have all the names of the plugins available in the end. Just defer actually loading the classes until dependencies have been settled, otherwise raise an error if one is missing.

Dinnerbone's point is that a jar file can be named anything and it doesn't have to match the name of the plugin at all; I could name the jar for my `MagicalMysteryPlugin` as `MagicalMystery-v1.3.jar`, `superduperfancy.jar` or even `poop.jar` and Bukkit doesn't care. Your dependencies implementation runs counter to that.

As for library dependencies, just make sure the library is on your classpath and Bukkit won't have to worry about it being a dependency or whatever—either the plugin will work or, if you don't have the library installed, it won't. That's how most software works.

**Comment by Raphfrk** [comment]
I have updated it so that the loader takes a Map as an input.  This is a pluginName -> File map that has the locations for previously loaded plugins.

If the dependencies are not in the map, then it will throw an UnknownDependencyException.

If it does successfully load the plugin, it will add the plugin to the map.  

The load directory method is also updated.  It will now keep retrying to load any plugins that fail unless it tries all remaining plugins and they all fail.

This means that if a plugin that requires a later plugin throws an UnknownDependencyException, it will be retried at the end.

**Comment by Raphfrk** [comment]
Hmm, I may have a look at this again Tonight.

It might be better to store all previously loaded plugins in JavaPluginLoader.

This has the potential to also fix the issues with 3rd party .jar files and handling different versions (the search order would need to be changed).

Would there be any issue with changing the order to
- search local cache
- search local .jar file
- search global cache 

I assume the 3rd one also contains the actual (Craft)Bukkit classes themselves.

Currently, it searches globally before checking if the class exists in the local .jar file.

There is still the issue of what to do if an attempt is made to load a plugin before one of its dependencies, I think I will keep the UnknownDependencyException for that.

**Comment by Raphfrk** [comment]
Updated this again.  It is now simpler.  The file cache is now stored directly in the JavaPluginLoader class.

I am going to look into changing the search ordering, but not sure if it should be a different pull request.

**Comment by Raphfrk** [comment]
Updated again, it now has the modified search order.  The local class loader is checked before the global one.

**Comment by Raphfrk** [comment]
This has been tested and it allows different versions of 3rd party libraries to operate correctly.

See [this](http://forums.bukkit.org/threads/making-plugins-which-use-the-same-3rd-party-packages-play-nice.6589/#post-100217) forum post.

**Comment by Dinnerbone** [comment]
Tweaked a little, but thanks.

**Pull request closed without merging**
