### PR TITLE
Add ChunkFilter per chunk

### PR DESCRIPTION
**Pull request by codename-B**
Added ChunkFilter interface and added getChunkFilter() method to org.bukkit.Chunk

### CODE REVIEW

**Comment by codename-B** [comment]
Corresponding CraftBukkit pull
https://github.com/Bukkit/CraftBukkit/pull/527

**Comment by Dinnerbone** [comment]
Please work on the javadoc.

**Comment by codename-B** [comment]
Any improvement?

**Comment by Rigby90** [comment]
Out of curiosity... what would you use this for?

You state in your JavaDocs that this is "Fantastic for anti-xray or unique effects."

However I can't see it being used to hide ore from players because it's a flat out "Diamond Ore = Stone" no matter whether it meets a specific condition or not. So even if the player is meant to see it they wont be able to so it's blind luck as to whether they come across any ores.

Also seeing as you're only editing the initial chunk packet any lighting updates or neighbour blocks updating will update the client with the correct block id AFAIK.

**Comment by codename-B** [comment]
Yeah, it's designed as a very very simple lightweight filter on the chunk packet.

This was pulled together to be used in place of "packet listeners" for the anti-xray plugin I have written.

It's also designed to be extremely fast "Diamond Ore = Stone" to keep in line with the pull requests shouldn't detriment performance in any way requirement.

Obviously more advanced things can be done with Spout, but this is great for people who need simply to remove ores from that initial chunk send packet (or perhaps give their world a different effect during an event like glass trees etc).

**Pull request closed without merging**
