### PR TITLE
Define SpawnerSpawnEvent; Adds BUKKIT-267

### PR DESCRIPTION
**Pull request by EdGruberman**
https://bukkit.atlassian.net/browse/BUKKIT-267
https://github.com/Bukkit/CraftBukkit/pull/1046

### CODE REVIEW

**Comment by kitskub** [comment]
Shouldn't this extend CreatureSpawnEvent so any methods listening to that can still catch the spawn?

**Comment by EdGruberman** [comment]
CreatureSpawnEvent expects a LivingEntity.  "Mob" spawners can spawn any Entity.

However, along that line of thinking, we need to look closer at https://bukkit.atlassian.net/browse/BUKKIT-1559 and determine if this should be extending some more generic EntitySpawnEvent somehow.

**Comment by cybertiger** [comment]
Wouldn't a better way be add EntitySpawnEvent as a super class of CreatureSpawn event (and possibly another subclass called ItemSpawnEvent)?

It'd be a lot more work, and a lot of the cases which create non living entities have associated spawn events (though a hell of a lot don't).

**Comment by kitskub** [comment]
I agree with cybertiger.

**Comment by EdGruberman** [comment]
I agree, also; Both with the idea and how it'd be a lot more work. :)  And that is why I haven't gotten back to this yet.

**Comment by ST-DDT** [comment]
Its a great PR, but I would improve the description.

**Comment by ams2990** [comment]
The way this is structured now, you should probably also remove SpawnReason.SPAWNER from the enum.

**Comment by ST-DDT** [comment]
@ams2990 No because the other event is still called. See CraftBukkit PR.

**Comment by ams2990** [comment]
@ST-DDT Right you are. I saw that the line firing the event was being "removed", but missed that it was present later in the diff.

**Comment by EdGruberman** [comment]
Closing in favor of #859

**Pull request closed without merging**
