### PR TITLE
[B+C] Expose locale to plugin developers. Adds BUKKIT-4507

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by turt2live** [comment]
What would be included in a "Language API"?

**Comment by spaceemotion** [comment]
Maybe getting the Locale, adding translations for keys, ... ?
Imo this is not really needed, just getting the language field is enough.

**Comment by turt2live** [comment]
Yea, a full translation API is not needed in Bukkit (it would be on a per-plugin basis).

It would be extra bulk :/

I do like this "getLocale()" method though... Plugins like Essentials (plugins with multiple translations) could use this. (cough cough, @Iaccidentally)

**Comment by turt2live** [comment]
That (in my opinion) would be better a plugin like Vault rather than packed into the API.

**Comment by riking** [comment]
Would it be possible to use the [java Locale class](http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html) for this? It makes sense to provide that in the API instead of a string. Sure, this string might conform to the ISO standard, but we don't have control over vanilla changing that.

**Comment by riking** [comment]
Actually, what does this return for the "Pirate" language?

**Comment by riking** [comment]
Okay, that would work for passing into the Locale constructor then, I think.

**Comment by me4502** [comment]
I strongly agree with this PR. It would remove CraftBooks last usage of NMS.

**Comment by TfT-02** [comment]
This is a great addition to the API.

**Comment by me4502** [comment]
He any progress on this been made?

**Comment by TheE** [comment]
Any news?

**Comment by rmsy** [comment]
Is this going to be looked at? :eyes:

**Comment by jessestricker** [comment]
@riking @turt2live I like this. Any news about a merge?

**Comment by turt2live** [comment]
This is currently pending internal review. No ETA.

**Comment by rmsy** [comment]
3 months of internal review for an access scope change? Really?

**Comment by turt2live** [comment]
It does appear to be broken because of 1.7, so now it needs that update.

**Pull request closed without merging**
