### PR TITLE
Added TreeGrowEvent

### PR DESCRIPTION
**Pull request by iffa**
Possible uses: cancel natural tree growth for example in nether, make saplings useless (would be fun!)

I also made a quick test plugin: http://pastebin.com/K2KvKQvX

Associated CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/519

### CODE REVIEW

**Comment by DiddiZ** [comment]
Yay, I really want to see this implemented, adds new logging abilities to LogBlock.

Would there be a way to provide the actual created log/leaves blocks in the event, like in explosion event?

**Comment by iffa** [comment]
The blocks that will be grown? Either I keep this event cancellable and make a new event just for that (which is waste of space), or I call it in the tree gen classes with the blocks.

**Comment by DiddiZ** [comment]
What about making a list of all block changes in tree gen, call the event, and apply the changes after the event wasn't cancelled? Just like explosions

Would allow to cancel and to log tree grow.

**Comment by iffa** [comment]
You can make a pull request for that later on (if this is accepted), I only wanted basic functionality :)

**Comment by md-5** [comment]
DiddiZ got to it before me.
But event.getBlocks() is really a must.
But otherwise we really need this for Guradian.

Also I dont want to pull a pull request, so once this is accepted or you hand it to me :), I will add methods for getBlocks(), bonemeal and the player that used the bonemeal.

**Comment by iffa** [comment]
I could add getBlocks() but I want DiddiZ to re-explain.

**Comment by md-5** [comment]
Ok I'll explain this for Diddiz.
Tree makes the decision to grow.
You code gets the blocks affected and then calls the event.
Plugin X receives the event, does getBlocks and then sees the tree WILL grow in a bad area.
It then cancels the event, without the tree ever growing

**Comment by DiddiZ** [comment]
That's totally what I meant :)

**Comment by iffa** [comment]
oaky

**Comment by iffa** [comment]
so imma have to go dive in the tree gens next - blah i cba

**Comment by md-5** [comment]
Don't make me do it :)

**Comment by Top-Cat** [comment]
**Top_Cat** makes @md-5 do "it"

**Comment by md-5** [comment]
0.o All you need to do is make the event called under Bukkits internal treegen and then perhaps modify that method to include niceties such as boolean bonemeal; and Player player;

**Comment by iffa** [comment]
Bonemeal? where the heck would i find out if it was bonemealed

**Comment by iffa** [comment]
but i'll work on dias tomorw

**Comment by iffa** [comment]
goddamn, if i call the  event in the treegens (to have list-blocks), the tree would already be grown no matter if it was cancelled or not?

**Comment by iffa** [comment]
c

**Comment by md-5** [comment]
Hmm maybe I should take a look at this but
You can call your event from many locations
Put it in the blocksapling code for when it is natural
Then call it from the bonemeal interaction
In both these instances hijack the tree that would be generted
Store the blocks then once the event is finished write the blocks

**Comment by iffa** [comment]
"write the blocks"?

**Comment by DiddiZ** [comment]
Actually apply the block changes

**Comment by iffa** [comment]
i just dont understand how this could work if the tree is random and i have to store blocks in the gen, i would also have to store the materialit's supposed to be?

**Comment by iffa** [comment]
(To apply block changes)

**Comment by DiddiZ** [comment]
Yeah, BlockStates with location and type

**Comment by iffa** [comment]
feel like giving an example of this crap, im retarded and do not understand

**Comment by DiddiZ** [comment]
List<BlockState> treeBlocks = new ArrayList<BlockState>();
BlockState state = block.getState();
state.setType(123);
treeBlocks.add(state)

callEvent

if(not cancelled)
    for(BlockState state : treeblocks)
        state.update();

**Comment by iffa** [comment]
oh i sea! lol, i'll see what i can do

**Comment by DiddiZ** [comment]
ty :)

**Comment by iffa** [comment]
Goddamn BlockChangeDelegate

**Comment by md-5** [comment]
Thanks for putting that into code Diddiz
I was not going to try and do that on my phone
If you need anymore help @iffa just ask

**Comment by iffa** [comment]
Almost done with what i think will work, once this is done lets just hope the thing compiles and runs properly

**Comment by iffa** [comment]
Builds!

**Comment by iffa** [comment]
BlockChangeDelegate -> CraftWorld is my problem.

**Comment by md-5** [comment]
Not sure what you mean by that.
We are all counting on you :) No pressure

**Comment by oliverwoodings** [comment]
You best make this work iffa!

**Comment by iffa** [comment]
Alright, it should work but notchlogic broke :( https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/net/minecraft/server/WorldGenTrees.java#L35

it's returning false for no obvious reason

**Comment by iffa** [comment]
https://github.com/iffa/CraftBukkit/commit/364af314f1e75ed0e007da8ebc88d3870bfe7fb3#diff-6

**Comment by iffa** [comment]
I'm done with this goddamn notchcode bullshit

bye

**Comment by md-5** [comment]
So you're abandoning ship?

**Comment by Top-Cat** [comment]
*you're

**Comment by md-5** [comment]
@top-cat could not resist my first spelling mistake EVAR

**Comment by aPunch** [comment]
I'll see if I can take this over and change it to PlantGrowthEvent, handling all types of plant structure growth.

**Comment by md-5** [comment]
I've already got a pull but he done screwed it. I know all the methods and other gorwth is super easy once the gen stops breaking

**Comment by md-5** [comment]
EDIT: FINISHED - Sortof

https://github.com/md-5/CraftBukkit
https://github.com/md-5/Bukkit

Still need to do big trees and maybe mushrooms.

**Comment by md-5** [comment]
Here it is:
https://github.com/Bukkit/CraftBukkit/pull/523
https://github.com/Bukkit/Bukkit/pull/399

**Pull request closed without merging**
