### PR TITLE
Add API for tab completion

### PR DESCRIPTION
**Pull request by ScoreUnder**
CraftBukkit: https://github.com/Bukkit/CraftBukkit/pull/865

### CODE REVIEW

**Comment by ScoreUnder** [comment]
Just realized I left the event undocumented, hang on. -- EDIT done

**Comment by ScoreUnder** [comment]
Should I remove the event entirely?
Also, should TabCommandExecutor also include the label as args[0]?

Edit- acted on both anyway

**Comment by ScoreUnder** [comment]
Also, a nice testing script written in Groovy :P

```
import org.bukkit.*
import org.bukkit.command.*

@groovy.transform.CompileStatic
class X implements TabCommandExecutor {
    List<String> list = new ArrayList<String>()

    boolean onCommand(CommandSender sender, Command cmd, String alias, String[] args) {
        if (args.length > 0)
            list.add(args[0])
        return true
    }

    List<String> onTabComplete(CommandSender sender, Command cmd, String[] args) {
        List<String> test = new ArrayList<String>()
        String last = args[args.length - 1].toLowerCase()
        for (String x : list)
            if (x.toLowerCase().startsWith(last))
                test.add(x)
        Collections.sort(test)
        return test
    }
}

def cmd = new PluginCommand("tabcomplete", plugin)
cmd.executor = new X()
server.commandMap.register("test", cmd)
```

**Comment by ScoreUnder** [comment]
Oh yeah, I was wondering how suspect the use of Collections.emptyList() is in the CraftBukkit PR - there is a "static final List<String> EMPTY_LIST = new ArrayList(0);" in org.bukkit.command.defaults.VanillaCommand, I'm wondering if that was just an oversight or if there's a legitimate reason to not use Collections.emptyList().

**Comment by feildmaster** [comment]
@ScoreUnder There's was no real reason to use the empty list. (I forgot it was there)

**Comment by Wolvereness** [comment]
Leaving this open as a placeholder for the chat complete API (which needs a ticket btw).

**Pull request closed without merging**
