### PR TITLE
Material fixes

### PR DESCRIPTION
**Pull request by CelticMinstrel**
This fixes missing and incorrect durability and stack size values in the Material enum, as well as noting that maps have material data (from sunkid).

I got the tool damages from the wiki, but verified just to be sure they were correct.

### CODE REVIEW

**Comment by sunkid** [comment]
Just had a chance to look at this. I will close my pull request, but you may need to combine both commits into one. I don't care if you do my change manually.

Thanks for doing these!

**Comment by Dinnerbone** [comment]
Get's my vote. Sidenote: we really need to expand on Material stuff and make it a little more... useful.

**Comment by Afforess** [comment]
Dinnerbone - I was planning on starting a thread in Bukkit dev forum about that. I don't think the current system with enums is a good idea, since it does not support non-standard items at all, nor the ability to control adjustable aspects of items.

**Comment by Dinnerbone** [comment]
It allows for changing of aspects as much as a class does. But yes, an overhaul is coming soon already and is planned out, which isn't an enum system.

**Comment by Afforess** [comment]
Any chance I can read a summary of your plans? I'm curious.

**Comment by sunkid** [comment]
@Afforess: @Grum has already put a lot of effort into a replacement for Material and MaterialData, alas, it is not as straight-forward as one would hope. Of course, it doesn't help when people like myself clamor for backwards compatibility. ;)

**Comment by Afforess** [comment]
@sunkid, is there a branch or repo where I can see said changes?

**Comment by sunkid** [comment]
@Afforess: not that I know of

**Comment by Afforess** [comment]
Then can you provide a brief summary of what the changes include? @Dinnerbone? Anyone?

**Comment by sunkid** [comment]
As I indicated, @grum is working on this. You should ask him!

**Comment by CelticMinstrel** [comment]
Things I think a materials rewrite should consider...
- Separating item data from block data. Items use data a lot less than blocks, and most of the block data is irrelevant in the context of items; on the other hand, all item data for block items is relevant in the context of blocks.
- Instead of hardcoding things like max stack size and durability into the API, it should fetch them from the server. This is another argument against using an enumerator, unless you have a separate class for the fetching, but it would eliminate errors of the sort that this pull request was made to fix.
- It would be nice to expose an interface to some of the other methods in the Item class, such as the one to change the container item (which I used to make soup give back the bowl in crafting) and the ones to change stack size or durability, as well as interfaces to similar sorts of methods in the Block class (might it be possible to change a block's durability that way? I haven't checked, so I'm not sure, but it would be nice if it were).
- Although I made an argument against using an enumerator, I do like the way the enumerator makes it simple to hardcode a specific material rather than needing to do Material.getMaterial("SAND"). I'm not sure if a compromise is possible; maybe a simulated enumerator, which is to say an abstract class (maybe interface) containing all the public static instances of itself, but without making the class final as a real enumerator is.

I feel like I've missed something, but whatever. I suppose I'll talk to Grum about it if I get a chance, too.

**Comment by Afforess** [comment]
Excellent points. I had the same idea about using final static variables in an interface for accessing the default MC items.

(Celtic - Block Durability and the time to break it is all client side, IIRC.)

However, I think this would be an excellent time to get rid of MaterialData, for good. Items should implement a base abstract Item class (or interface...but I'm actually thinking an abstract class works best here) and there should be a variety of interfaces applied to items. A track interface for rails, powered rails, detector rails that lets developers see the direction of the track, etc. Food interface to get amount healed, etc. With that sort of a system, MaterialData would no longer be needed, and incorporating custom items into your code would be easy. Instead of checking whether an item is bread, or an apple, or porkchop, or... instead, check item instanceof Food.

One last point - items with unique data values (coal, charcoal) should be considered separate items, since thats how the game treats them. Users don't need to know that wool is all the same id, why should developers? I should be able to have a red wool item.

**Comment by CelticMinstrel** [comment]
Block durability may be done client-side, but that doesn't make it impossible for the server to override it... granted, though, it might be difficult to make blocks _harder_ to break if the client thinks the block is broken and tells the server that the player has stopped mining.

That aside, the interfaces method makes a lot of sense.

**Comment by Afforess** [comment]
I'm glad you agree with the interfaces idea. I'm coming from the perspective of wanting to eventually have custom items, so just implementing existing, widely used interfaces would mean that most plugins would support custom items like they were native items. It would be quite a bit of work, and I can see it spawning over 50 interfaces, but I think it's ultimately the for the best if we drop our obsession with data values.

I say that because I expect to register custom items with random, unassigned item values, not specific hardcoded ones, so I need this kind of system. I was planning on writing it myself, but native support is ideal.

**Comment by CelticMinstrel** [comment]
Oh, I'll also note that while getting away from data is not a bad idea, I think I would still prefer to do it as variants of a base item, keeping each materials class representing a single item id. Having separate Material entries for coal and charcoal sounds like a good idea at first glance, but I think I can imagine situations where it would be harmful; mainly situations where you say "any variant of this item" such as when adding a crafting recipe.

**Comment by Afforess** [comment]
I'm not sure I understand your concerns...

If coal and charcoal are kept separate, how would they be considered varients of the same item? As separate, unique items, it would eliminate the issue where they get mixed up - not excerbate it.

**Comment by xZise** [comment]
Yep would be nice, if it is possible to extend the available materials via an API. Maybe the default materials are still stored in an enumeration, but there is still an map (like now) where it is possible to add custom materials.

Fabian

**Comment by EvilSeph** [comment]
Pulled, thanks!

**Pull request closed without merging**
