### PR TITLE
Added getAge and setAge.

### PR DESCRIPTION
**Pull request by RobinvanderVliet**
This pull adds getAge and setAge for dropped items.

Corresponding CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/383.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
I think something like this would be more useful as an Entity thing.

**Comment by CelticMinstrel** [comment]
Indeed, other entities do have an age; as I recall, it's one of the factors in deciding to respawn a mob.

**Comment by RobinvanderVliet** [comment]
New pull for all entities here: https://github.com/Bukkit/Bukkit/pull/298.

**Comment by jwhb** [comment]
In which unit is this given?

**Comment by Fishrock123** [comment]
Ticks, I think?

**Comment by jwhb** [comment]
I don't think so... I have a tamed Ocelot, and it has zero age for about 30 minutes now

**Comment by jwhb** [comment]
Now i got it: The returned age contains the (negative) remaining ticks until the baby animal becomes adult.
As a baby animal actually needs 20 minutes to become adult, you can say that:
- A newly spawned baby animal has an age of -24000 (that's -20 minutes)
- An adult animal always has an age of 0

So @Fishrock123 was right

**Pull request closed without merging**
