### PR TITLE
BlockUpdateCallEvent- sometimes you need to stop a block from updating

### PR DESCRIPTION
**Pull request by HaxtorMoogle**
Lets you Check for block updates by the world. For example Ice and
snow have a update tick method. This allows for a plug in to prevent
ice and snow from melting.

Ground work to add mods such as blizzards

Change-Id: Icb5927cc1e4fa70a50f1a77a5dbc64d6d8f72157

### CODE REVIEW

**Comment by Raphfrk** [comment]
Is this a request, rather than a pull request?

You would normally also submit the code that adds the feature to CraftBukkit

**Comment by HaxtorMoogle** [comment]
I'm still new at submitting updates Raphfrk  I haven't cleaned up the CraftBukkit part to my liking probably upload something new today

**Comment by Raphfrk** [comment]
Np, was just pointing it out.

There's not much point in adding stuff to the API, unless the server supports it.

Also, btw you have " \* Called when tells a block to update", presumably it should be called when 'the world' tells a block to update, or something like that.

Btw, a very nice command is

git rebase -i HEAD~2

This allows you to combine the last 2 commits into 1.

**Comment by HaxtorMoogle** [comment]
Code is out of date now fixed up and renamed to BlockUpdateTickEvent

**Comment by EvilSeph** [comment]
Not sure if we want this but, regardless, this pull request is messed up. 250+ commits? Deleting README.md? pom.xml? .gitignore?

**Pull request closed without merging**
