### PR TITLE
[B] Added .floor() method to Location - Adds BUKKIT-4827

### PR DESCRIPTION
**Pull request by BillyGalbreath**
The Issue:

No current method to convert Entity Location to a Block Location without having to either create a new Location or modify the Location with multiple conversion methods.

Justification for this PR:

This is a convenience method, similar to Location.getBlockX(), Location.getBlockY(), Location.getBlockZ() are convenience methods, except this method is a 1 liner and saves the data for use. Yes, a plugin developer could implement this in their own plugin, but they can also implement other convenience methods (like the three mentioned previously) too.

PR Breakdown:

Simply floors the x, y, and z values to the Location using Bukkit's already present NumberConversions() method and saves these values.

Testing Results and Materials:

Plugin source: http://pastebin.com/yrhNUXSK
Plugin jar: https://db.tt/yx1ubA9i
Plugin Output: http://pastebin.com/DFY3wc87

Relevant PR(s):

None that I could find.

JIRA Ticket:

BUKKIT-4827 - https://bukkit.atlassian.net/browse/BUKKIT-4827

### CODE REVIEW

**Comment by gmcferrin** [comment]
Needs to actually follow the Contributing.MD guidelines. Also, how is this really needed? It's just a convenience method that developers could easily implement themselves and most developers won't even need.

**Comment by BillyGalbreath** [comment]
Updated PR to conform to CONTRIBUTE.md guidelines. About being a convenience method, am I missing the point of convenience methods? I thought they were a Good Thing (TM), which is why we see convenience methods all throughout Bukkit. To convenience the developers.

**Comment by jessestricker** [comment]
Developers can use location.getBlock().getLocation()! No real need for this.

**Comment by BillyGalbreath** [comment]
location.getBlock().getLocation(); seem fine, but its really doing a lot more than it has to just to floor 3 values.

Here's a quick trace I just did on what that line of code is actually doing: http://pastebin.com/7DvjvUwV

This PR's method is much faster with far less to actually do.

**Comment by Black-Hole** [comment]
location.getBlock().getLocation() is much more expensive and can only be used in the main thread.

**Comment by EdGruberman** [comment]
@BillyGalbreath https://github.com/Bukkit/Bukkit/pull/939#issuecomment-25776503

> am I missing the point of convenience methods?

Sort of.  The Bukkit API could be littered with convenience methods and it still may not cover what a given developer needs.  There needs to be more justification than just convenience.  Beyond personal preferences, what makes the API better as a result of having this?

As I see it, this PR would change the following equivalent (functionally and performance wise) code:

```
location.setX(location.getBlockX());
location.setY(location.getBlockY());
location.setZ(location.getBlockZ());
```

into:

```
location.floor();
```

Changing three lines into one seems barely even worth the time it probably took you to compose this PR.  On top of that, most developers that might need this functionality will probably embed these basic steps inside an appropriately named and documented method of their own to indicate why they are doing this.

What is your specific use case for needing this and why is the current solution insufficient for your needs?

**Comment by BillyGalbreath** [comment]
That makes sense now. I guess I got overly excited about making my first PR and my better judgement went out the window. I see now how pointless this really is. Sorry for wasting everyone's time ^_^

**Pull request closed without merging**
