### PR TITLE
Add getLevelName. Adds BUKKIT-4358

### PR DESCRIPTION
**Pull request by ewized**

### CODE REVIEW

**Comment by EdGruberman** [comment]
Please follow the contributing guidelines.

What is insufficient with `Bukkit.getWorlds().get(0).getName()`?  This looks to simply be a convenience method with limited usefulness (only the first world instead of any others).  I doubt the core team will approve the idea.

**Comment by frymaster** [comment]
There is [`String getWorldType()`](http://jd.bukkit.org/dev/apidocs/org/bukkit/Server.html#getWorldType(\)) so a parallel method for getting the name isn't totally unreasonable

@ewized if you want this to be pulled your PRs need to follow the contributing.md guidelines.  For example, right now there's no way to find the associated CB PR without manually searching the CB repo for PRs from you.  I suggest your justification for the change be along the lines of what I said above.

Similarly, consider making the javadoc for this new method mirror the javadoc for `getWorldType()` in wording

**Comment by EdGruberman** [comment]
@frymaster Existing API is rarely a justification that convinces the core team.  There is plenty of existing API that is highly frowned upon.

My assumption is `getWorldType` is one of those frowned upon items.  Bukkit prides itself on its multi-world support.  Convenience methods that only work with the default world seem to undermine that focus by creating confusion on a consistent world interaction.

**Comment by turt2live** [comment]
Abandoned. If you would like this pulled please update it to the latest code base.

**Pull request closed without merging**
