### PR TITLE
Removed outdated biomes.

### PR DESCRIPTION
**Pull request by dannytix**
This (indirectly) solves Bukki-1087

### CODE REVIEW

**Comment by feildmaster** [comment]
Change these removals to deprecations, and put it in a single squashed commit, and I'll think about pulling it.

**Comment by dannytix** [comment]
I see the mistake in the commit itself, which I will fix; but I disagree with changing the removals to depreciations. It would not solve the problem, nor would it offer any other advantage, as the underlying classes these values depend on were themselves removed, not depreciated. What purpose would keeping these serve?

**Comment by Fishrock123** [comment]
Don't RAINFOREST and TUNDRA exist as of now?

**Comment by mikeprimm** [comment]
Not a fan of doing this - breaks with nothing gained, and alters ordinals of values that don't change (binary compatibility issues there).  And, relative to Bukki-1087, you're just trading one runtime error for another in existing plugins.

**Comment by mikeprimm** [comment]
I DO suggest a documentation change (definitely mark the biomes that are currently obsolete as such).  Biomes have come and gone in previous releases (Tundra, the ice biomes), so 'never say never' on biomes really being 'gone'.

**Comment by dannytix** [comment]
No, @Fishrock123, none of the biomes that I removed have any traces left in vanilla minecraft. The only place they exist is in this bukkit enum, since beta 1.8. You could technically remap them to the most similar current biome, but the names are not the only thing that changed, so it would not be completely accurate- and this is not currently being done, anyways. It's effectively dead code that only serves to confuse users.

@mikeprimm What does it break? The only CraftBukkit code I've seen using the ordinals (CraftBlock.biomeToBiomeBase/biomeBaseToBiome) doesn't have the values hard-coded, so it's safe; and plugins shouldn't be using ordinals anyways- it's bad style. I wouldn't mind writing the required changes myself, though, if you'll point me in the right direction. Furthermore, the ordinals currently used are effectively random, so they don't even match the "real" biome ids.

Perhaps I am not being clear enough on why I want this change. Currently, the Biome enum is the only pure-bukkit way of retrieving a list of currently supported biomes. I (and several other developers I've spoken with) use Biome.values in plugins to present players with a list of which biomes can be used with the plugin's commands (anything bukkit supports.) Since some of these biomes don't actually exist, my plugin (through bukkit) is lying to users, who then file a bug report. Really though, the bug is not in my plugin, but bukkit. My only options are to duct-tape things together (maintain my own list of "real" biomes & mappings) or solve the problem at the source, here.

And why would it be such a problem to re-add the outdated values, should they ever come back? It's effectively 10 seconds of work (opening the file, hitting caps lock, typing the biome name) on top of the other changes that are required; and would be no different than when any other new biome is added- only with a "familiar" name and look. It would make sense to keep them around in the bukkit API if the API also supported adding new biomes, but it doesn't; so there isn't any way to make use of these values, even if somebody did re-add the old biome classes through a plugin. I don't disagree with you that some of them could come back someday (although, really, most of them never truly left.) I just don't see the inherent value in future-proofing the API when said future-proofing breaks legitimate use of the API.

Although I don't have a problem with- at a minimum- marking the biomes as depreciated, I still believe it would be better to remove them completely. Besides not solving the whole problem, I feel that it does not accurately reflect the situation. Depreciated implies that, although you shouldn't be using this code, you still can for the time being; with the intention of someday removing the code completely. This is not the case here, though.

**Comment by mikeprimm** [comment]
@dannytix: My problem with your use of the biome enum as a support pattern (that is, making the assumption that the list matches the set supported by the given CB runtime) is that, unless you use it in a decided un-enum-like way (.values() as a list, versus explicit references to the symbols in the enum), you create an unresolvable support problem for folks that DO use it as an enum (e.g. value comparisons, switches, and the like): it makes having a single build of a plugin less able to be version robust.  As I said earlier, biomes have come and gone and returned on more than one occasion - having something that is compile-time sensitive be jerked around for this is bad, since compile time is not run time.  Do we NEED a way to know which are supported in the runtime?  Yep, I think its an excellent idea, and easy to implement (given what I'd already implemented when I did biomeToBiomeBase).  But, fact is, the listing of the biomes in the Biome enum has frankly never, in my experience, been equal to the set supported by vanilla at a given point in time - some of those biomes are pretty ancient at this point, so depending on them as you indicated has never been a good idea.  Once again, it's my position that making a breaking change to make it so, and creating a support pattern that can only be maintained by committing to an ongoing set of breaking changes, is bad.

**Comment by dannytix** [comment]
That is one way to look at the problem, I suppose. Give bukkit developers a way to lookup what biomes are currently available, and I would personally be happy with it. It was my impression, however, that this was already one of the purposes of the biome enum.

Another way to look at it though, is to consider what the situation would be like if instead Mojang had just removed a single biome from the game- let's just say they got rid of "ice plains". Of course, if it was decided to keep ice plains in Craftbukkit- just without regular generation- it would be obvious- keep it in the enum. If instead, however, it was decided to completely remove ice plains from craftbukkit- as these other biomes have already been removed- what should be done?

I think the answer is still clear. Since the underlying classes needed to use ice plains no longer exist, plugins that haven't yet updated to the change will still break in the same way plugins are breaking now, with or without changes to the Biome enum. Plugins would have to be updated anyways, so why wouldn't you update the enum? The only difference here is that it was left alone long enough to be considered "normal" behavior. Just because it was decided a while back not to update the enum does not mean that it has to stay that way now. Whatever was originally being planned for these values has obviously not happened, and it seems clear by now that it's not going to happen. Yes, it's possible these biomes could come back, but it's a slim chance. They weren't just removed, they were replaced. If you asked Mojang to add tundra back in, they'd tell you it's already there- they just call it ice plains now. And what if they did it anyways? The only difference is that you'd have to re-add "TUNDRA" to the enum, which is incredibly easy to do. Furthermore, any plugin written in a way that it would be affected if you did remove tundra from the enum would still have to be updated if tundra was re-added to the game without it being removed to the enum, so the two arguments against making the changes are mutually exclusive.

I also understand the need to maintain compatibility with older plugins, but there is a time to move on, and I think we've reached it. Maybe the update should be rolled into some other plugin breaking release to minimize the impact, but it's really a very minimal change to implement. Developers just need to remove whatever special cases they've added to fix this problem themselves. Personally, I love making those sort of changes- they're easy to make and they clean up my code; but I understand not everyone feels the same way- including the users forced to update. Nevertheless, splitting the enum into a "real" and "historic" copy just sounds messy and redundant. I don't have a problem with the old biomes; I have a problem with them being broken. There's no sense sitting on the fence here- fix them or remove them.

**Comment by EdGruberman** [comment]
I've always thought of enums as a supported/recognized list.  Keeping values in an enum that no longer are implemented/defined anywhere seems pointless.

@mikeprimm can you expand more on your binary compatibility concerns with removing enum values?  Based on the Java documentation it looks like removing wouldn't break plugins, as long as those plugins didn't directly reference a no longer implemented biome?

And then if a constant had to be readded later it wouldn't hurt anything at all?

Are you concerned there are a lot of plugins actively used that directly reference outdated biomes?

> [13.4.26 Evolution of Enums](http://docs.oracle.com/javase/specs/jls/se5.0/html/binaryComp.html)
> Adding or reordering constants from an enum type will not break compatibility with pre-existing binaries.
> 
> If a precompiled binary attempts to access an enum constant that no longer exists, the client will fail at runtime with a NoSuchFieldError. Therefore such a change is not recommended for widely distributed enums

**Comment by dannytix** [comment]
@EdGruberman 

That is exactly it. Removing a value from an enum will cause an error in any code that references that value. As your source mentions, it is generally a bad idea to remove from an enum for this reason. That does not, however, mean that you should never do it with good reason.

Also, I accidentally hit the close button while writing, so just ignore all that...

**Comment by Fishrock123** [comment]
Is people having to update their plugins a terrible thing?

Besides, why the heck would you want a plugin to reference an enum entry that does nothing? That means the plugin is long since broken, with missing functionality.

**Comment by bartenbach** [comment]
If the biomes don't exist, I think that they should be removed.

**Comment by KaBob799** [comment]
Sometimes you have to just go ahead and change outdated things even if it breaks outdated plugins.  If we keep leaving all this outdated and/or nonexistant stuff in Bukkit its just going to become a huge mess.  Might as well take care of some of it now rather than waiting for more stuff to pile up.

**Comment by feildmaster** [comment]
Might leave this for the next minecraft release

**Comment by KaBob799** [comment]
_cough_ Its the next release =D

**Comment by mikeprimm** [comment]
Still say its more downside than upside, particularly given just how many mods are now lightly supported.   I'd recommend adding a test method to return an EnumSet of the biomes supported by the current runtime - but putting functional code in a position of breaking when it would otherwise just have a graceful degrade (i.e. if I'm testing for Biome.SKY, or switching on it, all I get now is that it never happens) isn't good.  The notion that enumerating the Biome enum to see which biomes are supported has literally NEVER worked, so all we're doing is introducing a 'better' behavior that has no existing application dependencies at the expense of breaking other existing ones.

**Pull request closed without merging**
