### PR TITLE
Event system refactoring (by t3hk0d3, fixed)

### PR DESCRIPTION
**Pull request by erisdev**
This is essentially the same change set as #277, but I've reverted the reformatting and squashed the commits into one. @t3hk0d3 is still listed as the author.

I hope to see this pulled with the formatting problems out of the way. As you can see, the diff is quite readable and the changes seem to be sound. Everything compiles cleanly on my end.

I'm tempted to add his annotated listener class, but I'll leave that up to his discretion. C:

### CODE REVIEW

**Comment by erisdev** [comment]
For anybody who's not sold on the idea, I suggest you check out the comments on #277 for arguments in favor.

**Comment by Afforess** [comment]
Okay, I officially change my stance in favor of it, I can see reason. ;)

**Comment by t3hk0d3** [comment]
look on #279 :)

**Comment by Dinnerbone** [comment]
We now have a new event system, thank you for the work but I'm afraid I must close this off.

**Comment by erisdev** [comment]
I ain't even mad.

**Comment by erisdev** [comment]
Although, uh, I'd appreciate a little more information about this "new event system". I haven't touched Bukkit for months. C:

**Pull request closed without merging**
