### PR TITLE
[B+C]Adds the ability to look up online players by UUID. Adds BUKKIT-5071

### PR DESCRIPTION
**Pull request by ghost**
_Before closing this pull request because you think it does not do what it says please read https://github.com/Bukkit/CraftBukkit/pull/1288#issuecomment-30087592._  
- Reason for new pull request: Update to latest Bukkit code base, old PR was not updating correctly.

The Issue:
With the move to UUIDs as the static player identification method it is necessary for any plugin which uses persistent player data to keep track of players by their UUID instead of their username.  Currently looking up a player by their UUID requires the plugin to get the list of online players then test the UUID it is looking for against every player.

Justification for this PR:
- Allows online player lookup by UUID in the same manner as lookup by name, keeping the api consistent.

Previously: 
- Player getPlayer(String name); was the only way to get a single Player.

Now: 
- Player getPlayer(String name); can still be used by plugins which do not need to persist data or protect against name changes.
- Server.getPlayer(String name); allows plugins which use player UUIDs to get players directly.  This will mostly be use by plugins which persist player data.

PR Breakdown:
- Adds the method, Player getPlayer(UUID uuid); to org.bukkit.craftbukkit.CraftServer

Testing Results and Materials:
See CraftBukkit PR.

Results test plugin successfully looks up player by UUID and prints player name and player UUID to console.
- My Mojang UUID is ff01f784ab524b2baf2401052415320f
- The UUID returned by the test plugin using the added method is ff01f784ab524b2baf2401052415320f

Relevant PR(s):
- CB-1288 - https://github.com/Bukkit/CraftBukkit/pull/1288 - Implementation

JIRA Ticket:
- BUKKIT-5071 - https://bukkit.atlassian.net/browse/BUKKIT-5071

### CODE REVIEW

**Comment by TheE** [comment]
Why not returning an OfflinePlayer for players who are offline?

**Comment by mbax** [comment]
@TheE How would you acquire the player name?

**Comment by TheE** [comment]
@mbax If there are no usable methods in NMS, bukkit would need to implement Mojang's [AccountsClient](https://github.com/Mojang/AccountsClient).

To be clear, I am not sure if this is the best possible way to deal with the whole UUID-thing. The only generally problem I see right now is that there are several situations were plugins may need to get the name from a stored UUID for players who are offline. For example, in MyWarp you can list all existing warps together with the name of their creator (who can be online or offline). If I store the UUID instead of the player-name, I need a way to get the name associated with the UUID to make the list human-readable, that works for online and offline players.

**Comment by mbax** [comment]
@TheE AccountsClient supports name to UUID resolution, but not the other way around. :(

**Comment by TheE** [comment]
@mbax Sorry, seems as if I missed that (how could they not implement that?). Please ignore anything I said opposing this pull-request.

**Comment by ghost** [comment]
Rebased fork with latest commits.

**Comment by amaranth** [comment]
See comment on the CB PR.

**Pull request closed without merging**
