### PR TITLE
Removed period character at the end of loading and unload plugin message

### PR DESCRIPTION
**Pull request by DjDCH**
This pull request fixes BUKKIT-699: https://bukkit.atlassian.net/browse/BUKKIT-699

### CODE REVIEW

**Comment by EvilSeph** [comment]
You can't be serious.

**Comment by DrakiaXYZ** [comment]
How about instead of being condescending, you ask him why he is under the assumption that no line should end with a period?

**Comment by TomyLobo** [comment]
I don't think he was commenting on whether to place a period there or not
but wonders why on earth anyone would care, let alone clog the pull request pipe with it

really, there are more important things to fix

**Comment by DrakiaXYZ** [comment]
You are right, there are more important things to fix, too bad attitude like that shown by EvilSeph is one main reason nobody wants to help with those more important things. The user who made this pull request isn't a hardcore dev, they are trying to help out in a way they know how.
 Maybe EvilSeph should take a minute to figure out WHY this user wants things this way, or take the 5 seconds to pull this PR, instead of being an ass about it?

**Comment by TomyLobo** [comment]
these issues exist, but you should've picked a less pointless PR to bring them forward :)

**Comment by stephenwilliams** [comment]
+1 @TheDgtl

**Comment by DrakiaXYZ** [comment]
@TomyLobo This PR is a great example, actually. This user is trying to help out in a way he knows how, and got shot down in a very rude manner for doing so. This does not lead to a positive environment, nor does it provide users who know more in the way of programming any incentive to actually contribute, as they could very well be treated just as badly.
@EvilSeph Before banning more users for making Bukkit unwelcoming, I recommend working on your own attitude first.

**Comment by TomyLobo** [comment]
that's not someone trying to help but someone acting on his OCD...

He doesn't even give any reasons for why this change should be made, neither here nor in the linked ticket.

**Comment by DrakiaXYZ** [comment]
Actually, if you look at the other messages printed to the console:
http://pastebin.com/XVjVBrqN
Nothing there contains a period aside from an actual sentence. So, for consistency, the plugin enable/disable should not contain a period.

Jumping to the conclusion that there is no basis for this PR, or that it's purely based on "OCD" is just you being ignorant. How about next time you try _asking_ the OP why they are making a pull request? Crazy concept in the Bukkit community, I know.

**Comment by DjDCH** [comment]
I didn't expect such reaction when I got the initiative to push this commit, but I understand now that I should have better explain myself from the beginning. 

Before stating my explanation, I think that I need to be clear about this pull request: this is not a troll or any kind of a joke. I have no time to do such thing and I wouldn't be here trying to explain myself in the actual situation. I am very serious in this procedure.

As a system administrator, sending this pull request was entirely natural. I see, read and refer to system logs everyday. When I saw the period character, I was first surprise and I immediately thought about a mistake. Since Bukkit is an open project, it was simply logic to send a pull request that would fix the issue with nothing more to do.

But after reading your comments, I realize that not everybody is familiar with logging and logfiles. As I said above, I'm very familiar with logs and I only see in rare case log line ending with a period character. In those specific case, ending period was applied for all the lines contains within a specific logfile. Except those case, I never saw line ending with a period character, even less in few single lines of a logfile. It's not uniform at all.

I've tried to search for any logfile format or standard. I'm very surprised that I wasn't able to find any RFC or well know standard that state clearly what I am referring to. It seems that "those standards", even if they aren't written, are well respected and applied by all the linux distributions and a major part of the most used daemons.

Is the issue is only esthetical? Well, the presence of these period characters can lead (even if this pretty unlikely to happen) to malfunction of log parsing program or method that read log to analyze them. It can also lead to other esthetic issue, if a wrapper try to embed a log line in a sentence (and that can end with two period character by example).

This is not a big issue at all. It is mainly for consistency of logfiles and to respect those not written conventions explain above. Even if this will unlikely lead to real issue, there is no reason to reject this pull request. This pull request meets the Bukkit coding standards and requirement. I have take the time to create a issue in the JIRA instance and link it to the pull request. I have done this job in good faith. 

Please, be comprehensive, and understand my point of view. I do not expect this pull request to be accepted with the actual reaction of the Bukkit community, but I hope that you will at least understand my motivations and the reasons behind it.

Sincerely,

DjDCH

**Comment by Majiir** [comment]
+1 @DjDCH 

I felt uneasy when I first saw these new log messages, but I couldn't quite put my finger on it. (I code professionally, but I'm only an amateur sysadmin.) I think @DjDCH makes some salient points about this excess of, er, points.

I don't think every PR has to be a big structural change. In fact, it's probably more healthy if PRs are small and isolated. It's not like this is a difficult merge.

**Comment by EvilSeph** [comment]
One of the requirements for pulls to be considered is for effort to be put into them. As there was a clear lack of effort put into this pull request, we naturally treat it like every other of its kind. We get many pulls and JIRA tickets of this nature several times a day (more so on JIRA than GitHub, obviously), it is simply unrealistic to expect us to chase after each and every pull author to request what should have been in the pull in the first place to make it a valid one, as per our standards. Couple this with a ticket that is of equal use in explaining the person's intentions and demonstrating any effort (read:none) and I'd say our reaction was valid and stand by it. I'd much rather my team focus on reviewing legitimate pull requests than waste their time managing pointless ones.

Usually we'd just close these pulls without a comment and leave it at that, but in an effort to provide reasoning for every decision we make on whether a pull or not is appropriate and acceptable, we now have to post a comment however short it may be.

As you have now provided justification for the proposed changes and put forth some effort into the (pull) request, I'll reopen this for consideration.

**Comment by Majiir** [comment]
> in an effort to provide reasoning for every decision we make on whether a pull or not is appropriate and acceptable, we now have to post a comment

@EvilSeph, I'm not sure the following comment is really in that spirit.

> You can't be serious.

**Comment by patrickfreed** [comment]
You keep saying it requires "effort", and my question is why? This PR has one goal that requires little effort to complete; I don't see how that makes it a joke, as you implied.

**Comment by craftycreeper** [comment]
Good to see we're spending so much time and effort worrying about two periods. Surely we have something better to do. :/

**Comment by petteyg** [comment]
Nope, @craftycreeper. This pull request apparently didn't involve enough effort to be worthy of the great Bukkit, so we're applying extra effort.

**Comment by stephenwilliams** [comment]
Uhhh..... Why wouldn't this be pulled? It solves a (granted unimportant) problem, but required NO effort from the Bukkit team and doesn't have to be tested because it only changes some issues in logging, effectively its fixing a typo in logging.

**Comment by EdGruberman** [comment]
While I think the drama surrounding this pull request is preposterous, I absolutely agree the period should be removed.

What gets me even more though is the word "loading".  It's in the enablePlugin method that calls onEnable.  While the onLoad event doesn't have any log indication at all.  This log entry should say "enabling" (and "disabling" as appropriate).  How was that overlooked with all the concern over the simple grammar? heh

My plugins have always said the version in onLoad and a simple "Plugin Enabled" message in onEnable.  It's not like the version is going to change each disable/enable cycle and if anything you want to know what version of a plugin is loading at its first possible interaction, onLoad.  I suppose it's arguably useful at the onEnable as a reminder/quick reference also.

https://github.com/EdGruberman/SimpleTemplate/blob/master/src/edgruberman/bukkit/simpletemplate/Main.java

**Comment by Afforess** [comment]
_yawn_

Clearly no one here ever learned to pick and choose your battles. :/

**Comment by DrakiaXYZ** [comment]
@Afforess Why pick and choose when you can fight them all? ;) Haha.
Also, I was bored at the time I saw this quite rude comment from EvilSeph, it was less to do with the PR in itself, and more to do with the attitude of the "head" of Bukkit.

**Comment by EdGruberman** [comment]
So this is what I'd propose...  Periods removed, loading/unloading words changed to enabling/disabling, using the new plugin.getLogger() to leverage the standard plugin name prefix automatically, and adding a loading message to CraftBukkit for clarity. (Seems weird the onLoad call is in CraftBukkit and not Bukkit, no?)

https://github.com/EdGruberman/Bukkit/commit/e2c17979dca28177af635ef066e4d67dc0a1e192

https://github.com/EdGruberman/CraftBukkit/commit/21ab778b7bef52f5a56e4c866910d767b77b2ac2

**Comment by EvilSeph** [comment]
Pulled EdGruberman's commits, thanks!

**Pull request closed without merging**
