### PR TITLE
include sources in mvn deploy

### PR DESCRIPTION
**Pull request by XanderFast**
bukkit maven repo should include sources jar

### CODE REVIEW

**Comment by XanderFast** [comment]
I use eclipse which generates javadoc from the source on the fly.  But mostly I wanted the source for the occasional drill down.

**Comment by t3hk0d3** [comment]
+1

**Comment by nightpool** [comment]
Would solve [SITE-75](https://bukkit.atlassian.net/browse/SITE-75) (At least partially)
And solved bug reports are always good.

**Comment by Wolvereness** [comment]
This is not the best way to approach this problem. The proper way would require a change to the repository, that may or may not come later, but that does not justify this change.

**Comment by XanderFast** [comment]
What change is required?

**Comment by nightpool** [comment]
I believe it would be a change in the maven configuration.

**Pull request closed without merging**
