### PR TITLE
Addresses https://bukkit.atlassian.net/browse/BUKKIT-770

### PR DESCRIPTION
**Pull request by defek7**
Added new event EntityPrimeEvent to properly handle triggering of TNT blocks into TNT
Entities.

### CODE REVIEW

**Comment by asofold** [comment]
Actually this might also be useful with creepers later.

I will continue discussion in the related pr:  context: https://github.com/Bukkit/CraftBukkit/pull/869

**Comment by riking** [comment]
Of course this is still relevant, but I think the name is taken.

**Comment by riking** [comment]
@defek7 If you want this to be pulled, you need to update to the latest CraftBukkit, and fix the formatting errors.

**Comment by turt2live** [comment]
CraftBukkit PR was closed 6 months ago.

**Pull request closed without merging**
