### PR TITLE
Fixed English fail

### PR DESCRIPTION
**Pull request by iffa**
- Sets the sneak mode the player

->
- Sets the sneak mode of the player

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Replying comment the pull request for addition into project.

**Comment by Nightgunner5** [comment]
I like joke very Dinnerbone good.

**Comment by iffa** [comment]
Nightgunner is plugin good developing.

**Comment by EvilSeph** [comment]
I am working on addressing JavaDocs as a whole, so this will not be pulled as I will or likely already have had this fixed, just not pushed yet.

**Pull request closed without merging**
