### PR TITLE
Create HealCommand.java

### PR DESCRIPTION
**Pull request by MrInspectorDev**
Sorry, I know I'm wasting your time, but this should work, right?

Sorry, I'm pretty new at contributing, I don't really know much on how to contribute to bukkit, I'm still learning, we learn it at different paces, and I may be a little slow but I'm still getting their step by step, sorry ;/

### CODE REVIEW

**Comment by Wolvereness** [comment]
Commands in Bukkit are either _Bukkit_ related (like /reload) or default Minecraft ones. See:

http://minecraft.wikia.com/wiki/Commands
http://minecraft.gamepedia.com/Commands

You should also review http://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

It also doesn't work...

**Comment by blha303** [comment]
You can add commits to old PRs. Also you're not following the guidelines, and they don't want the command because it isn't in vanilla minecraft.

**Comment by MrInspectorDev** [comment]
Oh okay, thanks, and I know I'm wasting time - but what guidelines did I exactly not follow o.o

**Comment by blha303** [comment]
No, it's fine to ask questions. https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md#commit-message-example and below that, but read the whole document if you want to contribute to Bukkit.

**Comment by Wolvereness** [comment]
@MrInspectorDev https://github.com/Bukkit/Bukkit/pull/966#issuecomment-29439042

> Oh okay, thanks, and I know I'm wasting time - but what guidelines did I exactly not follow o.o

Enough of them to draw a conclusion that you have not read them at all.

**Comment by MrInspectorDev** [comment]
Okay thanks blha303 & Wolvereness ;p

**Comment by stuntguy3000** [comment]
@Wolvereness Are you always stuck up like that? Seriously..

**Comment by turt2live** [comment]
@stuntguy3000 Uncalled for. :/

**Comment by blha303** [comment]
@stuntguy3000 Stuck up? It was pretty clear MrInspectorDev hadn't read the contributing guidelines.

**Comment by JamesNorris** [comment]
@stuntguy3000 I have noticed similar behavior. They banned me from the bukkit and bukkitdev chats for my reaction to it. Anyways, to get back on topic. @MrInspectorDev This command will probably never be added to Bukkit. If you want to add it, just create a plugin, I am sure it won't take long at all, and you can probably learn a bit about the API that way.

**Comment by EvilSeph** [comment]
@stuntguy3000 https://github.com/Bukkit/Bukkit/pull/966#issuecomment-29442462

> @Wolvereness Are you always stuck up like that? Seriously..

@JamesNorris https://github.com/Bukkit/Bukkit/pull/966#issuecomment-29554961

> @stuntguy3000 I have noticed similar behavior. They banned me from the bukkit and bukkitdev chats for my reaction to it. Anyways, to get back on topic. @MrInspectorDev This command will probably never be added to Bukkit. If you want to add it, just create a plugin, I am sure it won't take long at all, and you can probably learn a bit about the API that way.

This isn't the proper place to provide constructive criticism or feedback on the way the project functions, we have a forum dedicated to that. You should follow @stuntguy3000's lead:
http://forums.bukkit.org/threads/so-i-wanted-to-know-why-there-is-a-lack-of-communication.197680/#post-2027527

Please continue discussions of this nature by creating a thread here:
http://forums.bukkit.org/forums/bukkit-project-and-community-feedback.12/

GitHub Pull Requests comments are purely for discussion on the PR and not a place to discuss the behaviour of a  Bukkit team member or any individual.

**Comment by MrInspectorDev** [comment]
@JamesNorris I know how to make a heal plugin, I already know my way around the API, I just want to contribute to the bukkit project really bad, i'm trying my best to read everything I can for contribution.

**Comment by JamesNorris** [comment]
@EvilSeph As I did. I discontinued the conversation. @MrInspectorDev Alright, well try looking through the issues first, you can find stuff to fix or improve upon there: https://bukkit.atlassian.net/secure/Dashboard.jspa

**Comment by turt2live** [comment]
EDIT: I really need to read.

**Comment by MrInspectorDev** [comment]
Okay @JamesNorris, thanks!

**Pull request closed without merging**
