### PR TITLE
More plugin info shown in /pl

### PR DESCRIPTION
**Pull request by TheRedCrafter344**
Now shows version too, not only plugin name.

### CODE REVIEW

**Comment by mbax** [comment]
Helpful!

Unfortunately, Bukkit development stopped in 2014, so you're a little too late for most people to benefit:)

**Comment by TheRedCrafter344** [comment]
Guess I'll have to make a plugin for that.

**Comment by Walkman100** [comment]
Sounds like a useful plugin

**Comment by IsaiahPatton** [comment]
Bukkit development stopped in 2014, But Spigot is still going!

**Pull request closed without merging**
