### PR TITLE
Add Event.stopPropagating and Event.isPropagating

### PR DESCRIPTION
**Pull request by cole2sworld**
Adds https://bukkit.atlassian.net/browse/BUKKIT-1714 - allows a plugin to stop an event in it's tracks right then and there.

Like a hard-cancel.

### CODE REVIEW

**Comment by gravitylow** [comment]
What would this be used for?

**Comment by gravitylow** [comment]
That's what I was thinking too, except I can't really see a clear use-case for this.

**Comment by cole2sworld** [comment]
I knew that "giving too much power to the plugins" would come up somewhere - but isn't that the server admin's fault? Install a virus, it's your fault for visiting that bad site and downloading their stuff.

As for usefulness, I can see it being used to get rid of garbage events, being used to truly cancel BlockBreak and the like for protections, etc. And also, a lot of bugs that show up in many plugins are from conflicts with other plugins, and those plugins screw up the values in the event since they don't honor isCancelled.

**Comment by gravitylow** [comment]
Unfortunately, while it could be seen as the server admin's fault, that's not how it works. I don't think we can just throw things that could potentially be dangerous to a server into the system just because we want it to be there, and then say "oh it's the server admin's fault if it hurts them." The Bukkit API should only provide things that are safe for everyone to the plugins. Admittedly, there are some exceptions to that already, but at least the ones that are there are an integral part of the game, and have a very clear use-case. As for this, I don't think it's so much of a "this plugin has too much power" rather than just "this plugin was coded horribly and is screwing everything up". I can see that happening a lot with this, and it seems the benefits of this are a bit minor compared to the damage and confusion it could cause.

**Pull request closed without merging**
