### PR TITLE
Allow top-level config properties to have individual comments

### PR DESCRIPTION
**Pull request by ZerothAngel**
Original discussion [here](http://forums.bukkit.org/threads/how-does-one-write-a-default-list-comments-in-the-middle-of-a-yml-file.39852/).

This is similar to the way a header can be added and allows for a more verbose and helpful config file.

Example code:

``` java
        Configuration config = getConfiguration();
        config.setComment("foo", "# This is foo");
        config.setComment("bar", "\r\n# This is bar");

        config.setProperty("foo", 42);
        List<String> someList = new ArrayList<String>();
        someList.add("garply");
        someList.add("baz");
        config.setProperty("bar", someList);

        config.save();
```

Example output:

```
# This is foo
foo: 42

# This is bar
bar:
- garply
- baz
```

### CODE REVIEW

**Comment by feildmaster** [comment]
This should easily be allowed to set comments anywhere, no?

**Comment by ZerothAngel** [comment]
That would be ideal, yes. However, the entire config is stored as a map. And originally, a single YAML.dump() was called on that map.

To support comments anywhere, you'd have to drill down into each property (recursing into other maps) and dump() each property out individually. I compromised by only supporting top-level properties. The new methods I added don't preclude eventually allowing comments anywhere since they take property paths.

There may be other issues too (e.g. guessing the correct indent level for the comment).

If I missed an obvious alternative, please let me know...

**Comment by Salynne** [comment]
I would be very happy if someone actually made a pull to make the config stored as something other than a map. I don't think startup config load times are really an issue? I really hate having to call save/load every property in order to get it out in order, I ended up dropping using Config entirely and instead extract a pre-made one from the jar.

**Comment by Dinnerbone** [comment]
We're no longer updating the old Configuration.

**Pull request closed without merging**
