### PR TITLE
Event system refactoring

### PR DESCRIPTION
**Pull request by t3hk0d3**
For greater flexibility.

### CODE REVIEW

**Comment by Afforess** [comment]
This is better how?

**Comment by t3hk0d3** [comment]
> This is better how?

Now you can make universal event listeners, for any type of events, using onEvent(Event).
Also huge unbeauty event type switch removed from PluginLoader.

**Comment by t3hk0d3** [comment]
oops, pressed wrong button. sorry :(

**Comment by lycano** [comment]
Please implement this! I cannot wait to define own Events. this would be so freaking awesome if i could just implement Listener interface directly to do my own Event handling. No barrier! Any plugin could then use other custom defined events too; Unjail events and let us play ^.^

**Comment by xZise** [comment]
@lycano: Ehr at the moment, it is already possible to issue the [CUSTOM_EVENT](https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/Event.java#L739)? Actually this pull requests here moves the "case switching" from the JavaPluginLoader to the Listener itself.

Fabian

**Comment by grum** [comment]
Besides useless changes because of bad formatting; I'm not quite seeing much benefit from this? Bar the semi-obvious; the switch is smaller so theoretically dispatching the event is a fraction faster.

**Comment by Afforess** [comment]
I agree with Grum, the change does not seem to be better or worse than the existing system, with no real advantages.

**Comment by t3hk0d3** [comment]
2 Affortress, grum, xZise
Again, main advantage what now you can create univeral (and catch any event you want) listeners, not separate listeners for each types (block, entity, vehicle, etc) of Event.

And again - This is refactoring, not optimisation or ether. It shouldn't make big advantages, just make system a bit more flexible, scalable and easy to handle.

For non-professional programmers who doesn't know this term: 
http://en.wikipedia.org/wiki/Code_refactoring

> Code refactoring is "a disciplined way to restructure code",[1] undertaken in order to improve some of the nonfunctional 
> attributes of the software. Typically, this is done by applying series of "refactorings", each of which is a (usually) tiny change in a
> computer program's source code that does not modify its functional requirements. Advantages include improved code
> readability and reduced complexity to improve the maintainability of the source code, as well as a more expressive internal
> architecture or object model to improve extensibility.

**Comment by akrieger** [comment]
I'm actually glad that the current event system forces people to make separate classes for each type of listener, otherwise all of the 'non-professional' programmers you think we are would just shove every listener into one omni file which would be damn near unreadable and unmaintainable. In this case, a slight cludginess in the API enforces better coding practices in the plugins.

**Comment by t3hk0d3** [comment]
akrieger 
Man, no one force you to use onEvent directly.
Making barriers just to prevent inexperienced developers from coding errors are bad idea.

**Comment by DrakiaXYZ** [comment]
It doesn't offer greater flexibility though. Could you explain exactly how you think the ability to have EVERY event handled in one function is more flexible than having events handled on a per-listener basis? They both accomplish the exact same result, while this one will lead to cluttered code, and require more end-user code.

**Comment by t3hk0d3** [comment]
TheDgtl
And again, conventional abstract listeners (BlockListeners, PlayerListener, etc) are still here.

**Comment by Afforess** [comment]
"Making barriers just to prevent inexperienced developers from coding errors are bad idea."

Funny, I thought that was the idea behind Java.

**Comment by erisdev** [comment]
@TheDgtl I can see it being useful to people developing plugins for dynamic languages like JavaScript. There's no sense having a million listener objects registered just to forward all events to a single script. A hypothetical JavaScript listener using onEvent might look like this—if you'll forgive me for not knowing one of the JavaScript-in-Java APIs off the top of my head, and for indenting like a C programmer:

```
class JSListener
    extends Listener
{
    private static final String FALLBACK_CALLBACK = "onEvent"; // the name rhymes; sue me

    private final Logger log = Logger.getLogger("Minecraft");

    private String scriptName;
    private JSObject callbacks;

    public JSListener(String scriptName, JSObject callbacks)
    {
        this.scriptName = scriptName;
        this.callbacks = callbacks;
    }

    @Override
    public void onEvent(Event event)
    {
        String callbackName = getCallbackName(event.getType());
        if ( callbacks.hasProperty(event.getType.toString()) )
            callbacks.callMethod(callbackName, event);
        else if ( callbacks.hasProperty(FALLBACK_CALLBACK) )
            callbacks.callMethod(FALLBACK_CALLBACK, event);
    }

    private String getCallbackName(Event.Type type)
    {
        // code to convert EVENT_TYPE to onEventType that I can't be arsed to write
    }
}
```

With the addition of an appropriate catch-all event type constant, a scripting language plugin wouldn't even need to update just because Bukkit adds a new event. Cleverly written (as anything I write in a dynamic language tends to be), the JavaScript side could call something like this and be done with it:

```
Bukkit.registerScript('A Rude Script', '1.0', {

    onPlayerJoin: function(event) {
        console.log("Some lamer calling themselves '"
            + event.getPlayer.getName() + "' showed up.");
    },

    onPlayerQuit: function(event) {
        console.log("Good riddance, " + event.getPlayer.getName() + "!");
    }

})
```

Also, @akrieger, who cares if bad programmers write bad code? It's not your place to try to force people to follow good programming practice, and poor programmers will still write poor, unmaintainable code until they learn.

**Comment by erisdev** [comment]
I'd also like to add that, while it's wonderful and excellent to write modular, maintainable code, and please do if you're building a complex system, sometimes you just want to write a quick damn hack and get it over with. Modern IDEs and programmers' editors make it relatively easy to refactor code if you later decide that your quick hack needs to grow into a Real Project™. The large amount of rigidly enforced coding practices in Bukkit make those quick hacks needlessly verbose, and that's why I haven't actually written those quick-and-dirty bindings for JavaScript or Ruby or some other language yet.

**Comment by t3hk0d3** [comment]
Here is another example:

```
@Retention(RetentionPolicy.RUNTIME)
public @interface EventHandler {
    org.bukkit.event.Event.Type value();
}

public abstract class AnnotatedListener implements Listener {

    protected Map<Event.Type, Method> events = new EnumMap<Event.Type, Method>(Event.Type.class);

    public AnnotatedListener(Plugin plugin, PluginManager pluginManager) {

        for (Method method : this.getClass().getMethods()) {
            EventHandler handler = method.getAnnotation(EventHandler.class);
            if (handler == null) {
                continue;
            }

            pluginManager.registerEvent(handler.value(), this, Event.Priority.Normal, plugin);
            this.events.put(handler.value(), method);
        }
    }

    @Override
    public void onEvent(Event event) {
        if (!this.events.containsKey(event.getType())) {
            return;
        }

        Method method = this.events.get(event.getType());
        try {
            method.invoke(this, event);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}

public class ExampleListener extends AnnotatedListener  {
    .....
    @EventHandler(Type.BLOCK_BREAK)
    public void onBlockBreak(BlockBreakEvent e){
        // .. do stuff
    }
}
```

**Comment by grum** [comment]
t3hk0d3 said: Again, main advantage what now you can create univeral (and catch any event you want) listeners, not separate listeners for each types (block, entity, vehicle, etc) of Event.

I do agree that having mandatory different types of listeners is not so 'nice', but if the goal is to remove those, wouldn't you have put all the dispatching in a single method like it was in the old hMod days? (too much will become slow eventually).

Also (don't pin me down on this); there should actually be a comment in the Bukkit code saying that we should eventually make this system a bit more generic, however this only seems part of that change.

I do like the ability to use annotations however. In fact, I'd even prefer that to become the only way of doing it.

**Comment by t3hk0d3** [comment]
grum
Actually only Annotated events will break Bukkit's "platform irrelevance" because it use language specific features.

**Comment by erisdev** [comment]
@t3hk0d3 Wow, you can _do_ stuff like that with Java? That's just down-right beautiful from a plugin developer's point of view. TBH, I think Bukkit should adopt that as an official part of the API. That would make it hell of easy to group event handling code into classes by function or purpose (i.e., permissions- or economy-related events) rather than event type, too.

Do you do this for a living?

**Comment by xZise** [comment]
Actually, why should this pull produce not maintainable code:
"[…]while this one will lead to cluttered code, and require more end-user code."
I mean the event system like it is isn't so much better (if it is even better). I mean a plugin with 2 events don't need two classes with this pull.

Okay it is possible to create anonymous classes, but are they super maintainable?

Fabian

**Comment by grum** [comment]
t3hk0d3: hehe doesn't mean I do not prefer it. Also I do not think you can 'force' people to use annotations, as the annotations have to be implemented in some way, and using reflection you can break any 'java-tin-can' open in seconds.

**Comment by t3hk0d3** [comment]
xZise
This "system" do not break compatibility. If you want use BlockListener or PlayerListener you can still use them as you do it before. This is just refactoring which make event handling system code slightly better and occasionally offer more flexibility :)

**Comment by xZise** [comment]
I didn't say it break compatibility! I only want to say: This is a fantastic way for plugins to reorganize the events. As in Java it isn't possible to inherit from multiple classes, you couldn't combine two listeners in one.

Fabian

**Comment by grum** [comment]
You still can't do that using this.

**Comment by t3hk0d3** [comment]
grum
No he can. You readed diff and examples, right?

**Comment by xZise** [comment]
Okay, maybe I wasn't clear with my statments. But this pull allows other plugin developers to manage the events on their on. Actually, it is possible, to provide different types of listeners. You don't have to use PlayerListener if you want to get player events. You could, but it isn't necessary. Actually I also was working on a different system to accomplish this (but unfortunately this will break (almost) every plugin). You can read more about this [here](http://forums.bukkit.org/threads/new-event-handling-system.22395/).

This pull request doesn't change anything. The developers could code like before, but other developers could create their own listeners. So I don't see any reason for TheDgtl's statement:

```
They both accomplish the exact same result, while this one will lead to cluttered code, and require more end-user code.
```

Fabian

**Comment by grum** [comment]
@xZise: Maybe because I never actually made that statement? :/

Also I generally do not care to read commits which are clearly badly formatted (and thus create WAY more diffs than actually needed). If there is no effort in representation there shall be non in reading. :D

**Comment by t3hk0d3** [comment]
@grum
than you show you not from brighter side. Formatting doesn't actually matter (Say Thx to Netbeans formatter).
You doesn't readed diff, but started active argue. :/

**Comment by erisdev** [comment]
@t3hk0d3 I think grum's point is that you've changed the indentation and bracket placement of code that you didn't touch. It makes the diff hard to read because there are a lot of "junk" changes with no content between the real meat. You say formatting doesn't matter, but it makes a lot more work for the person who pulls your changes if you cock it up. If your editor is doing this automatically, then you need to either turn off that feature or get a new editor.

I'd like to see this commit redone without all the unnecessary reformatting, because it looks like a big step in the right direction to me.

**Comment by t3hk0d3** [comment]
@erisdiscord
Okay.

**Comment by erisdev** [comment]
@grum I've made my own pull request #278 that includes the same meat but without the formatting issues. As an added bonus, I used git-rebase to squash the fixups into a single commit, so it's easier to roll back the change.

@t3hk0d3 you're still credited as the author since I basically pulled your changes and modified them with rebase. Hope you don't mind. C:

I actually did this a few hours ago, but then dinner happened and I never got around to drawing anybody's attention.

**Comment by t3hk0d3** [comment]
More advanced change upcoming :D

**Comment by t3hk0d3** [comment]
This commit closed due existence of better versions.

Look these:
https://github.com/Bukkit/Bukkit/pull/279
https://github.com/Bukkit/Bukkit/pull/278

**Comment by xZise** [comment]
@grum Sorry, thought you said this.

**Pull request closed without merging**
