### PR TITLE
- Added InventoryOpenEvent and InventoryCloseEvent. (Still need to be called in NetServerHandler)

### PR DESCRIPTION
**Pull request by halvors**
I've just done the pre work. Look at afforesses code to see how the call is done. If it's ok for him.

<a href="https://github.com/Bukkit/CraftBukkit/pull/351">CraftBukkit Pull Request</a>

### CODE REVIEW

**Comment by EvilSeph** [comment]
I've already said we will not be pulling this. It is already being worked on and your pull is broken.

**Comment by halvors** [comment]
So it's being developed by someone internal?

**Comment by Afforess** [comment]
Halvors, IIRC, Grum is working on a solution. I believe I mentioned this multiple times.

**Comment by halvors** [comment]
Thanks :D

**Comment by Rigby90** [comment]
Indeed most of the work has already been done by someone internally, there's some strict requirements and guidelines for the inventory events.

Doesn't hurt to try though, so thanks :).

**Comment by halvors** [comment]
I actually just added the Event classes, the callings weren't done :(

**Comment by halvors** [comment]
Just hope that the inventory events will be called when open chest's too :D

**Comment by Afforess** [comment]
Of course they will. Why would Bukkit go to so much trouble for partially functional events? 

If you need them now - bukkitcontrib works fine until the official release.

**Comment by halvors** [comment]
@Afforess
BukkitContrib is nice :D But i don't want to force my users to use it.

**Comment by Afforess** [comment]
We're getting off topic now;

Why not? It doesn't do anything. It's a library. You already force your users to use the bukkit server wrapper. It's a library.

**Pull request closed without merging**
