### PR TITLE
Adding 1.0 Vanilla Commands

### PR DESCRIPTION
**Pull request by Rob4001**
This adds the /toggledownfall and /xp <playername> <amount> Commands to bukkit

Hope this is correct

### CODE REVIEW

**Comment by rqf** [comment]
I have been wondering why bukkit did not include this, or perhaps they just haven't gotten to it yet

**Comment by Rob4001** [comment]
They are either doing more important stuff or have forgotten to implement it (minecon and all) this. Is just so that it is a one button implement job like all the others who just want to help 
:)

**Comment by Rob4001** [comment]
Woops
I commented last time on my phone it closed it (St00pid phone)

Im going to have to update this to new Experience methods :(

**Comment by Rob4001** [comment]
Sorry for the second commit

**Comment by vanZeben** [comment]
Why not merge the experience into the /give command

ie. /give <name> exp #

seems more relevant on the front end as opposed to creating a new command that is disambiguous.

**Comment by Rob4001** [comment]
Although this is true these are implementations of the vanilla commands that have been left out plain and simple.

**Comment by vanZeben** [comment]
yea, but why create new commands for them instead of merging them into current ones where it makes more sense. Dont be lazy now -_-

**Comment by Rigby90** [comment]
> yea, but why create new commands for them instead of merging them into current ones where it makes more sense. Dont be lazy now -_-

Because they are vanilla commands plain and simple... Modifying vanilla commands and syntax is not something Bukkit does, as scripts and wrappers rely on Vanilla setups.

**Comment by Rob4001** [comment]
^ and van please don't call me lazy I don't see you helping

**Comment by Dinnerbone** [comment]
No longer needed, but thanks!

**Pull request closed without merging**
