### PR TITLE
PluginsCommand - make length getting more sensible

### PR DESCRIPTION
**Pull request by LunNova**
Removes pointless counter and uses .length in PluginsCommand.getPLuginList()

### CODE REVIEW

**Comment by feildmaster** [comment]
That's a good point.

git commit --amend "Use plugins.length instead of a counter" and a ticket here: http://leaky.bukkit.com

**Comment by LunNova** [comment]
I assume you mean leaky.bukkit.org ?

**Comment by feildmaster** [comment]
umm.. yes. I was in a rush for work.

**Comment by EvilSeph** [comment]
Haha...yea, I totally missed that.

**Comment by feildmaster** [comment]
Pulled, thanks.

**Comment by EvilSeph** [comment]
I just implemented this myself and gave you credit as it was easier to do so. Forgot to close this pull request, thanks!

**Pull request closed without merging**
