### PR TITLE
Add SnowmanTrailEvent

### PR DESCRIPTION
**Pull request by DrakiaXYZ**
This event is called when a snowman entity places snow on the ground. This event is cancellable.

CB Pull Request: https://github.com/Bukkit/CraftBukkit/pull/590

### CODE REVIEW

**Comment by davidcole1340** [comment]
Sounds nice. Now loggable. 1+

**Comment by tips48** [comment]
Yes please!

**Comment by CelticMinstrel** [comment]
#456 is probably better though.

**Comment by DrakiaXYZ** [comment]
@CelticMinstrel Personally I think this goes better with how Bukkit has currently implemented entity-based block events (EndermanPickEvent, etc), though EntityBlockFormEvent is definitely more generalized.

**Pull request closed without merging**
