### PR TITLE
Added a ban API

### PR DESCRIPTION
**Pull request by pschichtel**
I added the new methods banPlayer(String message), unbanPlayer(), banIp(String message) and unbanIp() to the Player class.
The methods banPlayer and banIp call the PLAYER_BAN event (also added by this pull) right before the ban gets executed and can by cancelled.

This is my first pull-request, so I hope everything is fine.

CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/261

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Does PLAYER_BAN fire if someone uses the vanilla ban commands?

**Comment by mickael9** [comment]
No

**Comment by pschichtel** [comment]
No, but I'll change that, when I make it MC 1.5 compatible

**Comment by pschichtel** [comment]
https://github.com/Bukkit/Bukkit/pull/211

**Pull request closed without merging**
