### PR TITLE
Interface for getting recipes (by result) and removing recipes

### PR DESCRIPTION
**Pull request by CelticMinstrel**
I couldn't think of a nice way to add getRecipe and removeRecipe, but this commit provides the same functionality in a different way: by providing an iterator with which you can go through the registered recipes, examine them, and optionally remove them.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
[https://github.com/Bukkit/CraftBukkit/pull/445](Associated CraftBukkit pull request)

**Comment by Dinnerbone** [comment]
What's the reasoning for breaking the return of addRecipe?

**Comment by CelticMinstrel** [comment]
Well, the returned recipe is the same recipe as the input, except that it's now also a CraftRecipe. However I would be fine with that detail being reverted.

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
