### PR TITLE
[B+C] Add API for respawning players. Adds BUKKIT-4029

### PR DESCRIPTION
**Pull request by ninja-**
##### The Issue:

There is no way to respawn the player when he's dead.
##### Justification for this PR:

Existing methods to make the client skip the death screen are either clunky or use volatile internal code.
##### PR Breakdown:

A respawn() method is added to Player, which first checks whether or not they are actually dead and respawns them after verifying that they are not alive.

It calls PlayerRespawnEvent and everything if you wonder.

Adds respawn() method to Player.

``` java
    @Override
    public void respawn() {
        if (entity.dead) {
            server.getServer().getPlayerList().moveToWorld(getHandle(), 0, false);
        }
    }
```

You can also ask: why using this method and why I am sure it will work?
It is same code as from packet 205's handler, see https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/PlayerConnection.java#L589
##### Relevant PR(s):

Bukkit - https://github.com/Bukkit/Bukkit/pull/940  - Added API for this.
CraftBukkit - https://github.com/Bukkit/CraftBukkit/pull/1251 - Implemented new API method.
##### JIRA Ticket:

BUKKIT-4029 - https://bukkit.atlassian.net/browse/BUKKIT-4029
##### Pull Request Check List (For Your Use):

**General:**
- [x] Fits Bukkit's Goals
- [x] Leaky Ticket Ready
- [x] Code Meets Requirements
- [x] Code is Documented
- [x] Code Addresses Leaky Ticket
- [x] Followed Pull Request Format
- [x] Tested Code
- [x] Included Test Material and Source

**Example plugin:**

``` java
    // disables respawn screen
    @EventHandler(priority = EventPriority.LOWEST)
    public void onDeath(final PlayerDeathEvent ev) {
        Bukkit.getScheduler().scheduleSyncDelayedTask(plugin, new Runnable() {
            public void run() {
                ev.getEntity().respawn();
            }
        });
    }
```

### CODE REVIEW

**Comment by riking** [comment]
Will a plugin using this functionality be able to break others not using it?

What happens if I call `respawn()` during the death event?

Are there things that normally happen in NMS when a player clicks respawn that are skipped here?

Is the main world always correct?

Is the `moveToWorld()` going to call a `PlayerRespawnEvent`? If not, why aren't you calling one?

I shouldn't have had to go to the CraftBukkit PR's file view to figure out that the way you were doing this was the `moveToWorld(getHandle(), 0, false)` method in PlayerList - that should've been in your "PR Breakdown" section.

If "plugins simulating respawn screen 'click' packets" are "very popular", why is that not being done here? I.e., what makes this method better than calling the 205's handler?

<hr>

Also, why are you using the inferior `scheduleSyncDelayedTask` method? `runTask` is a much more descriptive function.

**Comment by jessestricker** [comment]
Why would you need this anyway? I'm using this:

``` Java
@EventHandler
void onPlayerDeath(PlayerDeathEvent event) {
    event.getEntity().setHealth(20d);
    event.getEntity().teleport(event.getEntity().getWorld().getSpawnLocation());
    // some other resetting
}
```

It resets the players health to prevent him/her from dying and teleporting him/her to the spawnpoint.
Then you can clear the inventory, setting the xp to 0, etc.

**Comment by ninja-** [comment]
> Will a plugin using this functionality be able to break others not using it?

no

> What happens if I call respawn() during the death event?

I don't think player is dead already, there are much funnier ways to break stuff from inside events anyway.

> Are there things that normally happen in NMS when a player clicks respawn that are skipped here?

no

> Is the main world always correct?

yes, respawn event would be called and you can change the world

> Is the moveToWorld() going to call a PlayerRespawnEvent? If not, why aren't you calling one?

yes

> I shouldn't have had to go to the CraftBukkit PR's file view to figure out that the way you were doing this was the 
> moveToWorld(getHandle(), 0, false) method in PlayerList - that should've been in your "PR Breakdown" section.

whatever

> If "plugins simulating respawn screen 'click' packets" are "very popular", why is that not being done here? I.e., what makes this method better than calling the 205's handler?

look at 205's handler if you want

> Also, why are you using the inferior scheduleSyncDelayedTask method? runTask is a much more descriptive function.

no, it is not

> Why would you need this anyway? I'm using this: [whatever]

works only when teleporting player to another world, look at CraftPlayer#teleport

**Comment by EdGruberman** [comment]
You should be setting the world the player is already set to respawn in, not assuming the default and forcing developers to change in the event.

If you aren't willing to address alternatives and justify why this PR is better (205 handler) it's doubtful the team will want to look at your PR in any detail.

If this method still relies on a delayed task to be successful, the team won't accept it as proper API.

**Comment by ninja-** [comment]
> You should be setting the world the player is already set to respawn in, not assuming the default and forcing developers to change in the event.

No, I am not. I am not going to be your pain in the ass just like Multiverse is.

> If you aren't willing to address alternatives and justify why this PR is better (205 handler) it's doubtful the team will want to look at your PR in any detail.

It is better because it is proper API to respawn the player when dead.

> If this method still relies on a delayed task to be successful, the team won't accept it as proper API.

you can respawn player whenever you want, just make sure he is dead already

**Comment by EdGruberman** [comment]
What does Multiverse have to do with this PR?

Will this spawn a player in the world their spawn is set to or not?  If so, that should be documented in the breakdown section.

**Comment by ninja-** [comment]
> What does Multiverse have to do with this PR?

it doesn't respawn you in correct world unless you explicitly set it 

> Will this spawn a player in the world their spawn is set to or not? If so, that should be documented in the breakdown section.

he will respawn normal way just like he clicked the fucking respawn button. please stop making stupid arguments. and that's what PlayerRespawnEvent is for.

**Comment by ninja-** [comment]
> Will this spawn a player in the world their spawn is set to or not? If so, that should be documented in the breakdown section.

``` java
    /**
     * Clicks the motherfucking respawn button.
     */
    public void respawn();
```

**Comment by Wolvereness** [comment]
@ninja- https://github.com/Bukkit/Bukkit/pull/940#issuecomment-25951840 

> > Will this spawn a player in the world their spawn is set to or not? If so, that should be documented in the breakdown section.
> 
> ``` java
>     /**
>      * Clicks the motherfucking respawn button.
>      */
>     public void respawn();
> ```

We don't have to put up with belligerence.

**Comment by jessestricker** [comment]
And yes, my method does work @ninja-. I am using it that way with successfully teleporting the player.

**Comment by ninja-** [comment]
> And yes, my method does work @ninja-. I am using it that way with successfully teleporting the player.

.

> works only when teleporting player to another world, look at CraftPlayer#teleport

**Pull request closed without merging**
