### PR TITLE
-

### PR DESCRIPTION
**Pull request by bit2shift**

### CODE REVIEW

**Comment by RhvsW** [comment]
Good luck asking every contributor to switch to lgpl.

 /it wont happen

**Comment by dariusc93** [comment]
They don't have to be lawyers to know their right that is under GPL. @Wolvereness can't switch the license even if he wanted to because each person contributed to bukkit thus holding their rights to the code they commited

**Comment by t00thpick1** [comment]
Doesn't the fork you made to create this pr now have an improperly licensed version of bukkit?  I am pretty sure you cant do that.....

**Comment by nightpool** [comment]
@t00thpick1 is right, you can't do that.

**Comment by daboross** [comment]
You realize that **all 106 contributors**, **including Wolverness**, will have to sign off on this before it can be legally merged, right?

**Comment by turt2live** [comment]
@daboross Actually, as per @t00thpick1's comment, all 106 contributors needed to sign off on it before it could be opened as a PR.

**Comment by daboross** [comment]
@turt2live, ah, yea. Just saying they also have to sign off for it to be merged as well.

**Comment by nightpool** [comment]
To give you some scope for this, Bukkit has 106 contributors. CraftBukkit indubitably has more. Some of them haven't been heard from in years, and some of them (myself included) will object to this change on ideological grounds.

**Comment by t00thpick1** [comment]
@turt2live. I thought we all have to sign off on it even just for him to make the commit on his public fork.

**Comment by turt2live** [comment]
@t00thpick1 that's what I meant to say :P But yes. 

@bit2shift I suggest you close this PR and remove the commit from your repo before someone decides to do it for you.

**Pull request closed without merging**
