### PR TITLE
Case-insensitive version command (BUKKIT-2383)

### PR DESCRIPTION
**Pull request by EdGruberman**
[BUKKIT-2383](https://bukkit.atlassian.net/browse/BUKKIT-2383)

### CODE REVIEW

**Comment by Wolvereness** [comment]
This falls over when two plugins share the same name but different case (possible, and should be addressed). Unless I'm missing something?

**Comment by EdGruberman** [comment]
I'm not sure what you mean by "falls over"?

This PR will first attempt to find a case-sensitive match as specified for the command argument.  If it doesn't find an case-sensitive match it then returns the first case-insensitive match it finds.

Pretty non-deterministic (depending on exactly how PluginManager.getPlugins() orders results) but a user could simply re-issue the command if they find the results did not match the plugin they initially expected but with proper case instead.

**Comment by Wolvereness** [comment]
Load order determines the getPlugins order. By falling over, I imply that it doesn't actually find case insensitive matches, it only finds the first.

**Comment by jrtc27** [comment]
I'm failing to see what is wrong with this behaviour - the order of getPlugins only affects which of the plugins it chooses _when there is no exact case match_, no?

**Comment by EdGruberman** [comment]
@Wolvereness Please take a look at the last commit I just added.  It leverages the plugin name formatting logic in PluginsCommand to standardize a matching plugin list.  This helps clarify what is happening when more than one plugin might match.  Is this something like what you are inferring you'd prefer?

**Comment by EdGruberman** [comment]
Example Usage

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/Bukkit/commit/c8dc8e682e1fa241d9d9808b525801801a3c2729

**Pull request closed without merging**
