### PR TITLE
Updated TeleportCommand.java to use final static public members rather than magic numbers

### PR DESCRIPTION
**Pull request by samoatesgames**
Added World.WORLD_SIZE static member, specifying the maximum size of a world.

Added VanillaCommand.INVALID_DOUBLE static member, specifying an invalid value for a double was entered into a command.

Updated TeleportCommand.java to use the new public static members.

### CODE REVIEW

**Comment by LB--** [comment]
I don't think a name like `WORLD_SIZE` makes much sense; what about `WORLD_MAX_COORD` and `WORLD_MIN_COORD`?

The same goes for `INVALID_DOUBLE` - name name is unituitive. What about `INVALID_COORD`?

**Comment by samoatesgames** [comment]
I originally had it as INVALID_COORD, but that felt wrong, as technically it is set when the parsing of a double fails a try/catch.

And the reason for WORLD_SIZE was, it can be use as -WORLD_SIZE -> WORLD_SIZE, rather than having to members, one positive and one negative (saves 8 bytes in memory! woohoo).

In saying that WORLD_SIZE does seem a little ambiguous.

**Comment by LB--** [comment]
Maybe `WORLD_RADIUS`?

**Comment by samoatesgames** [comment]
radius implies a circle? and the world size is a square?

**Comment by LB--** [comment]
Size implies a coordinate pair? And this is being used as the 1D distance from the origin?

I couldn't think of what else to use...

**Comment by samoatesgames** [comment]
WORLD_LIMIT feels like the best suggestion so far.

**Comment by spaceemotion** [comment]
+1 for limit
 size means for me the current map size, not the max/min available size

**Comment by samoatesgames** [comment]
https://github.com/samoatesgames/Bukkit/commit/2ad116839fead25aad24a189a1e7ac0c62019d19

Not sure if I can update this pull request (I'm a SVN user at heart not a Git User :P)
or do I need to make a new pull request with both revisions?

**Comment by ammaraskar** [comment]
Nope, you can do it right here in this pull request. Just squash those 2 commits down to 1.
See this guide on how to squash down commits http://git-scm.com/book/en/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/Bukkit/commit/bacc2e3596c220d0a8daae40d9b3a04342964725

**Pull request closed without merging**
