### PR TITLE
Option to load plugins from the classpath.

### PR DESCRIPTION
**Pull request by stephank**
This pull request has a matching CraftBukkit pull request, with more explanation:
https://github.com/Bukkit/CraftBukkit/pull/68

One API addition, and one minor API change is introduced. (A void-returning function now returns a value. I'm not sure if that also breaks ABI, and if that'd be a concern.)

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Interesting. I'll go over this in depth later.

**Comment by EvilSeph** [comment]
Ticket reopened because GitHub ate our pull requests.

**Comment by zml2008** [comment]
I like this concept. This also allows unit tests to be done more easily for things that need a Plugin to work correctly. I think 9 months minus two days has been long enough for @Dinnerbone to go over this in depth too.

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
