### PR TITLE
[B] Sort plugins by name in plugins command. Adds BUKKIT-5629

### PR DESCRIPTION
**Pull request by cybertiger**

### CODE REVIEW

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

Isn't this purely aesthetic?

Associated ticket is [closed](https://bukkit.atlassian.net/browse/BUKKIT-5629?focusedCommentId=30533&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30533).

**Comment by cybertiger** [comment]
Yes, this is purely aesthetic.

**Comment by rioricorick** [comment]
Hello. It is the case that aesthetic changes can not even be considered? I have noticed in the past when getting a list of mods that it would be great if they were ordered. Some mod packs I have used have over 100 mods, and it's just not worth looking for a mod in an unordered list. I have not made any commits yet, and want to be sure I understand.

Here's what I see from where I sit:
The change does fit with Bukkit's goals.
It does not result in unexpected behavior.
It does not expose an issue or vulnerability when operating within the Vanilla environment.
The change is reasonably supportable and maintainable, and is indeed future proof.
The word "aesthetic" is not even mentioned on the "contributing" page.

Just help me to understand why something like this is not able to be implemented.
I mean, thinking about it, correcting a misspelled word in a plugin is purely aesthetic as well, but I hope something like that would be done.

Hey thanks for your help!

**Comment by rioricorick** [comment]
OK I wanted to get it and I certainly do now. Thanks I appreciate it!

**Comment by Wolvereness** [comment]
@rioricorick https://github.com/Bukkit/Bukkit/pull/1067#issuecomment-44099738

> It is the case that aesthetic changes can not even be considered?

No, aesthetic changes are awesome. However, _justifying_ and aesthetic change is far harder because it can both usually be done with a plugin and carries a lot less weight in comparison to non-aesthetic ramifications.

For example, if your aesthetic change actually breaks plugins (excluding some horrendous uses of the API, like relying on `toString()` output), it almost certainly will get denied.

On the other side of the spectrum, fixing a misspelled word in an output message is very likely to get accepted, assuming it's not something like changing _color_ to _colour_.

**Pull request closed without merging**
