### PR TITLE
added default MaterialData class to MAP

### PR DESCRIPTION
**Pull request by sunkid**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Another MaterialData-related thing is the damage value for shears (238 according to the wiki).

Also, is the wiki wrong on the fishing rod's damage being 64? Because Bukkit says it's 32, and it's the only item with a discrepancy of more than 1 with the wiki.

**Comment by CelticMinstrel** [comment]
Also, some unstackable items don't seem to have this property noted in the Material enum (milk bucket, both fish, beds).

**Comment by CelticMinstrel** [comment]
Never mind, I made my own pull request for these: https://github.com/Bukkit/Bukkit/pull/293

**Comment by sunkid** [comment]
Thanks Celtic! Work has caught up with me these past weeks and I have not been able to look at these.

**Comment by sunkid** [comment]
Closed in favor of https://github.com/Bukkit/Bukkit/pull/293

**Pull request closed without merging**
