### PR TITLE
Added punctuation to comments.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by TheMolkaPL** [comment]
Use [Bukkit-JavaDoc](https://github.com/Bukkit/Bukkit-JavaDoc) repo to contribute to javadocs.
Also read [contributing](https://github.com/Bukkit/Bukkit-JavaDoc/blob/master/CONTRIBUTING.md) file there.

**Comment by Black-Hole** [comment]
Bukkit is maintained now by Spigot. The issue tracker is here: https://hub.spigotmc.org/jira/secure/Dashboard.jspa

**Comment by mbax** [comment]
Bukkit is _forked_ (not maintained) by Spigot, and **many others**. That list also includes [Glowstone](https://github.com/glowstonemc), a popular fork that distributes a server that hasn't dealt with legal trouble.

**Comment by EnderBrine101** [comment]
<code>Hi</code>

**Comment by brandonsutton12** [comment]
Umm. Hi

**Pull request closed without merging**
