### PR TITLE
Ban methods in Player and Server

### PR DESCRIPTION
**Pull request by CruzBishop**
Added two API methods (banPlayer and banPlayerIP) in both the Player and Server classes

CraftBukkit implementation: https://github.com/Bukkit/CraftBukkit/pull/444

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Oh nice, I wanted something for this at one point.

Additional note: Since /ban-ip takes an IP and not a player, why not add a banIP method to the Server interface as well? Also, since the string message is optional, what about a version of both that takes no argument?

**Comment by CruzBishop** [comment]
Sure thing, CelticMinstrel! :)

**Comment by lahwran** [comment]
does this really belong inside bukkit? plugins should do this by denying a login event, yes?

**Comment by CruzBishop** [comment]
I guess, but this method implements functionality that is already inside the MineCraft server - It just wasn't in Bukkit's API

**Comment by lahwran** [comment]
ah. I suppose that makes sense.

**Comment by CruzBishop** [comment]
Closing this because @Dinnerbone seems to be implementing IP bans and bans at the moment

**Comment by Dinnerbone** [comment]
Yes I am! Sorry :(

**Comment by CruzBishop** [comment]
Hey, I'm happy! :D I can finally start writing some plugins that include bans :)

**Pull request closed without merging**
