### PR TITLE
There is no silver wool, only light gray.

### PR DESCRIPTION
**Pull request by rrama**
Dono who decided it was silver, but it took me ages to realise that my code wasn't working. (I was using GRAY when I should have used "SILVER").

### CODE REVIEW

**Comment by jrtc27** [comment]
Unnecessary breaking change. By all means suggest a change to the JavaDocs, but not the enum itself.

**Comment by LB--** [comment]
Can't you just add GRAY and keep SILVER?

**Comment by Wolvereness** [comment]
Breaks without proper justification are not going to get pulled. Backward compatibility is more important than naming convention, unless the name specifically means the opposite or something completely different than what it actually does.

**Comment by rrama** [comment]
So should I just change the JavaDocs to say it's actually light gray wool, so people don't get confused like myself?

**Pull request closed without merging**
