### PR TITLE
Added a Metadata framework for Player.

### PR DESCRIPTION
**Pull request by cyberdudedk**
Consists of 3 classes: Metadata, MetadataGroup, MetadataNode

I tried implementing a Metadata framework that allows plugins to add additional metadata to a Player.
This can be used by e.g Permission Managers to assign a "group", "prefix" or similar additional data to the player.

Another plugin can then get this metadata easily without depending on a specific Permission Manager.
If a unofficial unwritten agreement is that group names will be assigned to a Metadata named "group" every plugin can use this information.

Every plugin can assign a metadata key/value, when a plugin assigns the same key/value again the value is overwriting the old value, this a plugin can only assign 1 value to a key.
HOWEVER I've implemented that each plugin can assign a key/value pair with the same key, it will just be added to a internal list/hashmap.

When asking for the Metadata, a list of metadata will be returned (if only 1 value is present only 1 value will be in the list), if multiple plugins have added metadata to the same key, e.g. "group", then the list will contain all the "group" metadata assigned by the plugins.
Plugins can then decide whether to just use one of the value or generate a delimited joined string of the values. E.g multiple groups could be joined to form "Group1/Group2/Group3" if 3 different plugins have assigned 3 different groups.
More work on this is probably need as the nodes are contained in a HashMap and will be returned in no particular order (Hashed order). Something like a level/priority property or FIFO queue would probably be needed, TreeMap?.

A metadata assigned by a specific plugin can also be requested either by the Plugin instance or by plugin name.

I am only using groups as an example because many people can relate to this, but there are MANY more uses of this.

I was thinking whether it would be useful to move this "up the tree", so instead of just allowing metadata on Player, move it to HumanEntity or maybe even all the way up to Entity allow metadata on ALL entities. But I'd like to take this discussion first.

I am not sure my implementation is absolutely perfect, but I'm hoping for some response and a little discussion about this subject, hopefully this could catch on. It would probably also need access methods such as getString, getBoolean, getInt and the likes. Currently it is only implemented as getValue, which returns a object.

Setting a Metadata example:
player.setMetadata(plugin, "key", "value");

Getting Metadata examples (4 examples, so BukkitDev paste'd it):
http://dev.bukkit.org/paste/4153/

Forum thread discussing the matter about Permissions/Metadata: 
http://forums.bukkit.org/threads/idea-design-a-better-permissions-plugin.42131/

Corresponding CraftBukkit Pull Request: 
https://github.com/Bukkit/CraftBukkit/pull/517

### CODE REVIEW

**Comment by maker-dude** [comment]
This is a great idea! 
I would love to see this merged in and refined to be in a RB

**Comment by ZachBora** [comment]
Sounds interesting up to now. +1

**Comment by RichardRobertson** [comment]
+1 for me too. Can't say I'll use it any time soon, but I like the idea.

**Comment by ZachBora** [comment]
I have a plugin called PlayerStats in which I had to declare a new class with player properties. With metatags the code would be much simpler and could be used by other plugins. Example : muted player

**Comment by Evenprime** [comment]
+1 simply for it promising an end to the abuse of permissions for storing such metadata. Even if this version doesn't get merged, at least that should be a good base for discussion on what should be made different.

**Comment by dredhorse** [comment]
sigh so simple... a lot less code than the api we are coding..

if you would move it up to entity you would be able to for example name a wolf etc.. and I guess the thread is in the bukkit+ forum..

getBoolean would be a must... for example for status information like afk etc.
getString also = PreFix / SufFix
Int, double etc could be done by converting a string, but I agree an own method would be better
I would really like to see something like this being implemented in bukkit... or if not possible in a plugin..

so if your pull doesn't get accepted perhaps you want to help us..

**Comment by ZachBora** [comment]
@dredhorse Yes I would put this on entity level

**Comment by Afforess** [comment]
Yes please.

One tiny suggestion, allow plugins to set both transitory metadata (data that disappears after server restart, like you have it now) and persistent metadata (saved to yml file associated with entity unique id?)

Also, having this on all entities would indeed be awesome.

Otherwise, +100.

**Comment by ZachBora** [comment]
@Afforess Why does it have to be a yml?

**Comment by Afforess** [comment]
> @Afforess Why does it have to be a yml?

I didn't say it had to be (hence the question mark at the end of the suggestion...)

**Comment by ZachBora** [comment]
@Afforess since would be something automatically loaded at each server start/entity create and unloaded at each server stop/entity remove, and since we can create fake Entitiy/Player objects, I don't see a point in making the file human readable. I would just save the object as is with ObjectOutputStream. I don't have the speed numbers but I would guess it's faster than any human readable type of files.

**Comment by mbax** [comment]
Saying that plugins should agree on "group" is a bad idea. Immediately you're excluding the idea of multi-group situations.

**Comment by maker-dude** [comment]
@mbax the solution handles multi group by adding anything that is called 'group' gets added to the group list. So if somebody is in multiple groups, you just add 'group' multiple times.

And the issue of group priority has already been raised.

**Comment by dredhorse** [comment]
@ZachBora  yml would still be nice as it would allow the average admin to edit the file.. e.g. for prefixes.. (pseudoyml)

Groups:
    SuperGroup:
       Prefix: My Super Prefix

if you only make it persistant you would need ingame commands for that... take a look at pex and how many people have problems with it... sigh...

**Comment by ZachBora** [comment]
@mbax You can save in the metadata "groups" a list of groups ordered. Metadata doesn't have to be a string, int, byte, etc. it can be complex objects.

**Comment by RichardRobertson** [comment]
I agree on changing to Object. Good programmers always check the type of an object with an unknown source using instanceof before attempting to cast, so it shouldn't be a problem.

Also +1 to non-human-readable metadata persistence. Server admins shouldn't be able to screw with internal data unless they know what they are doing so hard they could break a rock with a hammer made out of that knowledge.

**Comment by ZachBora** [comment]
@dredhorse I don't use PEX I wouldn't know... I still use 2.7.4 because it works fine up to now, but I hate modifying the file by hand (theres about 7000 lines).

I guess there could be situations where you need to modify data by hand, but this is just like a player inventory. You can't modify inventory outside game unless you use a dat editor.

**Comment by ZachBora** [comment]
@cyberdudedk For a sorted map I suggest TreeMap.

**Comment by Afforess** [comment]
I'd suggest using Serializable instead of Object, so people can write more specific serialization implementations if needed. It's a Java interface:

http://download.oracle.com/javase/1.5.0/docs/api/java/io/Serializable.html

**Comment by cyberdudedk** [comment]
Wow, this got more response quicker than I thought it would.

@dredhorse
Yes, it's so much simpler.
I am currently keeping it on Player until I hear more from Dinnerbone and talk with him about it.
I'm not sure where the Bukkit Team's stance is on this Metadata subject, and I'm a bit afraid that if I loosen the knot a bit too much they might be less likely to approve because it would turn out to not go well in line with some of their ideas. I'm merely trying to open the conversation at first :)

@Afforess
Thank you :).
I thought about persistence, but I'm not really sure. Is anything in Bukkit persistent at all? I'm sure if I implemented persistence this would not go very well the team.
Metadata on all entities would sure allow a lot greater usage, and  I love for it to be approved on full entity.

@mbax
That is infact correct. This is also merely an attempt at going somewhere ;)

@jblaske
mbax is in fact correct about this one. I especially wrote this so 1 plugin can only have 1 value per key. So 1 plugin can not add multiple "groups" for example, but more plugins can add more "groups", this is done so plugins will not overwrite each other values, but more along the lines of coexisting in a shared environment (metadata).
If it was found to be needed it would of course be very possible to support 1 plugin to add multiple of the same key, just stacking it. But I thought long and hard about this and found the current solution to be both flexible while at the same time structured and easy to work with.

@dredhorse (about editing persistent data)
I don't agree on this, because frankly a admin should not be touching this data. And binary storage of the objects will allow to store ANYTHING instead of only those objects that support XML/YML serialization. This metadata is supposed to be set by plugins, not edited by admins, the data that is being set is based on what other plugins set it too, and they should base that on some config. If you ask me at least ;).

@Zachbora and RichardRobertson
Yeah, it was supposed to be Object, I worked with string in the beginning and changed to object but missed 1 spot ;)
Will fix at some point ;)

**Comment by dredhorse** [comment]
hmm... is it possible that other plugins read metadata from other plugins?
can other plugins also change metadata from other plugins?
is there an option to have ONE instance of a "field"... eg. afk?

and if I understand you correctly @cyberdudedk you only want to have this as a repository or better directory of schema data but without a user facing component, except perhaps a command line.. 

so if you go for some like storing a chat prefix or a specifc info like NumberOfPrivateWarps=3 how would you do that? 

from the plugin which does the warping? but how does that plugin now this number? Would it need to define Groupx=NumberOfPrivateWarps=3? But how would we know who is member of Groupx?

**Comment by ZachBora** [comment]
@dredhorse I also thought of something similar, like with iConomy the entity could have an account but lots of those plugin handle bank accounts and shared accounts which couldn't be placed in such metadata, unless you create fake entities... which isn't a good idea in my opinion.

**Comment by cyberdudedk** [comment]
@dredhorse
Yes, it's possible to read the metadata from other plugins. In fact this is the aim of this pull request. Creating a common "bucket" where all plugins can read and put information into. It is written with the concept that plugins shouldn't need to reference a particular plugin or write specific code for each and every single plugin that provides the same data (such as bPermission, BukkitPermission, Permissions, PEX) all these plugin could add group and prefix and whatever else they have into the collective shared metadata per player. Any plugin that needs to know the group or prefix will just get it from this metadata.

It is currently possible to change metadata from other plugins, because you can just parse and instance of the plugin to the function. This is however not intended use, and I have thought about other ways of implementing this. Such as moving the set/get to the Plugin/JavaPlugin class, and requiring the Entity to parsed instead, then we can ensure that plugins can only set/add in their own name, thus not being able to overwrite the metadata set by other plugins.
Well, yeah I can see the usecase for single instance fields also. I¨m not really sure how that would go well together with this. The idea is that plugins should coexist not work against each other. This means that if two plugins wants to add "afk" information there will be created 2 fields of "afk" values. It is then up to the plugin to decide what it wants to do with this information, but probably more thoughts might have to be into this. If I allowed single instance, these two plugins would start working against each other and would just make a mess instead ;).

That is correct. This is only intended for use as an API between plugins. If you want to you can call it an attempt at creating a loose reference and data sharing API.

The plugin that maintains the number of privatewarps, just set the data: player.setMetadata("privatewarps",3);
Another plugin can then use this information by calling player,getMetadata("privatewarps");
A couple days later another plugin appears on the forums that also counts privatewarps, it also just calls player.setMetadata("privatewarps")
No the plugin getting the metadata suddenly has access to two values of privatewarps, what it does with those values is up to the plugin, whether to add them together or prefer the one over the other.

It is possible to retrieve data stored by a particular plugin if desired but this is of course not intended purpose of this. This just adds the possibility. The value MetadataNodes that is returned when getting a metadata also contains the name and instance of plugin that assigned it, so plugins can take actions and decide based on the plugin that assigned it to use it or not use it or do something specific with it.

You would not need to define GroupX or anything. Groups was just an example of what could be stored as Metadata. This doesn't add any particular group support or anything of that sorts, it allows plugin developers a common ground to exchange information such as what group the user belongs to or whatever.

**Comment by dredhorse** [comment]
ok, going to bed now but we should probably talk via mumble / ts / skype...

concerning afk... the single instance WOULD be helpfull if you have one plugin setting for example afk to true.. and now other plugins can look at the status.. the other plugins don't need to know which plugin did set the status..

but if I read your comments correctly all of your "field" are multivalued so you get back always pluginname:afk=true, so that if you have 2 plugins setting afk you would have 2 entries..plugin1:afk=true, plugin2:afk=false

but how does a plugin needing the afk information know which one of the 2 values is now the correct one? especially without knowing which plugins are installed setting the afk information..

I hope I explained the use case I want to see covered in a way it make sense..

**Comment by cyberdudedk** [comment]
@ZachBora
We could probably create some kind of "one instance" metadata, either besides this, or add support for assigning a metadata as single instance.
The framework would have to be expanded for this sort of thing. It could also feature expanded MetadataInteger classes that allows incrementation, subtraction, multiplications and such. It could however also be handled by getting the data and then readding the data. But this kind of thing has to be worked upon in steps, and discussed a bit a more, since it allows for much broader range of errors and mistakes by plugin developers, if they have share the same metadata. Also because the data is not Type safe, one plugin might add a integer, another plugin reads this integer and adds back a string, the first plugin then reads the data again expecting a integer, bang! So a fully shared single instance metadata will need additional tools and require a lot more attention to work with by the plugin developers. Of course the case is the same in the current implementation, but it is more "closed" and structured and is thus easier for plugin developers to handle.
Making it TOO large and complex also means more plugin developers fail to use it correctly creating more problems.

Because this is only a loose (in the sense of not having a hard reference) it is also prone to error when used incorrectly.

This is not a "end all problems" solution, and without using hard referencing (referencing the plugins, or using a API/Interface existing in bukkit) this will always be error prone when used incorrectly, thus I believe "sometimes less is more".

But we'll see when Dinnerbone or Grum gets a chance to take a look, and we'll see what they are up for and what they are not up for.

**Comment by cyberdudedk** [comment]
@dredhorse
You are presenting a very good question, that I can't really answer. Basically the same goes in single instance environment:
Plugin1 assigns afk=true
Plugin2 then overwrites and assigns afk=false

Which of those values is correct, it all comes down to which plugin runs first? Which runs last? What should the afk value really be here? If they both try to assign the value within the same tick, both values might be correct, it all depends on which plugin triggers first.
This is why I wanted to create per plugin storage, so the plugin extracting the data has access to the values set, the plugin itself can then decide which of those two values it should use/count on. Currently the only thing it can really decide this on is based on the Plugin name.
This is where there needs more work. Currently it's a hashmap thus the order you get them out should, from a user/plugin developers point of view, be regarded as Random.
Maybe it could be a sorted map, where always the value updated last is the first item. So you can use the newest item if you desire.
It could just be a sorted map where the first item that gets added has the first position.
It could implement a priority system.
It could implement some other idea. I don't have the answer for this yet. As I wrote in the description it's not really fully finished yet, it's merely a beginning.

But you are presenting a valid question and valid concern that would require more attention and work ;)

**Comment by ZachBora** [comment]
@dredhorse that's why we need to save these values. This way, both plugins can use the same data and not save the data themselves so on the next load they don't fight for the current value. Bukkit itself will save and load that data, the plugins will simply verify if the data exists, and if it doesn't it creates it.

But! If we let bukkit save the data, we'll need some way to remove old data from unused plugins...

**Comment by tips48** [comment]
Love it!

**Comment by cyberdudedk** [comment]
I think I want to send the attention to @rmichela's attempt:
https://github.com/Bukkit/Bukkit/pull/393
It implements at lot of the desired features this is missing.
And a lot of nice concepts/features.

**Comment by Dinnerbone** [comment]
Okay here's the deal.

It's a cool idea. It's a good concept and we've been after it for a while. However, I've some gripes:
- Code style. Minor gripe, but we can't pull without it being consistent.
- This should probably be moved down to Entity, and perhaps remove the methods opting for an `x.metadata().set(plugin, key, value)`, `x.metadata().get(key)` etc. It will allow the class to be reused more often and more easily.
- I'm not too sure the naming of the classes is good enough, or the javadoc is too lacking. I'm still trying to figure out how groups and nodes fit together, it's not very intuitive.

I'll come back to a proper review when I have the time.

**Comment by cyberdudedk** [comment]
@Dinnerbone
Thank you for taking notice :)
This pull request was mainly an attempt to give this Metadata store some thought, and discussing it with other people, and you, getting some feedback on changes before it would be final.

But I believe this should be closed, since you also noticed @rmichela pull request, which is much better implemented and implements additional features that this doesn't. I stopped developing any further when his pull request appeared, and I'm highly endorsing his version of Metadata store.

**Pull request closed without merging**
