### PR TITLE
[B] Add enum for SmoothBrickType. Adds BUKKIT-3817

### PR DESCRIPTION
**Pull request by gmcferrin**
Leaky - https://bukkit.atlassian.net/browse/BUKKIT-3817

### CODE REVIEW

**Comment by gmcferrin** [comment]
Associated JIRA ticket - https://bukkit.atlassian.net/browse/BUKKIT-1599

**Comment by gmcferrin** [comment]
If you're not gonna pull this, it's fine, but you could at least let me know...

**Comment by Wolvereness** [comment]
This needs usage.

**Comment by gmcferrin** [comment]
What do you mean by "needs usage", so I can fix it?

**Comment by gravitylow** [comment]
Add a description and define your use-case, how this improves things or where it would be used, etc.

**Comment by Wolvereness** [comment]
This adds an enum that is unused. There is nowhere that this new code is referenced. It's orphaned. Also, link to jira tickets for your PRs.

**Comment by gmcferrin** [comment]
Ah, makes sense. And the JIRA ticket is linked in the 2nd comment.

**Comment by gmcferrin** [comment]
Alright, usage added.

**Comment by Wolvereness** [comment]
This is now a breaking change...

**Comment by gmcferrin** [comment]
Ack. I'll try to fix it so that it isn't.

**Comment by gmcferrin** [comment]
OK... having some issues making it non-breaking. Suggestions?

**Comment by riking** [comment]
Is this satisfied in the current version, or is it still relevant?

Also, needs a ticket

**Comment by gmcferrin** [comment]
Ticket is here - https://bukkit.atlassian.net/browse/BUKKIT-1599

Not sure if @Wolvereness is still correct on it being breaking & how that affects it. Has not been added as of yet, though.

**Comment by riking** [comment]
@gmcferrin It's breaking because you changed the inheritance from `TexturedMaterial` to `MaterialData`. Things that depend on that inheritance will break.

**Comment by natemort** [comment]
Textured is sufficient at the moment. By the time this matters (new blocks added to it) it's going to be irrelevant because of the new ID system.

**Pull request closed without merging**
