### PR TITLE
Added feedback for JavaPlugin (BUKKIT-1788)

### PR DESCRIPTION
**Pull request by SagaciousZed**
Added an UninitilizedPluginException and made JavaPlugin throw it for fields that are initialized by the initialize method.
Addresses BUKKIT-1788.

Leaky: https://bukkit.atlassian.net/browse/BUKKIT-1788

EDIT: fixed some typos

### CODE REVIEW

**Comment by obnoxint** [comment]
Multiple typos in commit message and inconsistencies in Javadoc. The exceptions thrown are unchecked, therefore a simple null check or

``` java
if (plugin.isInitialized())
```

does a better job.

**Comment by SagaciousZed** [comment]
The intention here is to give better feedback when a plugin author calls getConfig() to initialize and assign a instance variable then proceed to wonder why it is null.

**Comment by Wolvereness** [comment]
Obsolete as of a recent commit.

**Comment by SagaciousZed** [comment]
Recent commit was reverted. Should be reopened like the ticket

**Pull request closed without merging**
