### PR TITLE
Added CHUNK_GENERATED

### PR DESCRIPTION
**Pull request by FrozenCow**
I've removed CHUNK_GENERATION because it wasn't used anywhere and I found the name rather confusing.

CraftBukkit: https://github.com/Bukkit/CraftBukkit/pull/172

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Incomplete commit. Missing a class.

**Comment by FrozenCow** [comment]
Sorry! Damn I feel stupid. It's fixed now.

**Comment by Dinnerbone** [comment]
Ah. If that's just it then we use ChunkLoadEvent :p

**Comment by FrozenCow** [comment]
Np ;). In the end it might be nice to see ChunkLoadEvent being renamed to ChunkEvent... but for the moment using ChunkLoadEvent is fine.

**Comment by EvilSeph** [comment]
Closed as per above discussion.

**Comment by FrozenCow** [comment]
Wait a minute... dinnerbone responded positive towards integrating this in the above discussion. It isn't pulled yet l, so closing because of the discussion is illogical :s.

**Comment by EvilSeph** [comment]
What I got from this discussion is that we should use ChunkLoadEvent instead. Am I mistaken?

**Comment by FrozenCow** [comment]
Yes, dinnerbone only mentions to use chunkloadevent instead of chunkgeneratedevent. That's just sprinkles/naming. The discussion isn't about an alternative for the functionality.
This request is a simple addition so that plugins can know when and what chunks are generated. It should be easily merged and I know a bunch of developers who'd like functionality like this. I think an event like this is mandatory. Since plugins will else need to periodically go by -all- chunks to see if there are new ones. (Like I'm doing with fullrender in dynmap)

**Comment by EvilSeph** [comment]
I'll let Dinner handle this then, he can reopen it when he's looked at it.

**Pull request closed without merging**
