### PR TITLE
[B] Added Material Names Adds BUKKIT-4659

### PR DESCRIPTION
**Pull request by LlemonDuck**
The Issue:
toString() in Material returns the enum constant definition. It is unfriendly to users.

PR Breakdown:
This PR create

CraftBukkit PR:
Bukkit/Bukkit#Not sure?

JIRA Ticket:
https://bukkit.atlassian.net/browse/BUKKIT-4659

### CODE REVIEW

**Comment by gmcferrin** [comment]
Please follow the Contributing Guidelines. Also, I'm pretty much going to guarantee this won't get pulled as it currently stands. It should use the names from NMS, not hard coded names you've created.

**Comment by turt2live** [comment]
There are also plenty of formatting issues with the diff; most of them appear to be indentation changes and possibly converting spaces to tabs.

I personally think this would be better as a communal library rather than hardcoded into Bukkit because other plugins (including mine) already map "player friendly" names to "Material Names". This PR also does not add a way to get the material for a player-friendly name (ie: Material.fromString("Block of Iron")). On top of that this PR's hardcoded values may not agree with the player using them ("Block of Iron" versus "Iron Block").

**Comment by Wolvereness** [comment]
https://bukkit.atlassian.net/browse/BUKKIT-4659?focusedCommentId=26127&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26127

In addition to what @turt2live said.

**Comment by LlemonDuck** [comment]
Okay. Thanks, guys.

**Pull request closed without merging**
