### PR TITLE
Adds a BlockState for Skulls

### PR DESCRIPTION
**Pull request by meiskam**
Allows for manipulation of Skull blocks placed on the map.

Corresponding CraftBukkit PR: Bukkit/CraftBukkit#961

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Random additional note... maybe SkullType should be out in org.bukkit? I say this because at some point it'll probably be used by a MaterialData class as well...

**Comment by meiskam** [comment]
@CelticMinstrel Changed, thanks for the input, I really didn't know where it belonged

**Comment by CelticMinstrel** [comment]
Well, it's where all other such enums are, such as TreeSpecies, CoalType, and so forth.

**Comment by EvilSeph** [comment]
Pulled, thanks!

**Pull request closed without merging**
