### PR TITLE
Added method to World to get entity with specified id

### PR DESCRIPTION
**Pull request by tomsik68**
Added method getEntity(int entityId) which returns an entity from world with specified id.
Useful for saving entities as numbers - their IDs.
CraftBukkit PR: https://github.com/Bukkit/CraftBukkit/pull/813

### CODE REVIEW

**Comment by md-5** [comment]
Showing 1 changed file with 1,004 additions and 999 deletions. 

Maybe check your diff / learn to use git.

Same for https://github.com/Bukkit/CraftBukkit/pull/813

**Comment by tomsik68** [comment]
Sorry, I'm pretty new to git. I'll check my settings and create another commit.

**Comment by jrtc27** [comment]
Still broken

**Comment by khoek** [comment]
You're going to want to use git rebase to squash your second commit into the first. Same goes with the other pull.

**Comment by feildmaster** [comment]
See https://github.com/Bukkit/CraftBukkit/pull/813

**Pull request closed without merging**
