### PR TITLE
Fixed getMidpoint modifying the Vector object.

### PR DESCRIPTION
**Pull request by TomyLobo**
I don't think this was intended.

### CODE REVIEW

**Comment by TomyLobo** [comment]
if you want a test:

a = b.getMidpoint(c);
System.out.println(a);
a = b.getMidpoint(c);
System.out.println(a);

declare a, pick non-equal Vectors b and c
both prints should print the same but don't

**Comment by jrtc27** [comment]
Yes - simple request to pull. IMHO these sorts of pull requests are the highest priority - they fix trivial bugs that really shouldn't be there.

**Comment by TomyLobo** [comment]
Now someone just needs to poke Grum with this.
According to my information, he's the one responsible for this piece of code.

**Comment by grum** [comment]
Handled.

**Comment by TomyLobo** [comment]
grum said:

> You need to get your source of 'information right'. Learn to use git blame, in either case handled.

oh I know sk89q wrote this, but he mysteriously vanished from the committers list after you reverted one of his commits
=> you're responsible for his stuff now

**Pull request closed without merging**
