### PR TITLE
ServerCommandEvent setup (leaky #528)

### PR DESCRIPTION
**Pull request by Dutchy-**
See: http://leaky.bukkit.org/issues/528

Since I did not get any response I decided to implement it in the easiest way possible, using the already existing (seemingly unused) ServerCommandEvent.

If you'd rather see this in a similar way to the current onCommand (or perhaps server commands should also trigger onCommand) please give me suggestions on how it should be implemented.

There is a corresponding CraftBukkit pull:
https://github.com/Bukkit/CraftBukkit/pull/182

### CODE REVIEW

**Comment by Raphfrk** [comment]
Normally, what you do is submit both pulls and then link them to each other.  You only need to have comments for one of them.

**Comment by Dutchy-** [comment]
How would I do this linking? I don't see this option anywhere...

**Comment by Raphfrk** [comment]
I mean that you just submit both pulls and add a link between the 2 in the comments.

Something like:

There is a corresponding Bukkit pull:
https://github.com/Bukkit/Bukkit/pull/148

That way they can pull both pulls at the same time.

**Comment by Dutchy-** [comment]
Alright, done that!

There is a corresponding CraftBukkit pull:
https://github.com/Bukkit/CraftBukkit/pull/182

**Comment by Dinnerbone** [comment]
What's the use-case on this?

**Comment by Dutchy-** [comment]
The commands you enter in the craftbukkit console are currently not monitored. I'd like to have a way to monitor these for my ServerIRC plugin (server events -> IRC relay). This pull adds an event interface for these commands.

**Comment by Dutchy-** [comment]
Closed as per discussion on IRC:

13:56 @Dinnerbone Do you want a way for people to call your plugin from the console?
13:57 @Dinnerbone Or are you logging commands and don't want to handle them?
13:57 < Dutchy> No, I'd like to monitor the commands
13:57 < Dutchy> so, logging yes
13:59 @Dinnerbone Okay, I'd rather another way to do this which I'm working on
14:00 < Dutchy> Alright, any way I can help with that?
14:01 @Dinnerbone Not really but thanks for trying :D

**Pull request closed without merging**
