### PR TITLE
Only use TravelAgent if supplied; BUKKIT-3466

### PR DESCRIPTION
**Pull request by EdGruberman**
If there is no TravelAgent assigned, it can not be used.

Bukkit/CraftBukkit#1000

### CODE REVIEW

**Comment by feildmaster** [comment]
Why is this checked in the event?

**Comment by md-5** [comment]
Because you can't use a null travel agent, so that fact that it is null is a reason why its not used. My reasoning anyway.

**Comment by EdGruberman** [comment]
@md-5 has it right.  And then I leverage that check to avoid a couple of null checks in CraftBukkit accordingly.  To be honest, it can go either place.  I just thought it made sense here to help anyone else avoid the double check of use and null also.

**Comment by feildmaster** [comment]
Guess that's fine with me.

**Comment by EdGruberman** [comment]
Just updated to remove the parenthesis.  Although,  I wonder why Bukkit doesn't use them more?  Java Code Conventions even encourage it: http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-137265.html#331

**Comment by natemort** [comment]
@feildmaster   Did you forget to close this?https://github.com/Bukkit/Bukkit/commit/7f87d99353f0dedf097cc85bcd017e1a5d581ea5

**Comment by EdGruberman** [comment]
Probably because I used "Addresses" instead of "Fixes".  Apparently if you use the latter it automatically associates it.  d0h!

**Comment by feildmaster** [comment]
No, I just forgot to close it.

**Pull request closed without merging**
