### PR TITLE
Add brewing stand interface

### PR DESCRIPTION
**Pull request by N3X15**
Adds an interface for accessing Brewing Stand TileEntities.  CraftBukkit counterpart pull is [CraftBukkit Pull #597](https://github.com/Bukkit/CraftBukkit/pull/597).

### CODE REVIEW

**Comment by N3X15** [comment]
I should note that my MInecart Mania maintenance fork relies on this.  It has been thoroughly tested and works.

**Comment by xZise** [comment]
Nice with as this allows me to automatically log the contents of brewing stands without doing any trick and simply rely on ContainerBlock implementation :)

Fabian

**Comment by md-5** [comment]
I'll probably just copy this into bleeding, but for one, @author tags are a no no.

**Comment by md-5** [comment]
http://git.io/FAJ4eg

Can be closed now.

**Comment by Dinnerbone** [comment]
Closed due to bleeding.

**Pull request closed without merging**
