### PR TITLE
Makes the world seed modifiable. Addresses BUKKIT-1793.

### PR DESCRIPTION
**Pull request by lexi-lambda**
This adds a `setSeed(long)` method to the `World` interface to allow plugins to modify a world's seed directly through the API.

Link to ticket: https://bukkit.atlassian.net/browse/BUKKIT-1793
Link to CraftBukkit pull request: https://github.com/Bukkit/CraftBukkit/pull/793

### CODE REVIEW

**Comment by Wolvereness** [comment]
The API to accomplish the use-case has nothing to do with changing the seed. If there is something you 'need' the seed changed for, then the API should be designed around the specific use-case.

**Comment by lexi-lambda** [comment]
Could you elaborate on why this is the wrong way to implement this? I cannot think of a way to better accomplish this than making a way to change the seed. Unless you think that a `world.randomizeSeed()` method would be better...?

**Comment by Wolvereness** [comment]
We need a use-case.

**Comment by gravitylow** [comment]
Personally I don't think you should ever need to change a worlds seed. The amount issues it would cause would be a bit catastrophic.

**Comment by lexi-lambda** [comment]
Here's my use case. I wanted to make a type of highly customized server that used the standard Minecraft world generator, but used BlockPopulators to add additional features to the map, creating a type of randomly-generated "arena". The problem was that I wanted it to be different each time. My solution was to randomize the seed and regenerate the arena chunks. This would create a new arena with completely different terrain.

However, while I was able to do this, I had to use reflection, and I feel like that shouldn't be necessary. If you can think of a better method of doing things, then you can give me such a suggestion, but otherwise, I think that this is a good idea.

**Comment by Wolvereness** [comment]
If that's the use-case, then specifying a seed to the chunk regeneration would be more appropriate. Problem is, chunk generation is unruly and can cause things to explode. Using a custom generator would fix that, and mean that the seed doesn't need to change.

**Comment by lexi-lambda** [comment]
Alright, I can try that instead. However, I don't believe that one can modify the vanilla chunk generator as the base of a custom generator, and since I still want the normal chunks, just with added features, I can't just make a custom generator. However, adding a seed parameter to `regenerateChunk()` might be an option.

**Pull request closed without merging**
