### PR TITLE
Fixes /me

### PR DESCRIPTION
**Pull request by feildmaster**
@dinnerbone

### CODE REVIEW

**Comment by wizjany** [comment]
now you have an extra " " in front...

**Comment by feildmaster** [comment]
You're not being serious are you?

Try doing /me test

"\* feildmastertest" comes up.

He got rid of the first space. This fixes it. :P

**Comment by jmurth1234** [comment]
Such originality

THIS IS A MUST ADD!

**Comment by Dinnerbone** [comment]
Thanks. Wasn't my fault, but fixed!

**Pull request closed without merging**
