### PR TITLE
Added method to check conflicting enchantments on an ItemStack.

### PR DESCRIPTION
**Pull request by gmcferrin**
Updated version of pull request from here: https://github.com/Bukkit/Bukkit/pull/561

### CODE REVIEW

**Comment by gmcferrin** [comment]
Anyone?

**Comment by gmcferrin** [comment]
If you're not gonna pull this, it's fine, but you could at least let me know...

**Comment by gmcferrin** [comment]
Moved check to ItemStack.java, at the request of @feildmaster and @Wolvereness

**Comment by feildmaster** [comment]
This needs a corresponding CB pr.. I'll probably make it.

Also, needs a ticket.

**Comment by riking** [comment]
Is this PR satisfied in the current version?

Also, needs a ticket.

**Comment by gmcferrin** [comment]
Ticket is here: https://bukkit.atlassian.net/browse/BUKKIT-1159

Not sure if Fieldmaster ever did the CB side of this, though.

**Comment by riking** [comment]
@gmcferrin I was talking about the ItemMeta changes, do those provide a way to check conflicting enchantments without touching NMS/OBC code?

**Comment by feildmaster** [comment]
Lets move this function to ItemMeta.. :smiley:

**Comment by gmcferrin** [comment]
Updated here: https://github.com/Bukkit/Bukkit/pull/807

**Pull request closed without merging**
