### PR TITLE
added ability to change drops in case of Entity death

### PR DESCRIPTION
**Pull request by sunkid**
This simply adds the ability to change what an entity drops after death.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
You can already set the drops. Replacing them entirely with this method will just encourage conflicts with plugins overwriting the drops set by another plugin.

**Comment by sunkid** [comment]
How can the drops be set for a player?

**Comment by Dinnerbone** [comment]
``` java
List<ItemStack> drops = event.getDrops();
drops.add(new ItemStack(Material.APPLE));
drops.addAll(someInternalListOfDrops);
for (ItemStack drop : drops) {
    if (drop.getType() == Material.SAND) {
        drop.setType(Material.GLASS);
    }
}
```

**Comment by sunkid** [comment]
Yeah, OK, well... _blush_

**Pull request closed without merging**
