### PR TITLE
Allow the player's name in PlayerPreLoginEvent to be changed.

### PR DESCRIPTION
**Pull request by zml2008**
Changed PlayerPreLoginEvent to allow plugins to set the real name of the player as it appears to the server and all other clients.

CraftBukkit pullrequest: https://github.com/Bukkit/CraftBukkit/pull/483

### CODE REVIEW

**Comment by pschichtel** [comment]
I think the name of a player should not be changed, because it is often used as an ID (eg permission plugins).
The display name exists to give players custom names

**Comment by zml2008** [comment]
Setting the display name of a player does not change the name above the
player's head. Changing the name of the player in PlayerPreLoginEvent does.
Changing the name here also allows for complete faking of another player,
for more easily testing permissions settings, etc.

**Comment by pschichtel** [comment]
Maybe is would be possible to set the name above the player to the displayname

**Comment by codename-B** [comment]
@quickwango if you can do it - please do! As far as I can tell the name above the player is the same one the server uses.

**Comment by EvilSeph** [comment]
The only time a player's name should be changed is through official means. If you don't own the account, you shouldn't be using the name. There is a reason why we only provide display name manipulation within the API.

**Pull request closed without merging**
