### PR TITLE
[B+C] Add setCritical and isCritical methods to Arrow.java, Adds BUKKIT-5113

### PR DESCRIPTION
**Pull request by Morphan1**
<b>The Issue:</b>

At the moment, the only way to create a "critical" arrow is by actually grabbing a bow and arrow, then drawing the string back all the way. There's no current method to force an arrow to become critical.

<b>Justification for this PR</b>

This pull request adds .setCritical(boolean critical) to arrows so you can force an arrow to be critical or not. It also adds a way to check if an arrow is already critical with .isCritical().

<b>PR Breakdown:</b>

By utilizing the .a(boolean flag) method in EntityArrow.java (from net/minecraft/server), the new .setCritical method provides a way to force a spawned-in arrow, or any arrow at all, to be "critical", which includes the particle effects and extra damage, as if you were using full force with a bow.

The new .isCritical method returns whether or not an arrow is already critical, by using EntityArrow.java's .f() method.

<b>Testing Results and Materials:</b>

I made a simple plugin, and it did exactly as expected. The compiled plugin and the source are provided here.
https://dl.dropboxusercontent.com/u/188921928/CriticalArrowTest.jar

When you use a bow to shoot a critical shot, the server announces that. You can also use /critarrow to shoot critical arrows.

<b>Relevant PR(s):</b>

CB-1291 - https://github.com/Bukkit/CraftBukkit/pull/1291

<b>JIRA Ticket:</b>

BUKKIT-5113 - https://bukkit.atlassian.net/browse/BUKKIT-5113

### CODE REVIEW

**Comment by turt2live** [comment]
I like this :)

Does this just add the effect or does it make the arrow critical in the sense of a "high powered" shot?

Edit: Just tested to find out. It shoots a critical "high powered" shot :)

**Comment by ryantheleach** [comment]
does it also add the effect?

**Comment by turt2live** [comment]
Yes

**Comment by Morphan1** [comment]
Yeah, it does everything a normal critical arrow would do as if a player shot it from a bow, from the effect to the damage.

**Comment by turt2live** [comment]
This no longer does the true damage of a critical arrow, it only does the effect. Can that be fixed?

[Testing resources (Google Drive)](https://drive.google.com/folderview?id=0B6JIYSBkLkAnSm1sTU13WFZjWlE&usp=sharing)

**Comment by Morphan1** [comment]
I can't seem to reproduce this...
It seems to still work for damage, and has no reason not to as far as I can see.

EDIT: Actually, I do see the problem. The speed is taken into account during damage, not the criticalness.
So all the a() method seems to do is set the effect, not the speed.

**Comment by Black-Hole** [comment]
t00thpick1 is working on this:
https://github.com/Bukkit/CraftBukkit-Bleeding/tree/t00thpick1/projectiles

**Comment by turt2live** [comment]
Handled by https://github.com/Bukkit/CraftBukkit/compare/452109e716...88d138fc43 - thanks for your contribution!

**Pull request closed without merging**
