### PR TITLE
[B] Corrected solid blocks in Material. Fixes BUKKIT-5671 & BUKKIT-5559

### PR DESCRIPTION
**Pull request by ghost**
isSolid() returns nonsolid blocks (WALL_SIGN, IRON_PLATE, GOLD_PLATE, WOOD_PLATE and STONE_PLATE) as being solid and doesn't include FLOWER_POT as being solid.

JIRA Tickets:
[BUKKIT-5671](https://bukkit.atlassian.net/browse/BUKKIT-5671)
[BUKKIT-5559](https://bukkit.atlassian.net/browse/BUKKIT-5559)

### CODE REVIEW

**Comment by turt2live** [comment]
Please review the [Contributing Guidelines](https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md).

**Comment by JeromSar** [comment]
@xa112 As I discovered, `WALL_SIGN`, `SIGN_POST`, `IRON_PLATE`, `GOLD_PLATE`, `WOOD_PLATE` and `STONE_PLATE` are all valid solid blocks as defined by the `Material.isSolid()` in NMS (its native counterpart). Likewise, `FLOWER_POT` is a non-solid block.

Material.isSolid() more accurately describes its resistance to liquids, which is quite odd behavior.

For a more complete explanation and discussion, see https://bukkit.atlassian.net/browse/BUKKIT-5729

@turt2live I think this PR may be closed because:
- The changes committed are incorrect as described above.
- The code does not compile as it fails the `PerMaterialTest` test which validates `isSolid()` with its native counterpart.
- It does not follow the contribution guidelines.

**Comment by turt2live** [comment]
@JeromSar Closing PRs this quickly is unlikely. Further review is required as well as analysis of the problem scope. As it currently stands, the following issues are indeed raised, but do not qualify for an immediate closure at this exact moment:
- Contributing guidelines
- Lack of respect for CraftBukkit unit tests
- Lack of respect for documentation
- Lack of respect for other existing tickets

Further review is ongoing on this PR and will be closed/pulled/updated as required from here on out.

**Comment by turt2live** [comment]
Before this, or any other PR related to `isSolid` can be reviewed further someone needs to look at what the NMS `isSolid` does. Way back before Dinnerbone was part of Mojang the NMS `isSolid` was used to determine if something was "logically solid" (ie: exactly what the JavaDocs say). However at some time between then and now that NMS `isSolid` check changed and needs to be re-evaluated to determine what it actually does. 

Therefore, someone needs to analyze the NMS `isSolid` function and determine what it does compared to what it used to do. From that point a decision will be made about the Bukkit `isSolid` future.

**Comment by JeromSar** [comment]
@turt2live @feildmaster asked me to create a detailed leaky regarding the issue: https://bukkit.atlassian.net/browse/BUKKIT-5729

**Comment by turt2live** [comment]
@JeromSar that still doesn't answer what I've asked.

**Comment by JeromSar** [comment]
@turt2live He wanted a discussion on there.

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
