### PR TITLE
Undo weird use of singletons in Bukkit class

### PR DESCRIPTION
**Pull request by SpaceManiac**
Because the duplication of every method in Server in the Bukkit class seemed really weird.
Corresponding CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/467

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Deprecation please.

**Comment by SpaceManiac** [comment]
Any plugins already using these methods deserve to be broken :P (and it's not like there's been an RB yet, so breakages would be okay IMO) but if you insist I'll take care of this shortly.

---

From: "Dinner Bone" 
reply@reply.github.com
Sent: Sunday, 18 September, 2011 4:48 PM
To: "Tad Hardesty" tad.hardesty@suddenlink.net
Subject: Re: [Bukkit] Undo weird use of singletons in Bukkit class (#351)

**Comment by Dinnerbone** [comment]
I insist.

**Comment by SpaceManiac** [comment]
Done.

**Comment by Afforess** [comment]
Why? I thought they were added for utility purposes. What is wrong with them?

**Comment by SpaceManiac** [comment]
Just doesn't seem very clean (or anywhere near how singletons are supposed to work) to duplicate every single method of Server in Bukkit when an additional .getServer() is just as easy.

**Comment by CelticMinstrel** [comment]
An additional .getServer() isn't any harder, but it _is_ more verbose, which is annoying. Java is very verbose in general; I don't personally see a problem with that method of reducing that a bit, even if it's a bit ugly under the hood.

**Comment by Afforess** [comment]
Maybe I'm crazy, but I like the new Bukkit.foo() calls. It just reads cleaner to me.

**Comment by CelticMinstrel** [comment]
Yeah; whether it's clean depends on how you look at it. It's cleaner from a plugin developer's perspective, but less so from the perspective of someone submitting a pull request (for example).

**Comment by feildmaster** [comment]
I don't really like the thought of removing those functions. The convenience of Bukkit.foo() is something that should be there. :)

**Comment by feildmaster** [comment]
Also, CraftBukkit uses those "weird singletons" all over the place... Not just plugins. :3

**Comment by SpaceManiac** [comment]
"Corresponding CraftBukkit pull"

---

From: "feildmaster" 
reply@reply.github.com
Sent: Wednesday, 21 September, 2011 3:16 PM
To: "Tad Hardesty" tad.hardesty@suddenlink.net
Subject: Re: [Bukkit] Undo weird use of singletons in Bukkit class (#351)

**Comment by feildmaster** [comment]
@spacemaniac oh i see. ^^

**Pull request closed without merging**
