### PR TITLE
New locations

### PR DESCRIPTION
**Pull request by xZise**
In another [commit](https://github.com/Bukkit/Bukkit/commit/2f06becddcfea580e55dad6b1f3343074fa90ac4#comments) some discussed about a new location implementation.

This here allows different types of locations (int/double based, only x,y,z/+world/+directional, immutable/mutable).

The main problem are the obsolete Location and Vector classes. At the moment, all methods which are using locations still exists. But to allow using the new location types I added temporaly methods which returns the new types.

It isn't updated, but I will do this soon. Also I will create a corresponding CraftBukkit pull request. Primary I created this pull request to discuss about this and to know what the mood is about this problem/idea.

Fabian

### CODE REVIEW

**Comment by tips48** [comment]
Holy _insert cuss words here_ thats crazy :O

**Comment by phyreman** [comment]
Whoa....

**Comment by Afforess** [comment]
+1 love it.

This is _exactly_ what I was hoping would be implemented. Better, possibly, than I had hoped for.

**Comment by xZise** [comment]
The main problem is, that this will break every plugin which is using Locations, as I renamed the location class and created a special location package.

Fabian

**Comment by Afforess** [comment]
> The main problem is, that this will break every plugin which is using Locations, as I renamed the location class and created a special location package.

A needed change though, IMHO. Bukkit already warned of breaks in the next RB anyway.

**Comment by b1naryth1ef** [comment]
Add a deprication warning for the next few versions, and then add it in. +1

**Comment by xZise** [comment]
@Shamebot No, because the coordinates in the FixedBlockLocation are final and hopefully this allows the JRE to speed up things and the programmer could be sure, that the reference never change. For example now:

``` java
Location l = new Location(1,2,3);
Location lCopy = l.clone();
this.foobar(l);
// l mustn't be equals as lCopy
```

With FixedBlockLocation (Fixed as synonym for Immutable) you can be sure, that both are equal. The only possibility would be, to create a class which will be extended by both classes (Fixed and non fixed block location). Now I don't test if it is faster to call the value directly. For example following construct:

``` java
public abstract class BaseTest {

  public abstract int getNumber();

  public int getNumberSqr() {
    return this.getNumber() * this.getNumber();
  }
}

public class ImmutableTest extends BaseTest {

  public final int number = 42;

  public int getNumber() { return this.number; }

}

public class MutableTest extends BaseTest {

  private int number = 42;

  public int getNumber() { return this.number; }
  public void setNumber(int number) { this.number = number; }

}
```

You have to implement the sqr method only once, but you need an abstract getter, because in one class the value is final, while in the other it is mutable.

``` java
public class ImmutableTest {

  public final int number = 42;

  public int getNumber() { return this.number; }

  public int getNumberSqr() {
    return this.number * this.number;
  }
}

public class MutableTest {

  private int number = 42;

  public int getNumber() { return this.number; }
  public void setNumber(int number) { this.number = number; }

  public int getNumberSqr() {
    return this.number * this.number;
  }

}
```

Here I can access the value directly. I didn't run tests, to determine, which is faster (maybe the JRE is making optimizations there).

Apart from that, I could add some tricks in the fixed block location. For example the length/length squared is always the same I could store this value.

The break isn't really avoidable – I think. I will do my best tomorrow to update this to the newest and create the CB request, as this here seems to be wanted. And I don't want to slow down this because of formal errors.

Fabian

**Comment by Afforess** [comment]
> Ah ok thanks, I didn't notice the variables are final.

A small one, but the biggest thing is that final values are thread safe.

**Comment by xZise** [comment]
Okay, could somebody tell me, how I could clean this up? Making less commits and working on the newest Bukkit commits.

I'm also adding the getRelative() method (as it was “suggested” in some other pull request). And all world locations will have a “getBlock()” like the original Location has.

Fabian

**Comment by CelticMinstrel** [comment]
Not sure I like the deprecation of Vector; although a Vector is identical to a Location in terms of content, it's functionally quite different, representing a direction and distance rather than a direction and location.

**Comment by xZise** [comment]
It is only a naming difference. As each Vector could be also a pointer to a location and to have consistent names. Afaik Java don't allows me to create alias classes (such as Vector for an alias for a Location).

Fabian

**Comment by CelticMinstrel** [comment]
Speaking of consistent names, I'm not sure I like some of your name choices...

**Comment by xZise** [comment]
Ehr I'm not sure I like some of your comments... Sorry, but maybe more argumentive or helpful like "better" name suggestions?

Fabian

**Comment by CelticMinstrel** [comment]
FixedIntLocation --> FixedBlockLocation
FixedDoubleLocation --> FixedLocation

(for consistency with the non-fixed types)

Maybe DirectionalEntityLocation --> EntityLocation.

I think all the rest were okay.

**Comment by xZise** [comment]
Hmmmm, look in the second last commit: https://github.com/xZise/Bukkit/commit/2205aee3d3787faa8e7221f343636cd7b064702f

To name few:
- `src/main/java/org/bukkit/location/{WorldEntityLocation.java → EntityWorldLocation.java}`
- `src/main/java/org/bukkit/location/{FixedIntLocation.java → FixedBlockLocation.java}`
- `src/main/java/org/bukkit/location/{FixedWorldIntLocation.java → FixedBlockWorldLocation.java}`
- `src/main/java/org/bukkit/location/{DirectionalEntityLocation.java → EntityDirectionalLocation.java}`

Naming: `[Fixed]{Block,Entity}[World,Directional]Location`

Block means an integer location and Entity means a double location. An EntityDirectionalLocation (or DirectionalEntityLocation) is and location with doubles as coordination. Additionally the location has yaw and pitch. So renaming it to EntityLocation would downgrade it (acutally there is already an entity location).

Fabian

**Comment by CelticMinstrel** [comment]
Ah, I see. Never mind then. :)

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
