### PR TITLE
Cache Workarounds

### PR DESCRIPTION
**Pull request by FrozenCow**
A merge of https://github.com/Bukkit/Bukkit/pull/139 and https://github.com/Bukkit/Bukkit/pull/143 to make it easier to pull these changes.
This adds the following methods:
World.getBlockMetaDataAt
World.setBlockTypeIdAt
World.setBlockTypeIdAndDataAt

CraftBukkit: https://github.com/Bukkit/CraftBukkit/pull/178

### CODE REVIEW

**Comment by Timberjaw** [comment]
Won't this result in cache inconsistencies if one plugin/method uses the cache-free methods and another plugin/method uses the regular methods?

**Comment by FrozenCow** [comment]
Block.getMetaData just calls the same method as getBlockMetaDataAt, they use the same resource. The only caching that is being done is on Block-objects (which only stores their coordinates and 'parent' Chunk) afaik.

**Comment by Timberjaw** [comment]
Sorry, I wasn't clear. I'm referring to the block cache that is kept in each chunk. If the block references in that cache are simply that (references), however, I don't anticipate a problem.

**Comment by FrozenCow** [comment]
Yes, as far as i know they are just that: references. Although I don't know what the Bukkit-team has in mind for them.

Just as a note, this request will probably not be pulled, since Dinnerbone wants to make the caches thread-safe, even though the performance will suffer.

**Comment by Afforess** [comment]
If it's not going to be pulled, then close it.

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
