### PR TITLE
Added shootFireball.

### PR DESCRIPTION
**Pull request by RobinvanderVliet**
This pull adds shootFireball for entities.

Corresponding CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/359.

### CODE REVIEW

**Comment by wizjany** [comment]
Any reason it's returning an arrow?

**Comment by RobinvanderVliet** [comment]
Oops, how can I change it? :P

**Comment by wizjany** [comment]
rebase, change, ammend commit, push --force

**Comment by RobinvanderVliet** [comment]
Uhu? And how do I do that?

**Comment by wizjany** [comment]
http://help.github.com/rebase/

**Comment by RobinvanderVliet** [comment]
How can I use such a command?
Or can someone else change it?

**Comment by wizjany** [comment]
...how have you been using git until now?

**Comment by RobinvanderVliet** [comment]
On the internet?
https://github.com/Bukkit/Bukkit/pull/274

**Comment by RobinvanderVliet** [comment]
I found it, it is fixed now. :)

**Comment by erisdev** [comment]
I think this feature should be generalised into a single method rather than having separate `throwSnowball()`, `shootArrow()` and `shootFireball()` methods. See `org.bukkit.World`'s spawn method, for instance.

```
public <T extends Entity> T spawn(Location location, Class<T> clazz) throws IllegalArgumentException;
```

You can pass any class that inherits from Entity and it will spawn that kind of entity. `Egg`, `Fireball` and `Arrow` have a common base, `Projectile`, that would be suitable here.

**Comment by winsock** [comment]
@erisdiscord I agree something like: 

```
public void shootProjectile(Class<T extends Projectile> clazz);
```

would work a lot better and remove unnecessary code.

**Pull request closed without merging**
