### PR TITLE
adds MaterialData classes and associated Enums for COAL, CROPS, LOG, LEAVES, STEP, and DOUBLE_STEP

### PR DESCRIPTION
**Pull request by sunkid**

### CODE REVIEW

**Comment by cyklo** [comment]
I like this commit, and it would add some useful functionality. However, I'm not sure I agree with the Enum names you've given to the crops. Seeded/germinated/very small don't correspond (to me, at least) to what's seen in-game.

**Comment by sunkid** [comment]
You must not be a biologist ;)

Do you have a better suggestion for the Enum names? I am not particularly attached to them but they made sense to me.

**Comment by cyklo** [comment]
Nope, a physicist who abhors all things green! :)

I understand what you mean with seeded/germinated, it's just that
Minecraft shows green shoots for all phases.

Much like the "block break", levels, PLANTED (0), RIPE (7) and GROWING
(all others) would be sufficient Enum descriptors. If you need to know
exactly what growing phase, access the data value directly.

On 16 Mar 2011, at 16:18, sunkid
reply@reply.github.com
wrote:

**Comment by sunkid** [comment]
PLANTED, GROWING, and RIPE would work for me! It's simpler and there isn't really much use for the different growth stages (except for maybe the one before ripe, which does drop wheat when harvested, doesn't it?).

I'll leave it up for whoever pulls this to make the simple change.

**Comment by grum** [comment]
pew, accepted after whitespace cleanifications!

**Comment by sunkid** [comment]
Thanks! I'll check my Eclipse configuration.

**Pull request closed without merging**
