### PR TITLE
Add EntityTeleportEvent. Fix for BUKKIT-366

### PR DESCRIPTION
**Pull request by craftycreeper**
Fires whenever an Enderman teleports and allows checking of to/from location. I wrote this to fix BUKKIT-366 (https://bukkit.atlassian.net/browse/BUKKIT-366), as I need the feature for a plugin I'm working on. This is my first foray into Bukkit modifications, so any constructive criticism would be very helpful.

The event can be a bit spammy when the an Enderman starts going crazy in the rain, but hopefully this situation should always resolve itself quickly via the Enderman's death or teleportation to a dry spot (unless you just blindly cancel every teleport, forcing the Enderman to stay out in the rain and continue to try to escape).

(This is a companion to https://github.com/Bukkit/CraftBukkit/pull/662)

### CODE REVIEW

**Comment by EvilSeph** [comment]
This pull looks good, we're just wondering if we should be using EntityTeleportEvent instead, especially if we can catch pets teleporting. I'm leaning towards EntityTeleport (as well as making whatever events we can more generic, for example: PigZap and CreeperPowered).

**Comment by craftycreeper** [comment]
That's fine! I can easily change it if that'd be helpful.

**Comment by EvilSeph** [comment]
setCancelled and isCancelled already inherit javadocs from Cancellable so they should be removed. The Event class is also missing JavaDocs to explain what the class is for.

As far as I can see, those are the only issues we have with this pull request. Correct those (as well as renaming the event as per above discussions) and I'll look into this again.

Thanks for the contribution!

**Comment by EvilSeph** [comment]
Pulled, thanks!

**Pull request closed without merging**
