### PR TITLE
Adds basic custom entity AI functionality

### PR DESCRIPTION
**Pull request by Raphfrk**
This allows a plugin to override the AI of a particular entity.

There is a matching CraftBukkit pull.

https://github.com/Bukkit/CraftBukkit/pull/232

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Uh, did you forget the EntityAI file?

**Comment by grum** [comment]
Apparently so. As discussed this might linger around quite some time as right now we do not exactly know what we want from the AI.

**Comment by Raphfrk** [comment]
The file is there now.

Also, this gives lots of flexibility to the plugin's AI (perhaps to much), since it just polls it every clock tick.  The AI needs to tell the server what the target and destination of the creature should be.

Possible additions would be to set the pathing manually rather than setting a destination.

My view is that giving basic functionality early is better than waiting for ages for the full system.  Granted that argument didn't work with the scheduler.

A plugin author would be pretty free to implement AI with this change.

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
