### PR TITLE
Makes the error for "No player by that name" more descriptive

### PR DESCRIPTION
**Pull request by gbear605**
Makes the error for "No player by that name" more descriptive by telling you what name you typed.  This can be helpful so that you know if they aren't online, or if you typed their name wrong.  Also, sometimes, I have wondered "What exactly did I type, anyways?"

### CODE REVIEW

**Comment by Wolvereness** [comment]
player == null then player.getName() will ALWAYS throw a NullPointerException

I'm also pretty sure this wont compile, you have string concatenation without the + signs.

**Comment by Top-Cat** [comment]
Yeah you need to use args[0] not player.getName()

**Comment by gbear605** [comment]
XD Sorry, I was doing this fairly late at night.

**Comment by Top-Cat** [comment]
Bukkit doesn't look through their pull requests... unless you're lucky. Get used to it

**Pull request closed without merging**
