### PR TITLE
PlayerPreLoginEvent changes

### PR DESCRIPTION
**Pull request by zml2008**
Changed PlayerPreLoginEvent to allow plugins to set the real name of the player as it appears to the server and all other clients.

CraftBukkit Pull request: https://github.com/Bukkit/CraftBukkit/pull/439

### CODE REVIEW

**Comment by codename-B** [comment]
I approve this, setting the name of a player allows for fun customisation like Color Codes added to all players names as they log in!

**Comment by ghost** [comment]
I also approve of this, I've been looking for a way to do exactly what this allows for!

**Comment by alexstanoev** [comment]
This would've been perfect, but there are a couple of issues:
Changing the name breaks the player's skin, no way to fix.
Changing the name also makes all plugins that use the player name to act strange, due to the fact that... the name has changed and has unexpected symbols in it.
Screenshot of this in action: http://i.imgur.com/SMQj1.png

But.. this is perfect for display name changer plugins. I would love to see this pulled.

**Comment by wizjany** [comment]
I think the whole check auth thing is a little controversial...

**Comment by Rigby90** [comment]
IMO the fact that skins become unusable in this state and changing the players name introduces problems with plugins... not to mention adding colours would cause hassle... I doubt it would be pulled.

I also agree with wizjany, the ability to let certain players avoid authentication checks is a bit dodgy.

What use case do you have for the ability to change per player authentication? Apart from allowing cracked clients onto the server with online mode.

An alternative for the name changing would be to use the "display name" when sending information to other clients allowing names to be Prefixed/Suffixed and Coloured on the client end. However at this moment in time I'm not sure what that would take and whether any other issues would be introduced by such a method.

**Comment by EvilSeph** [comment]
There is no possible way this will ever be pulled for the obvious reasons Rigby has covered.

**Comment by zml2008** [comment]
I changed the offline mode to be a global setting, which still allows putting the server into offline mode when minecraft.net is down but does not allow pirated clients on the server with online mode. I never really wrote this to allow colored player names, but it's not all that hard to fix player entry of colored names in plugins with some ChatColor.stripColor()-ing.

**Comment by wizjany** [comment]
it's still possible to turn it off, let a player log on, then turn it back on...

**Comment by zml2008** [comment]
There's no way for a plugin to do that automatically without the
PlayerHandshakeEvent. Still requires manual intervention of the server admin
to change the setting.

**Comment by wizjany** [comment]
actually, a plugin can do it automatically

**Comment by zml2008** [comment]
well a plugin can do it automatically but afaik without PlayerHandshakeEvent
there's no way to tell if a player tried to connect but did not
authenticate.

**Comment by alexstanoev** [comment]
So as far as I can see the main reason against this is the setName stuff? What's the chance of this getting pulled without the setName on prelogin code?
This commit will unlock tons of new options for authorization plugins, mainly checking a client's minecraft.net authorization, which would be very useful.

I believe bukkit should remain neutral to both types of servers, offline and online mode. The reasons posted here look like favoring online-mode.

**Comment by EvilSeph** [comment]
Under no circumstances will we provide or support a way to bypass Minecraft's authentication. There is online mode or there is offline mode and only because it is provided by vanilla.

**Comment by zml2008** [comment]
Improved version without authentication changes: https://github.com/Bukkit/Bukkit/pull/331

**Pull request closed without merging**
