### PR TITLE
[B+C] Add setKnockbackStrength for arrows. BUKKIT-5103

### PR DESCRIPTION
**Pull request by Likaos**
The Issue:
None: just add more stuff in the api.

Justification for this PR:
Less nms in plugins.

PR Breakdown:
Use the vanilla fonction setKnockbackStrength on arrow entity, must be positive (mc check that) and have no limits.

Relevant PR:
https://github.com/Bukkit/CraftBukkit/pull/1287

JIRA Ticket:
https://bukkit.atlassian.net/browse/BUKKIT-5103

### CODE REVIEW

**Comment by Likaos** [comment]
the KnockbackStrength is private, there's only a method to set it, so I cant without editing the vanilla code.

**Comment by gmcferrin** [comment]
What do you mean? If you need to edit the vanilla code, then include that
in the CraftBukkit PR.

Also, fix your spelling in the Javadoc.

**Comment by Likaos** [comment]
added the getknockback method

**Comment by gmcferrin** [comment]
Next question - is this method ONLY valid for arrows, or is it available for all Projectiles?

**Comment by Likaos** [comment]
Only the Arrows have a method to KnockBack in Minecraft.

**Comment by gmcferrin** [comment]
I could have sworn that snowballs had knockback too...

**Comment by Likaos** [comment]
Juste make it with a plugin, when projectile impact if snowball > set velocity ;)

**Comment by gmcferrin** [comment]
By that argument you should just do the same for arrows.

**Comment by Likaos** [comment]
Not really, minecraft have a native method to set the knockback effect, I just map it with the bukkit API to share for everyone.
Else I could continue to use it with NMS code in my plugins, it's a lot easier and much faster then make a PR.

**Comment by Likaos** [comment]
-I added a method to get the knockbackStrength from arrow.

-The snowball does not have any knockback effect at all only a damage effect (who bump the player), no one could modify an inexistent knockback effect :/.

**Comment by gmcferrin** [comment]
Yeah, I think you're right, arrows are the only projectiles with an actual
knockback value, likely due to the enchant that messes with knockback.

**Comment by punkeel** [comment]
Up. Would be glad to have this, replacing my 10 lines method with a one-liner ...
Oh, and not having to update it every time, too.

Thanks in advance

**Comment by turt2live** [comment]
Handled by https://github.com/Bukkit/CraftBukkit/compare/452109e716...88d138fc43 - thanks for your contribution!

**Pull request closed without merging**
