### PR TITLE
Added MOTD methods to Server.

### PR DESCRIPTION
**Pull request by KokaKiwi**

### CODE REVIEW

**Comment by Cogito** [comment]
Hi there, this sort of thing is typically added to the server via a plugin. The modularity of Bukkit ensures that server admins can pick most features that they want on their server themselves.

As such, this is not something we will include in the core.

**Comment by Cogito** [comment]
having looked into your implementation, what you are actually trying to do is expose the 'Server Description' shown to clients before they log in. This is quite different to a MOTD, shown to players when they log in. Maybe re-jig the pull request and resubmit it.

**Comment by Cogito** [comment]
Although notch does call it motd - the main issue is that the naming is confusing in the context of existing plugins that provide motd functionality.

**Comment by KokaKiwi** [comment]
I've writed MOTD because that's the name of this property in properties file ;)
Thanks for your response ^-^

**Pull request closed without merging**
