### PR TITLE
Added setDrops() to set what the entity drops upon death

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Fishrock123** [comment]
Needs a space inserted:

```
items)<space>{

so:

items) {
```

**Comment by feildmaster** [comment]
entitydeathevent.getDrops().modifythefreakinglist, I don't understand why people don't understand this.

**Comment by ghost** [comment]
I already tried used getDrops().clear(); and it didn't work. I suppose it could be on my end, though.

**Comment by SagaciousZed** [comment]
@feildmaster I think it needs to be made clear that the list is not a copy, but the actual list that is used for the drops.

**Pull request closed without merging**
