### PR TITLE
Allows for per-player time or time-offset. 

### PR DESCRIPTION
**Pull request by eisental**
See matching CraftBukkit pull-request at
https://github.com/Bukkit/CraftBukkit/pull/279

by Shamebot, needspeed10 and me.

### CODE REVIEW

**Comment by xZise** [comment]
There is no need of DST on a Bukkit Server, because every day has the same length. So there are no shorter day in winter (when is winter on a server?) and longer days in summer.

Fabian

**Comment by eisental** [comment]
Could be a nice feature if seasons are ever implemented in minecraft. It would also be possible by this request :)

**Comment by xZise** [comment]
Not exactly: The position of the sun is determined by the time ingame. But with DST the sun must be one hour “behind” the time ingame. So if the world's time for example 0 without DST the sun is rising, but with DST the sun has to be one hour before 0.

I don't know how long one hour is, but lets say `one hour =: A`. Now with DST the internal time has to be `-A` or `24000 - A`. And this couldn't be achieved by this pull. Or maybe I'm wrong, and the sun doesn't depend on the player's time.

Fabian

**Comment by eisental** [comment]
To move the sun one hour behind the server time you could do:

``` java
player.setPlayerTime(-1000, true);
```

This will keep the time on the player's client constantly 1 hour behind the server (true is for relative) effectively
causing the sun/moon on the player's client to behave as if the time is 1 hour earlier that it really is.

**Comment by xZise** [comment]
But it also changes the time player. So if the player uses any client mods to read this time will get the non DST time (so 0 is again sun rising). But yep, you are correct, as long as the client uses any mods. I thought that any plugin will also be confused (e.g. the daysensor craftbook IC), but this will read the world's time.

So you could make a fake DST plugin.

Fabian

**Comment by eisental** [comment]
Correct. You could make a DST plugin (you could argue if it's fake or not), but more interestingly implement realistic and non-realistic world time zones as well.

**Comment by xZise** [comment]
Okay, I mean “fake”, because it is no real DST, as the sun is with and without DST at the same spot at the same time. So if the time is 12:00 the sun is at the maximum. For “real” DST in Minecraft the client have to be the time 13:00 and the sun at the maximum. Then could a client side mod show for example a clock and show always 12:00 when the sun is at maximum. Only the server side plugins/mods could differ between real time and player time.

But why should you do this ;) I'm myself hate DST and this would require the client to have two different “times”. One real time (which sets the position of the sun/moon) and one clock time.

And for time zones this change is great, although the world have to be large to be realistic… But what is realistic in Minecraft so hopefully this will be implemented soon.

Fabian

**Comment by eisental** [comment]
Oh, I see what you mean. I wasn't aware of any client-side time mods...

**Comment by EvilSeph** [comment]
As there are multiple authors, this pull request becomes complicated. I can apply it manually and thank everyone if all the authors do not mind. Otherwise, I cannot pull this.

**Comment by eisental** [comment]
Well, I don't think anyone would mind about credits if you actually pull it. Manual is fine. It could also be under my name if there are credits to Shamebot and needspeed10 in the comments if that's easier for you.
Thanks.

**Comment by needspeed** [comment]
It doesn't really make a difference to me. So manually or by pull are both ok.

**Comment by EvilSeph** [comment]
Applied manually, thanks!

**Pull request closed without merging**
