### PR TITLE
Added Sky biome for the Skylands.

### PR DESCRIPTION
**Pull request by RobinvanderVliet**
This pull adds the Sky biome for the Skylands.
(This is my first pull, I don't know if i have done it right.)

Corresponding CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/355.

### CODE REVIEW

**Comment by mikeprimm** [comment]
I may have missed it, but you are going to need a corresponding pull with a change to CraftBlock.jar in CraftBukkit (the getBiome() method does the mapping from BiomeBase classes to this enumeration, so it'll need to handle BiomeSky->SKY).

**Comment by RobinvanderVliet** [comment]
Added. ;)

**Comment by Afforess** [comment]
Not commenting on your pull, just the getBiome code in general - I'm curious why a case statement wasn't used. It seems ideal, instead of the massive if else block.

**Comment by mikeprimm** [comment]
@Afforess: Yep - seems like it'd be even cooler (in another pull) to modify BiomeBase to declare the BiomeBase instances with the Biome values - just totally eliminate the conditional, make it as fast as possible.

**Comment by sunkid** [comment]
@Afforess [BiomeBase](https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/BiomeBase.java) is a regular class and you cannot use switch/case statements with it.

**Comment by EvilSeph** [comment]
Applied manually, thanks!

**Pull request closed without merging**
