### PR TITLE
Python Plugin Loader

### PR DESCRIPTION
**Pull request by masteroftime**
Implements a plugin loader which is capable of loading plugins written in python.

Discussed in the bukkit forum: http://forums.bukkit.org/threads/python-plugin-loader.21247/

### CODE REVIEW

**Comment by Afforess** [comment]
I'm not sure what Bukkit's official policy is on multilanguage support. I'm curious what @Grum, @Evilseph and @Dinnerbone have to say on the matter.

**Comment by Dinnerbone** [comment]
We encourage people to make pluginloaders by means of plugins, not built in.

**Comment by Afforess** [comment]
Okay. I take it this should be closed then?

**Comment by CwbhX** [comment]
Well, even if that is so DinnberBone, I believe this would be a great addition to Bukkit. Then people can make even more plugins... Isn't that what you would like? I Hope very much so that it isn't closed!

**Comment by CruzBishop** [comment]
@Dinnerbone: Sorry, that doesn't even make sense. Is it because of overhead or just because you only want to "officially" support Java plugins out of the box?

**Comment by CwbhX** [comment]
@CruzBishop it does make sense. @Dinnerbone wants this to be a plugin not a mod to bukkit. I disagree and think he is making the wrong choice. He should be helping the community by allowing this. Sooo many people know Python better than Java. It doesn't make sense. This is a great mod! It doesn't remove anything. Please Dinnerbone!
Please Don't close it! It has soo much potential!

**Comment by b1naryth1ef** [comment]
@dinnberbone I agree with @cwbhx. It'd be great to have _built-in_ support of python for plugins. 1up this.

**Comment by desmin88** [comment]
I find this better suited to be plugin-based instead of built-in.

**Comment by CwbhX** [comment]
@desmin88 I believe this way would be way quicker and nicer. Having a Plugin to load a plugin is bleh

**Comment by Afforess** [comment]
"Having a Plugin to load a plugin is bleh" 

Ever heard of dependencies? It's common. People do it for Permissions, Iconomy, etc.

Anyway, I think natively supporting a language without a clear roadmap sets poor precedence. Should then Bukkit add C++, C#, Lua, Ruby, PHP (I kid...), etc support for plugins too? I'd rather they discussed it for a while, and came up with a plan, or an official way to link in other language plugin loaders.

**Comment by DrakiaXYZ** [comment]
@Afforess I'm with you, they should totally add a PHP plugin API

**Comment by alecgorge** [comment]
It is possible to have a plugin handle different files as plugins. I wrote a small Javascript plugin class loader for my own devices a while back.

**Comment by wizjany** [comment]
there's nothing new about loading non-java plugins through other plugins, and if server owners need those non-java plugins then the loader plugin as a dependency is not too much to ask
having inbuilt support for this is not only bloat, but certain parts of it wont be java 1.5 compatible, which if you weren't aware is what mojang and the bukkit team build on
also check out http://forums.bukkit.org/threads/inactive-dev-jxpl-javax-script-plugin-loader-r5-556.3550/ 
worldedit also supprts javascript plugins (albeit only to its own api) in the form of craftscripts (formerly editscripts way back in hmod days)

**Comment by CwbhX** [comment]
@Afforess Yes, but they could get @masteroftime on their side. Then they could plan, and have people to work on the Python part of Bukkit.

**Comment by ayan4m1** [comment]
@CwbhX Point being, it's a pull request. @masteroftime asked that this be merged in after writing the code. You don't tell your boss "Hey, I have the proposal for Project X completed," hand him a file folder containing a sandwich, then respond to the blank stare with "Well sure it's not done, if you don't accept the proposal, then how will we ever plan it out properly?!"

This would almost certainly be useful to some server administrators / plugin authors, but it would certainly not be useful to all of them. The assertion that more people know Python than Java, or that more people know Python "better" than they know Java, seems like hyperbole to me. Look at langpop.com for some real statistics. More people know Java, and it is at least as likely that anyone who has downloaded and installed a Java-based Minecraft server (i.e. CraftBukkit) knows Java compared to Python.

As a server admin, I shouldn't have to download support for a plugin language I may not even know exists. Making this pull request a separate plugin would only add one step for anyone looking to run a Python-based plugin, whereas if it were integrated it would add (debatable) bloat, a new dependency (jython), and most importantly, more code which will have to be looked over and maintained by a team which is already trying to manage a fairly large codebase.

The idea that a server admin is incapable of downloading and installing a Python plugin loader yet has also either written a Python plugin on their own or wants to use an existing Python-only plugin is frankly preposterous.

**Comment by grum** [comment]
I can understand why 'native support for {insert language}' would be a wanted feature. Yet if we'd accept this pullrequest then suddenly we (as Bukkit) become responsible for the maintenance. We could probably learn it but we've already have our hands full with the project as it is.

So maybe the interface for registering (custom) plugin loaders is not done/ideal/dunno, but that is something we can work on :D

See also: http://forums.bukkit.org/threads/python-plugin-loader.21247/page-3#post-467201

**Pull request closed without merging**
