### PR TITLE
Event system optimizations

### PR DESCRIPTION
**Pull request by TomyLobo**
This should slightly improve speed and reduce complexity.
If you squash these commits, please use this commit message:

```
Event system optimizations

- Made the handlers field a simple array instead of an array of arrays.
- Got rid of the "baked" field.
```

Last time I pull-requested multiple commits somewhere, it ended up as a mess *g*

The last 2 work in conjunction to provide a way to enable event handlers at runtime

### CODE REVIEW

**Comment by feildmaster** [comment]
Much cleaner.

**Comment by TomyLobo** [comment]
and no new features, joy!

**Comment by EvilSeph** [comment]
We've moved to a new model of having a Leaky ticket per commit/pull request, please supply one for this to get pulled. See the updated README.md for more information.

**Comment by TomyLobo** [comment]
pull request withdrawn because of ridiculous requirements by bukkit team

this change is contained in Bukkit++

**Comment by dredhorse** [comment]
sigh...

**Comment by patrickfreed** [comment]
https://bukkit.atlassian.net/browse/BUKKIT-813

You can pull this now.

**Comment by Fishrock123** [comment]
Can you pull closed requests? If not I'ma copy and paste. -_-

**Comment by tips48** [comment]
-_-

**Pull request closed without merging**
