### PR TITLE
[B] Call WorldSaveEvent on SaveCommand. Fixes BUKKIT-3681

### PR DESCRIPTION
**Pull request by BjoernPetersen**
**The Issue:**

When the "save-all" command is used, the WorldSaveEvent is not triggered, so plugins relying on the event don't save their data (or do something else).

**Justification:**

The event is always called when saving worlds, but not when saving is forced by a SaveCommand. There is no reasonable explanation for this to me.

**PR Breakdown:**
This PR triggers a WorldSaveEvent for every world that is saved by the org.bukkit.command.defaults.SaveCommand class.

**Testing Results and Materials:**
I found no duplication of the event implementation. I used this plugin for testing: https://github.com/Pheasn/WorldSaveTracker .
Binary can be found here: https://pheasn.de/downloads/generalbin/tracker.jar

**JIRA Ticket:**
BUKKIT-3681 - https://bukkit.atlassian.net/browse/BUKKIT-3681

### CODE REVIEW

**Comment by BjoernPetersen** [comment]
Why does it take so long to add such a simple change?

**Comment by Pocketkid2** [comment]
why not put the event caller in world.save() method instead of throwing it afterward? It seems that it would work for everything if you did it that way.

**Comment by turt2live** [comment]
Moving it (and removing the duplicate calls) would likely fit the use case better and provide future support.

**Comment by BjoernPetersen** [comment]
Yeah, I'll change it when I come home. I thought this was the common point to call events because of the current implementation... 

(Also, I'll fix the download link for the broken test plugin link)

**Comment by Wolvereness** [comment]
@turt2live https://github.com/Bukkit/Bukkit/pull/971#issuecomment-31796216

> Moving it (and removing the duplicate calls) would likely fit the use case better and provide future support.

https://github.com/Bukkit/CraftBukkit/pull/1315#issuecomment-31839287

**Comment by BjoernPetersen** [comment]
Well, fuck it then, someone else shall do it.

**Pull request closed without merging**
