### PR TITLE
All (?) needed things for ServerLoadEvent

### PR DESCRIPTION
**Pull request by CruzBishop**
My new implementation of ServerLoadEvent

Thanks to whoever it was before saying that ServerLoadedEvent was invalid!

### CODE REVIEW

**Comment by CruzBishop** [comment]
...Did I do something wrong? I've usually got at least "This is too messy" or "We'll see" by now <,<

**Comment by Dinnerbone** [comment]
Be patient. We have many pull requests and we're busy people.

However, what's the difference between this and https://github.com/Bukkit/Bukkit/pull/172 ?

**Comment by CruzBishop** [comment]
Oh, sorry.

I didn't actually see anything that could relate to your question. Do you mean ServerEvent?

I just thought that since it was for loading, it would have to use a Server(Load)Event.

**Comment by Dinnerbone** [comment]
Huh, github hid the link. Pull request 172

**Comment by CruzBishop** [comment]
It looks like the onStartup() is going to be done by changing the constructor of server.loadPlugins

Oh, I just looked, it is. It notifies just before the other plugins load.

This allows plugins that can run when the server writes "Done ($s)! For help..."

I'll go submit my CraftBukkit implementation so you can see. Here's the output that I'm planning on (with a quick plugin I wrote up)

http://i54.tinypic.com/2pspx5g.png

**Comment by CruzBishop** [comment]
I submitted pull request 247 (https://github.com/Bukkit/CraftBukkit/pull/247) which implements this.

**Comment by CelticMinstrel** [comment]
This would actually be helpful to me, since my plugin has something that should really not be done until after it is guaranteed that all plugins have loaded. (If you're interested, it needs to detect if there is a permissions system installed — yes, that could be done with onPluginLoad, but the thing is that onPluginLoad provides no good way to do something if _no plugin_ was detected, which in this case is important.)

**Comment by CruzBishop** [comment]
I was just wondering if there's any news on this.

**Comment by Raphfrk** [comment]
Btw, you can use the depend keyword in the plugin.yml file to mark other plugins that must be loaded before yours will start.

**Comment by CelticMinstrel** [comment]
That doesn't work when the dependency is optional.

**Comment by CruzBishop** [comment]
This is old, closing

**Comment by Raphfrk** [comment]
```
CelticMinstrel
That doesn't work when the dependency is optional.
```

I added a pull for soft dependencies.
https://github.com/Bukkit/Bukkit/pull/215

**Pull request closed without merging**
