### PR TITLE
Update names for porkchop

### PR DESCRIPTION
**Pull request by timbru31**
Hi,

because every other food is listed as "RAW_food" and "COOKED_food", I've done the same for porkchop!
Small fix/tweak, but you don't have to search for them anymore, because they are named other.

### CODE REVIEW

**Comment by wizjany** [comment]
this breaks everything, seriously

**Comment by timbru31** [comment]
Possible to add both variants?
Should be, shouldn't it?

**Comment by cyberdudedk** [comment]
I agree on this. Wouldn't it be sufficient, to deprecate the old values, and have both variants running for a couple of RB's.
I highly prefer this style for porkchop as it's fits with the rest. This is really what it should have been all along.

**Comment by mikeprimm** [comment]
I'm with @wisjany on this - it offers no functional gain, no improvement of user experience or performance, no design integrity improvements, and breaks existing plugins - it has nothing but aesthetic appeal, which is good for new stuff with no dependencies, but bad in this case.  The thought of adding duplicates creates problems with both '==' and ordinal-based logic (switches) - it's an enumeration, and unlike C/C++ style enums, every element is distinctive (even if its internal properties happen to be the same): if getMaterial() returns Material.PORK, that will not equal Material.RAW_PORKCHOP in a '==' or a 'switch() case RAW_PORKCHOP:'.

**Comment by cyberdudedk** [comment]
The == problem could be fixed by implementing equals and hashcode right?
I agree it doesn't add anything for user experience or performance, but isn't this kind of fixes exactly design integrity?.
Especially if the equals problem can be fixed.

**Comment by mikeprimm** [comment]
equals() and == aren't the same, so it unfortunately wouldn't help.  From a design point of view, there isn't anything wrong with it - call it PORK, call it PORKCHOP, call it THEOTHERWHITEMEAT, its all the same - it is only a symbol visible to the programmer, versus anything that impact system performance, integrity, maintenance, user experience, etc, so I don't see it as a point of design integrity.  In retrospect, if we were defining these for the first time, I agree that the suggested symbols are better choices - but I don't see that functional breaks in plugins are justified (particularly since removing anything from an enum tends to be a big pain for folks that want to keep their plugins working for a range of builds, versus only one specific version forward).

**Comment by cyberdudedk** [comment]
@mikeprimm
Now I remember why I love C# so much more, going back to Java I have found numerous things I can't do anymore :(.
In C# I'm used to being able to do operator overloading on == so it wouldn't be a problem implementing that.
Sometimes one needs to know the limits of Java, when one has been too used to C# for a long time.

**Comment by Dinnerbone** [comment]
Not pulling as it seriously does break everything, sorry. We can't deprecate because things that previously relied on the result of a call being one of the deprecated values won't be, as it's the new value. It sucks, but welcome to java <3

Sorry.

**Comment by timbru31** [comment]
It's okay :P
Some day in the future you (we) can edit it xD

**Pull request closed without merging**
