### PR TITLE
Added ENTITY_SET_HEALTH Event BUKKIT-274

### PR DESCRIPTION
**Pull request by steffengy**
Adds the EntitySetHealth Event to Bukkit.
CraftBukkit PULL: https://github.com/Bukkit/CraftBukkit/pull/589
Makes it possible to handle setHealth :)

### CODE REVIEW

**Comment by Cogito** [comment]
This commit message is entirely inadequate. It is good to reference a bug
number, however the commit message should make sense by itself.

On Sunday, December 11, 2011, steffengy <
reply@reply.github.com>
wrote:

> EntitySetHealthEvent
> 
> You can merge this Pull Request by running:
> 
>  git pull https://github.com/steffengy/Bukkit master
> 
> Or you can view, comment on it, or merge it online at:
> 
>  https://github.com/Bukkit/Bukkit/pull/448
> 
> -- Commit Summary --
> - Add BUKKIT-274
> 
> -- File Changes --
> 
> M src/main/java/org/bukkit/event/Event.java (8)
> M src/main/java/org/bukkit/event/entity/EntityListener.java (7)
> A src/main/java/org/bukkit/event/entity/EntitySetHealthEvent.java (66)
> M src/main/java/org/bukkit/plugin/java/JavaPluginLoader.java (6)
> 
> -- Patch Links --
> 
>  https://github.com/Bukkit/Bukkit/pull/448.patch
>  https://github.com/Bukkit/Bukkit/pull/448.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Bukkit/Bukkit/pull/448

## 

Regards,

Andrew Ardill

**Comment by steffengy** [comment]
I was in hurry because i had to go, so i just typed something, from that i thought it was at least a bit understandable.
If you need the exact description:
It adds an Hook to setHealth in LivingEntity and the Event "EntitySetHealth" and also the "function" onEntitySetHealth.
The CraftBukkit Commit to this commit is:
https://github.com/Bukkit/CraftBukkit/pull/589

**Comment by EvilSeph** [comment]
As stated in the CB pull request:

I think it would make more sense to incorporate a filtering mechanism into the existing implementation than creating a whole new event for this. We've been discussing setting up a filtering mechanism across all events that include natural and plugin triggers but came to the conclusion it would break things, so something like this will only find its way into core after the API-centric RB we're pushing for comes out.

**Comment by grum** [comment]
Closing this for now because it doesn't adhere to the style guide and because of what EvilSeph said.

**Pull request closed without merging**
