### PR TITLE
Improved FileConfiguration and fixed unit tests

### PR DESCRIPTION
**Pull request by t3hk0d3**
Replaced String buffer (loadFromString/writeToString) reading/writing, which are not memory wise, with Reader/Writer (load(Reader) / write(Writer)).

Also fixed falsificated unit tests: output are not matched to input.

Example:

```
config = YamlConfiguration.loadFromString(header + values);
....
assertEqual(header + "\n" + values, config.saveToString());
```

Kinda wrong, huh?
Take attention on extra newline character

### CODE REVIEW

**Comment by feildmaster** [comment]
The extra new line is not wrong.

The configuration goes as so:

Header
(blank line)
Configuration

Loading can load without the blank line, BUT when saving it will add a blank line.

**Comment by t3hk0d3** [comment]
@feildmaster 
Blank lines is already included into header.

Literally this bug means every save would add additional newline. After 100 saves there would be 100 new lines.

**Comment by feildmaster** [comment]
Thank you for your submission, I realize this is a late comment, however, this PR shall not be pulled.

Reasons being:
1. You have branch merges. >:|
2. The code is not up to date

Please feel free to resubmit an updated PR  if you still want this change.

**Comment by t3hk0d3** [comment]
oh wow

**Pull request closed without merging**
