### PR TITLE
Added ChickenLayEggEvent

### PR DESCRIPTION
**Pull request by Pocketkid2**

### CODE REVIEW

**Comment by BjoernPetersen** [comment]
I think you should at least try to follow this https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

**Comment by ghost** [comment]
@Wolvereness 
@turt2live 
any of you gonna do your thing?

**Comment by turt2live** [comment]
There are over 150 open PRs. One of us will get to it.

sent from mobile

**Comment by turt2live** [comment]
Related PR: https://github.com/Bukkit/CraftBukkit/pull/1275

**Comment by turt2live** [comment]
Closing this in favour of https://github.com/Bukkit/Bukkit/pull/902

Thank you for your contribution!

**Pull request closed without merging**
