### PR TITLE
Converting allowMonsters/allowAnimals from boolean into Set<SpawnReason>...

### PR DESCRIPTION
**Pull request by oloflarsson**
.... With this you can for example have worlds where no mobs spawn naturally but DO spawn from mobspawners. If this where to be done using bukkit events only it would cause heavy CPU usage since the algorithm that spawns mobs naturally would run all the time.

### CODE REVIEW

**Comment by tips48** [comment]
Link the to CraftBukkit change, open a ticket on leaky (leaky.bukkit.org), and merge your commits to have a better chance of getting accepted. Haven't looked at the implementation, but this sounds like a good idea :)

**Comment by jrtc27** [comment]
Deprecate the old methods rather than replacing them.

**Comment by tips48** [comment]
^Oh yes, also that

**Comment by tips48** [comment]
Going to add get this to bleeding if your okay with that

**Comment by oloflarsson** [comment]
Yeah please do and fix the issues you see :)

**Comment by Wolvereness** [comment]
This needs to link to the CB pull.

**Comment by oloflarsson** [comment]
This is to old now and there are better solutions to this already out there. So I'll go ahead and close my own pullreq :)

**Pull request closed without merging**
