### PR TITLE
Added a .equals() function to MaterialData

### PR DESCRIPTION
**Pull request by Edoxile**
Added a .equals() function for MaterialData.

This commit is needed for the CraftBukkit commit https://github.com/Edoxile/CraftBukkit/commit/4dbee3b8b4fc47d0216a86f59b88ec16be8601ee

However, people might find this usefull anyway.

### CODE REVIEW

**Comment by xZise** [comment]
Hey, I'm sorry to bother you again, but unluckily should you also implement `hashCode()` (I recently found in the [java doc](http://download.oracle.com/javase/1.4.2/docs/api/java/lang/Object.html): If you change `equals()` you should change `hashCode()` → [see more](http://www.ibm.com/developerworks/java/library/j-jtp05273/index.html)). I would suggest something like this:

```
public int hashCode() {
    return (type >> 24) ^ (type & 0xFFFFFF) & (data << 24)
}
```

Because the highest type id is at the moment lower than 2²⁴ I thought simply concat both. Maybe there is a better way, but as long as the type < 2²⁴ it is a perfect hash:

```
Byte:  0  1  2  3
Data: --type-- data
```

Fabian

PS: I edit it 13:55 UTC because I failed with the mask :D

**Comment by Edoxile** [comment]
I had an even simpeler idea: since a byte is only 8 bits, I can just bitshift the type 8 bits, and concat that with data. Should work perfectly.

**Comment by Edoxile** [comment]
Stupid me pressing wrong button, sorry :+

**Comment by xZise** [comment]
Yep as soon, as the type id is < 2²⁴ it is a perfect hash. Mine will produce a similar result but will change the hashes for type ids ≥ 2²⁴. Your hash is same, if the data is equals, and the lower 24 bits of the type. But it was only a suggestion, and as long as the type id is not high enough it is same as good as mine.

Fabian

**Comment by Edoxile** [comment]
Just noticed I screwed it up. This isn't going to work, and there are allready two commits. I'm going to close this and reopen with a working one.

**Pull request closed without merging**
