### PR TITLE
Added isArmor & isRepairable methods to Material.java

### PR DESCRIPTION
**Pull request by gmcferrin**
References my ticket at https://bukkit.atlassian.net/browse/BUKKIT-814

### CODE REVIEW

**Comment by RobinvanderVliet** [comment]
You can better add an isTool instead of an isRepairable. ;)

**Comment by gmcferrin** [comment]
The question is what people define as a tool - according to the wiki, tools includes buckets, compasses, maps, etc. The wiki also doesn't list swords as tools.

**Comment by feildmaster** [comment]
We need a better material usage... This enum just doesn't cut it.

**Comment by gmcferrin** [comment]
I completely agree with you feildmaster. You wanna get on IRC & we can discuss?

**Comment by feildmaster** [comment]
I'm always on IRC. Usually. ;)

**Comment by gmcferrin** [comment]
Except for, you know, right now.

**Comment by feildmaster** [comment]
I am on, actually. Just not in #bukkitdev

**Comment by bartenbach** [comment]
I saw this and first thought was this would be a perfect method for an mcMMO issue I spotted...

Then i realized who submitted the pull request in the first place.

**Comment by gmcferrin** [comment]
Anyone?

**Comment by gmcferrin** [comment]
If you're not gonna pull this, it's fine, but you could at least let me know...

**Comment by calda** [comment]
I support this

**Comment by gmcferrin** [comment]
Changed to switch case due to request by @Wolvereness

**Comment by feildmaster** [comment]
I don't think we should pull this. The idea of if a material is "armor," "repairable," or "edible" is flawed.

@Wolvereness can explain it better if need be.

**Comment by gmcferrin** [comment]
The "is edible" already exists, but I can respect that.

**Comment by feildmaster** [comment]
Due to the nature of this PR, and the flawed aspects this creates (Materials are Materials, they are not Armor, Repairable, or Edible. They are Materials used for items/blocks) this will not be pulled.

**Pull request closed without merging**
