### PR TITLE
Added NBT API. Adds BUKKIT-3142

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Technius** [comment]
I think the tags should have Tag before their type in the class name.  Ex: TagCompound instead of CompoundTag.

**Comment by md-5** [comment]
@Technius https://github.com/Bukkit/Bukkit/pull/730#issuecomment-11227433

> I think the tags should have Tag before their type in the class name.  Ex: TagCompound instead of CompoundTag.

I would have to agree on that.

**Comment by feildmaster** [comment]
An api like this, which clearly uses and references minecraft internals... will not be accepted.

An API should have specific use cases, and use it's own methods to maintain and contain what it needs to do (in craftbukkit)

The api should have no sense of what CB uses.

**Comment by BangL** [comment]
@feildmaster https://github.com/Bukkit/Bukkit/pull/730#issuecomment-11227671

> An api like this, which clearly uses and references minecraft internals... will not be accepted.
> An API should have specific use cases, and use it's own methods to maintain and contain what it needs to do (in craftbukkit)
> The api should have no sense of what CB uses.

are you f***ing kidding me? -.-

**Comment by SagaciousZed** [comment]
The API should be designed around what in game needs to be changed. Not around how the server happens to store stuff.

**Comment by Technius** [comment]
Ok, now we _really_ need to get that commit rejected.

**Comment by jjkoletar** [comment]
No, you just need methods to perform specific functions, like set the custom name of an item.

**Comment by hatstand0** [comment]
@jjkoletar https://github.com/Bukkit/Bukkit/pull/730#issuecomment-11228456

> No, you just need methods to perform specific functions, like set the custom name of an item.

Which, oddly enough, I'm not sure this PR allows you to do.

**Comment by Technius** [comment]
@hatstand0 
Wrong.
The name of the item is like this:

Tag of the item stack -> Compound "display" -> String "Name"

**Comment by EdGruberman** [comment]
@hatstand0 It does, but not in a way that makes sense in-game.  You don't open an Anvil to set the NBT data, you set the item's name.  You would do something like ItemMeta.setDisplayName(String name) (as https://github.com/Bukkit/Bukkit-Bleeding/compare/master...itemmeta is currently being worked towards)

I'm not even sure this would work in-game other than to load and save a file to disk.  I suppose you could load a player.dat file with this API, but then you'd have to worry first if that was actually up to date before loading it since in-game player data is not saved to file in real time.  Then you'd have to reload the player file somehow.

I don't think this would even work for items on the ground since it doesn't seem to load region files.  It really seems like just a stand alone NBT feature at most.  With the Configuration classes, I'm not sure why this would be preferred over those.  What exactly is the use case for this?

**Comment by hatstand0** [comment]
@Technius 
And how do I get the item stack's tag without using CB classes?

**Comment by jjkoletar** [comment]
@hatstand0 
That's what the PR should do.

**Comment by Technius** [comment]
@hatstand0 
This PR only adds the NBT API.  It doesn't add NBT access.

**Comment by EdGruberman** [comment]
@Steveice10 I think you are starting to see more clearly why these things are not so simple as a literal implementation of a random comment on the refactor commit.  Just because someone mentions "NBT API" doesn't mean that is exactly what is either being requested or even needed.  Coordination, planning, and understanding needs to occur before simply dropping in classes to see what can be done with them.

Most likely people who mention such things as NBT at all do so because to date they have been forced in to dealing with NMS classes due to the lack of an API in Bukkit to deal with item metadata properly.  Their complaints are driven by a lack of understanding of how APIs work.  If it was all as simple as only getting direct access to the NMS namespace there would be no reason for Bukkit to exist at all.

I saw a conversation with Grum earlier today in IRC where he was indicating even the concept of a Chunk ideally would not be exposed in an API.  Chunks are an internal mechanism for storing world data.  If the API is properly designed, plugins won't ever care about such a construct.

**Comment by EdGruberman** [comment]
@Steveice10 Stick with it!  As I said, you are starting to see more clearly.  That is a big step to take.  Continue to try and help Bukkit with PRs.  If you are interested in continuing to learn, you and Bukkit both can benefit.  I've had plenty of rejected PRs myself and each time I learned something beneficial.

**Comment by dredhorse** [comment]
while I agree to NOT pull this PR or even close it this PR is typical on how to turn away people...

the main reason for closing this PR was (I THINK) that it isn't an API... it is more the part of CB you would write when you had an API allowing access to those NBT files.

what is missing here is guidance and a sane construct on what is included and how into bukkit... after all those years there isn't one.... there is a rough framework, but to many exceptions have been made when the person in charge of pulling liked it.

**Comment by EdGruberman** [comment]
@dredhorse feildmaster gave specific reasons for the rejection.  I've given a specific example (the itemmeta branch work) that shows how this type of interest can be satisfied through an API.  I've also specifically encourage Steveice10 to keep trying.  No one has personally attacked Steveice10 and we are all willing to explain in detail anything further.

Steveice10 indicated he understands more now.  Even in the version change commit Steveice10 said it best, this solution is too "implementation dependent".

There _is_ guidance and an example here.  How could you interpret this scenario as one that turns people away?  The act of denying a submission should not be considered a negative experience.  Please don't assume that closing a PR indicates something bad has happened.

**Comment by feildmaster** [comment]
on a related note, steveice was on IRC earlier and we had a better discussion about this PR. I was glad he made an attempt at making a PR, most people don't even try.

I am more than willing to work with anyone willing to work on an API. I hope I am now clearer than I was before.

**Comment by dredhorse** [comment]
@EdGruberman that wasn't geared to your post
@feildmaster I know that you are.. looks like my edit didn't make it I'm sorry about that.

to rephrase: 

While feildmaster did explain why the PR was closed what I'm missing is that people get more input about why a PR isn't taken into account. You can not except people creating PRs to have the same knowledge like you have.

Ed described it a lot better...

and yes I know that you guys don't have time...

sorry... just forget it...

**Pull request closed without merging**
