### PR TITLE
Add EntityEatEvent

### PR DESCRIPTION
**Pull request by tips48**
Event is called when an entity eats a block. Right now, only sheep call it
Relates to BUKKIT-512

Try two :)

CraftBukkit: https://github.com/Bukkit/CraftBukkit/pull/635

### CODE REVIEW

**Comment by kjhf** [comment]
Call for wolves restoring health too?

**Comment by tips48** [comment]
You mean like when they eat a bone?

**Comment by kjhf** [comment]
No, that would be called by EntityTame, I believe. I mean if a player feeds the wolf food (say porkchop) so the wolf can recover health.

**Comment by tips48** [comment]
Thats a good idea, but not in the scope of this pull as the entity eats a 'block'

**Comment by kjhf** [comment]
Ah, I see. My apologies in that case - I jumped the gun by reading EntityEatEvent ;)

**Comment by tips48** [comment]
Yea..Isn't the event for that EntityHealEvent or whatever?

**Comment by kjhf** [comment]
Not sure if the EntityReganHealth also covers it -- the RegainReason enum comments state that it is for players, despite it being in the entity listener.

**Comment by tips48** [comment]
Moving to bleeding

**Pull request closed without merging**
