### PR TITLE
Added experience orb spawn event.

### PR DESCRIPTION
**Pull request by taufiqkh**
EXPERIENCE_ORB_SPAWN event type added with corresponding ExperienceOrbSpawnEvent class, to be triggered when experience orbs are spawned.

Corresponding CraftBukkit pull request: https://github.com/Bukkit/CraftBukkit/pull/474

### CODE REVIEW

**Comment by halvors** [comment]
What's the point with this? We have the CREATURE_SPAWN event.

**Comment by Rigby90** [comment]
Experience orbs are not Creatures.

**Comment by halvors** [comment]
Yes. But CreatureSpawn could be a more general EntitySpawn event. Then it could be used. Sorry for my misunderstanding.

**Comment by taufiqkh** [comment]
halvors, are you saying that an EntitySpawnEvent subclass of EntityEvent class should be created that is a parent of CreatureSpawnEvent, ItemSpawnEvent and ExperienceOrbSpawnEvent? It certainly makes sense to consolidate some of the logic, (ie. cancelled and location).

On another note, I recognise that in its current state, this change does not allow customisation of the number and breakdown of experience orbs produced when an entity dies. I have considered placing this event just before the orb generation in EntityLiving.aa() and adding get/setExperienceBreakdown methods, but it would be good to get some input. I don't see a lot of value in being able to specify exact breakdowns (eg. 10 experience, broken down into orbs of value 5, 2, 2, 1) but possibly a SINGLE and DEFAULT enum could determine whether it's a single orb for the drop or the default, prime number-based breakdown.

**Comment by taufiqkh** [comment]
Looks like core commits were done between the first and second commit in this. With the overlap in functionality this request doesn't add too much except the orb breakdown, which I don't think is expecially critical.

**Pull request closed without merging**
