### PR TITLE
Added .getExactPermission() method in PermissionAttachmentInfo to get original cased permissions

### PR DESCRIPTION
**Pull request by NodiusC**
This allows developers to get original cased permissions (as in exactly how users typed them in permissions plugin's configs / exactly how developers set them in PermissionAttachments) and will not break Bukkit's permission system nor will it break plugins. Very useful if a plugin were to parse permissions for some info unknown at start.

The TestPlugin that I used to test and its source can be found [here](http://www.nodinchan.com/TestPlugin.jar) and [here](http://www.nodinchan.com/src.rar) respectively.

### CODE REVIEW

**Comment by zml2008** [comment]
You should avoid changing line endings in the same commit as other non-formatting changes
Also, you should't post unofficial CB builds in PR's (or anywhere)

**Comment by NodiusC** [comment]
Ah, okay, let me remove the link.

Also, what did you mean by "changing line endings in the same commit"?

**Comment by zml2008** [comment]
ExpBottleEvent, PotionSplashEvent, SheepRegrowWoolEvent, PlayerVelocityEvent, and TestEnchantment all have their line endings changed in your PR. While the change is correct, it should be in a separate commit to keep actual code changes separate.

**Comment by NodiusC** [comment]
Well, I don't know. I never touched them, Github just thinks that I changed something. :/

Github always think that I commited something even though I didn't. :/

**Comment by drantor** [comment]
What Editor do you use?

**Comment by NodiusC** [comment]
Eclipse.

**Comment by NodiusC** [comment]
Fixed it.

With this bunch of commits, I might as well redo the pull request? :|

**Comment by zerg960** [comment]
Someone once told me about "force push" squashing commits.

**Pull request closed without merging**
