### PR TITLE
A few config changes/fixes/whatnot...

### PR DESCRIPTION
**Pull request by feildmaster**
Happy Holidays.

### CODE REVIEW

**Comment by feildmaster** [comment]
- Saving Configuration will now save in UTF-8
- Loading Configuration will now detect what encoding used, and load accordingly
- Fixed ItemStack Serialization

**Comment by grum** [comment]
Denied because we cannot depend on something bound to the sun implementation, this will not work on OpenJDK. (sun.nio.cs.StreamDecoder)

**Comment by feildmaster** [comment]
@grum Ahh... I didn't realize this. I just copied what InputStream used... I assume they use a different internal operation for OpenJDK.

**Comment by dredhorse** [comment]
also could it be that this causes all kind of issues with foreign characters? depending on os and java versions?

see https://bukkit.atlassian.net/browse/BUKKIT-1466

**Comment by feildmaster** [comment]
To be honest, the internals _should already_ be able to load and save any format... They just _aren't._

**Comment by dredhorse** [comment]
well I save the yaml files myself... as I WANT comments in my configs.

I started just saving them, till the moment people came up with errors when they where using äö etc... I searched and found that you needed to save in UTF-8... did that...

and now people come up with issues that those files can not be loaded...depending on the os / java.

OpenJDK is nice and AFAIK it is mainly used on MAC but if they can't support the standard that is THEIR problem.

We need a way to successfully save / load yaml files with foreign characters.. 

I could probably write my plugin in a way that if the load fails because of issues that I than read the file completly and save it again in a different format, but a lot of other people are running into issues now.

It looks like SnakeYaml is causing these issues... http://jira.codehaus.org/browse/JRUBY-6200 (read a little through)

some more info http://jira.codehaus.org/browse/JRUBY-6317

**Pull request closed without merging**
