### PR TITLE
Only forward assignable events to EventExecutor; Fixes BUKKIT-3487

### PR DESCRIPTION
**Pull request by EdGruberman**
When registering an event with the EventHandler annotation method an
anonymous EventExector is created that filters events from the
registration class's HandlerList.  This prevents an EventHandler method
from receiving an event it is not listening to.

This commit mirrors that EventExecutor wrapper approach by wrapping the
EventExecutor passed in with another EventExecutor which filters classes
the original EventExecutor did not register for.

[BUKKIT-3487](https://bukkit.atlassian.net/browse/BUKKIT-3487)

### CODE REVIEW

**Comment by md-5** [comment]
Awesome!

**Comment by Wolvereness** [comment]
This is more a method contract issue than a bug. It behaves as expected; our current contract is that the executor is supposed to filter any events it does not want.

**Comment by md-5** [comment]
But it doesn't seem to make sense that you register BlockBreakEvent.class and get BlockExpEvent.class, and you can't cast a BlockExpEvent to a BlockBreakEvent.

**Comment by feildmaster** [comment]
@md-5: The method only adds the handler to the specified event's handlers. You must implement the filters yourself.

**Comment by EdGruberman** [comment]
That needs to be documented in the Javadoc.  It's extremely unintuitive based upon the annotated EventHandler approach and the existing Javadoc.

**Pull request closed without merging**
