### PR TITLE
Allows PlayerArmAnimation to be cancelled.

### PR DESCRIPTION
**Pull request by desmin88**
Makes PlayerArmAnimation event implement cancellable.

CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/402

### CODE REVIEW

**Comment by iffa** [comment]
Will it not show the animation? :P

**Comment by desmin88** [comment]
It wont show the animation to all other players around the player in the event

**Comment by grum** [comment]
No tabs please

**Comment by desmin88** [comment]
@grum
Fixed.

**Comment by desmin88** [comment]
Ever going to be pulled?

**Comment by EvilSeph** [comment]
Applied manually, thanks!

**Pull request closed without merging**
