### PR TITLE
Created Heal

### PR DESCRIPTION
**Pull request by MrInspectorDev**
Heal command added.

### CODE REVIEW

**Comment by Wolvereness** [comment]
Commands in Bukkit are either _Bukkit_ related (like /reload) or default Minecraft ones. See:

http://minecraft.wikia.com/wiki/Commands
http://minecraft.gamepedia.com/Commands

You should also review http://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

It also doesn't work...

**Comment by MrInspectorDev** [comment]
I've got a question, so you're not accepting the /heal command @ all? like you don't want to add /heal? Sorry I'm a bit shaky :P

**Comment by MrInspectorDev** [comment]
Sorry, I'll make another pull request if you want for the heal, I know what I did wrong..

**Comment by daboross** [comment]
@MrInspectorDev You also made it a vanilla command as apposed to bukkit command I think, not sure though.

Also you should read through the CONTRIBUTING.md file and redo the pull request accordingly.

**Comment by MrInspectorDev** [comment]
I know daboross, I made another pull request, if you can check that out, I was confused, the other one should work, right?

**Pull request closed without merging**
