### PR TITLE
spawn() and delete()

### PR DESCRIPTION
**Pull request by nodren**
This will be combined with a similar pull request in the CraftBukkit repo.

The purpose of this is for invisibility and cloning functionality of a player.  spawn() will copy a player or make them appear if they were already delete()'d.  delete() will make them disappear.

### CODE REVIEW

**Comment by EvilSeph** [comment]
Ticket reopened because GitHub ate our pull requests.

**Comment by EvilSeph** [comment]
We'd like something like this in Bukkit, except it should deal with all entities as a whole and not just players.

**Comment by nodren** [comment]
well, delete() can be moved up to Entity, as the packet sent only requires an entity id to be passed.  however, spawn() would need to be in EntityLiving and overloaded in EntityHuman, as there are two different packets depending on the kind of entity

see: https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/Packet20NamedEntitySpawn.java#L19

and: https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/Packet24MobSpawn.java#L21

and: https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/Packet20NamedEntitySpawn.java#L19

**Comment by Dinnerbone** [comment]
We're going to look at other ways of doing this, sorry

**Pull request closed without merging**
