### PR TITLE
Added callAsyncEvent() for thread synchronisation

### PR DESCRIPTION
**Pull request by Raphfrk**
This method allows another thread to call events.

They are added to a queue and are dispatched when the main thread is free (a delay can be specified).

Events are stored in a TreeMap for quick polling so as to reduce server load.  The main thread must call the poll method at regular intervals.

There is also a corresponding craftBukkit (one line) pull.

This updates both the PluginManager API and also the SimplePluginManager file.

### CODE REVIEW

**Comment by Raphfrk** [comment]
Btw, is there an expectation that the a multi-world server would have 1 thread per world?

On that basis, the API might be improved by adding a getWorld() method to the Event class.  It would return null unless a sub-class overrides it.

An event with a null world would be sent to all threads, while one with a specific world would only be sent to that world's thread.

A queue would be required for each thread.  However, that would be for the future.  In any case, a multi-threaded server like that would require some kind of inter-thread syncing.

**Comment by Mattie** [comment]
I just noticed Java has a really snazzy DelayQueue class. http://download.oracle.com/javase/1.5.0/docs/api/java/util/concurrent/DelayQueue.html

Using this class would be much simpler, thread-friendly, etc. Any chance you could implement it using that? Anything it doesn't handle for what we want here? (I can't think of anything.)

**Comment by Raphfrk** [comment]
Done.  It has pretty much the same function, but I guess it is safer to implement it with the standard classes.

**Comment by StoneLegion** [comment]
Very nice looking forward to this being added.

**Comment by Mattie** [comment]
Likewise, looks solid, Raphfrk. Hopefully the dev team either accepts this or quickly clarifies the design they want for these. I look forward to moving forward. :)

**Pull request merged**
