### PR TITLE
Configuration class fills empty nodes with "null" when saving

### PR DESCRIPTION
**Pull request by rcjrrjcr**
Some users of the Permissions plugin have complained about this.
See http://forums.bukkit.org/threads/admn-dev-permissions-v2-6-phoenix-now-with-real-multiworld-permissions-670.5974/page-112#post-200972 , and http://forums.bukkit.org/threads/admn-dev-permissions-v2-6-phoenix-now-with-real-multiworld-permissions-670.5974/page-112#post-201148 .

The fix was to extend SnakeYAML's Representer class and prevent nulls from being written as "null" and write nothing. This commit also prevents empty lists and maps from being written too.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
While this is not precisely necessary, I do think null is better represented by nothing rather than the string "null". That is, in this:
<code>key: </code>
key is null, right? So writing it back out like that seems preferable.

**Comment by rcjrrjcr** [comment]
That's what it does.

**Comment by CelticMinstrel** [comment]
Yeah, I gathered.

**Comment by EvilSeph** [comment]
Applied manually, thanks!

**Pull request closed without merging**
