### PR TITLE
Added EntityPotionEffectChangeEvent

### PR DESCRIPTION
**Pull request by turt2live**
Long name, I know. This PR (and the associated Bukkit PR) is likely not going to get pulled, I'm aware of that.

I kinda meant for this PR to show what kinds of things are to be expected of an event like this.

Associated CraftBukkit Pull Request: https://github.com/Bukkit/CraftBukkit/pull/926
Main ticket: https://bukkit.atlassian.net/browse/BUKKIT-2817
Plugin code used to test: http://pastebin.com/SU5Yujak

USE CASE:
For me personally, I would like a way to stop certain players from gaining beacon effects, and after much research (well, not really...) it was found they were just potion effects.

This new event allows plugin authors to better control what potion effects players (and maybe entities, if this were to be expanded) can, and cannot, have. 

Although it is noted that you are unable to cancel a loss of an effect, this is described in the commit as "You cannot stop time". 

Suggestions are welcome, I will do as much as I can to help ensure this (or something like it) ends up in Bukkit so I can continue my plugin easily. 

(PS: I'm sure a lot of other developers would love this event as well, like WorldGuard, and region plugin, permissions plugins, etc, etc...)

EDITS:
- Renamed event from PlayerPotionEffectChangeEvent (player event) to EntityPotionEffectChangeEvent (entity event)
- Added ambient flag
- Added (true) duration and amplifier access 
- getLocation() = The location of the event.
- Added firings for mobs (wither-like mobs, witches, zombies, etc)

### CODE REVIEW

**Comment by LB--** [comment]
I don't see anything relating to the Ambient flag, which is set to true for beacon effects (this is that patch note "made beacon particle effects less intrusive on the screen"). If you made this to deal with beacons, maybe you should add a way to check that Ambient flag ;)

**Comment by turt2live** [comment]
I wasn't even aware of an ambient flag...

I shall look into this.

Edit: I'm working on a few things, commits will be squashed when I'm done
Edit2: Done.

**Comment by turt2live** [comment]
There :)

**Comment by LB--** [comment]
I approve :+1: can even be used now to make drinking regular potions ambient, which is quite nice when you drink long-lasting potions.

**Comment by turt2live** [comment]
Yup :) Hopefully it gets pulled...

Or something like it (meaning very close...)

**Comment by turt2live** [comment]
Added: 
- getLocation() = The location of the event.

getLocation() returns the following:
if BEACON then beacon block location
else player location (unless it's a thrown potion, then it is the potion's location)

**Comment by turt2live** [comment]
Broken. Updating

**Comment by lol768** [comment]
I'm in support of this being added :smile:

**Comment by cltnschlosser** [comment]
The ambient flag can already be added to potion effects. but i dont even notice a difference. anybody?

**Comment by LB--** [comment]
When it is put on the player, it makes the particles less visible like with the beacon effects. It is accepted on potions and splash potions but it doesn't carry over when you drink/throw the potion.

**Comment by cltnschlosser** [comment]
So the current method doesnt work? And we would need to add this effect through an event?

**Comment by LB--** [comment]
It's a Vanilla bug, nothing to do with Bukkit or any plugin.

**Comment by cltnschlosser** [comment]
Okay, i have a potion command plugin, and i noticed the ambient flag and wanted to add it in, but didnt notice a difference.

**Comment by LB--** [comment]
It will only make a difference if the effect is set directly on a player - if it is set on a potion or splash potion it currently has no effect, though Minecraft requires the tag to be of the correct type and it even saves it in the chunk data, which is why we know this tag is allowed in the first place.

**Comment by br45entei** [comment]
I have a pretty urgent need for this! I thought that there would already be an event for handling when a potion effect were added/changed on a player, but this is still not the case as of craftbukkit-1.7.2.R0.3! ... I hope this gets reconsidered! Here's the code I'm hoping to get to use:

```
public void onEntityPotionEffectChangeEvent(org.bukkit.event.entity.EntityPotionEffectChangeEvent evt) {
    Player player = evt.getPlayer();
    savePlayerPotionEffects(player, player.getWorld(), player.getGameMode());
}
```

**Comment by turt2live** [comment]
@br45entei This PR has been closed and a new one opened by another member

**Pull request closed without merging**
