### PR TITLE
Add playTamingAnimation(bool successful) to Tameable

### PR DESCRIPTION
**Pull request by CruzBishop**
Bukkit implementation of Bukkit/CraftBukkit#622

### CODE REVIEW

**Comment by main--** [comment]
This is related to #400. We might want to merge these two pull requests.

**Comment by CruzBishop** [comment]
Hmm. Yeah, it is

I guess we'll have to see what @Dinnerbone says :\

**Comment by iffa** [comment]
What does this allow

**Comment by main--** [comment]
@iffa You know the hearts or the smoke that's spawned when you try to tame a wolf and it succeeds/fails? With this PR, plugins can now manually trigger these particles.

**Comment by Dinnerbone** [comment]
Closing, see CB comments.

**Pull request closed without merging**
