### PR TITLE
Simplification

### PR DESCRIPTION
**Pull request by BalloonChamp**
Hi fellow Bukkitor/Glowers! So As a server owner I like doing things simply, and I know that the Essientials plugin does this, but could you change the default commands, like this

instead of typing /defaultgamemode, type/dgm 

instead of typing /gamemode, type /gm

And so on...

### CODE REVIEW

**Comment by gabizou** [comment]
Yeah... for a project that isn't being maintained, this PR doesn't belong.

**Comment by BalloonChamp** [comment]
What do you mean?

**Comment by rioricorick** [comment]
Could it not be maintained by volunteers?

On Mon, Dec 28, 2015 at 2:44 PM, BalloonChamp notifications@github.com
wrote:

> What do you mean?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bukkit/Bukkit/pull/1117#issuecomment-167663273.

## 

Richard M. Garber
Principal Software Engineer
520-538-6454 Office
520-604-2228 Cellular

**Comment by BalloonChamp** [comment]
I want to fork this project, but I also want the fork to be a dependancy to my GlowstonePlusPlus fork and im not sure how to do that

**Comment by gabizou** [comment]
[The Bukkit Project](https://bukkit.org/threads/an-independent-goodbye.310086/) was abandoned last year, this repository hasn't had any actual updates since.

**Comment by BalloonChamp** [comment]
Im not a big java person, but Im going to make a server like bukkit that supports all bukkit plugins, and also supports MCPE clients

**Comment by rioricorick** [comment]
Are developers still allowed to fork and use it?

On Mon, Dec 28, 2015 at 2:48 PM, Gabriel Harris-Rouquette <
notifications@github.com> wrote:

> The Bukkit Project
> https://bukkit.org/threads/an-independent-goodbye.310086/ was abandoned
> last year, this repository hasn't had any actual updates since.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bukkit/Bukkit/pull/1117#issuecomment-167663751.

## 

Richard M. Garber
Principal Software Engineer
520-538-6454 Office
520-604-2228 Cellular

**Comment by BalloonChamp** [comment]
IDK, I assume so.

**Comment by rioricorick** [comment]
Yes me to! Enjoy!

On Mon, Dec 28, 2015 at 2:49 PM, BalloonChamp notifications@github.com
wrote:

> IDK, I assume so.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bukkit/Bukkit/pull/1117#issuecomment-167663914.

## 

Richard M. Garber
Principal Software Engineer
520-538-6454 Office
520-604-2228 Cellular

**Comment by gabizou** [comment]
> Are developers still allowed to fork and use it?

Of course. That's why the Glowstone (and Glowstone++) project has continued.

**Comment by rioricorick** [comment]
Awesome! Thanks

On Mon, Dec 28, 2015 at 2:50 PM, Gabriel Harris-Rouquette <
notifications@github.com> wrote:

> Are developers still allowed to fork and use it?
> 
> Of course. That's why the Glowstone (and Glowstone++) project has
> continued.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bukkit/Bukkit/pull/1117#issuecomment-167664044.

## 

Richard M. Garber
Principal Software Engineer
520-538-6454 Office
520-604-2228 Cellular

**Comment by BalloonChamp** [comment]
So how do I fork this project, but I also want the fork to be a dependancy to my GlowstonePlusPlus fork?

**Comment by BalloonChamp** [comment]
Bukkit was abandoned, but Im using Spigot on my server. All I want Is the Spigot source code!

**Comment by mbax** [comment]
What on Earth is going on.

**Comment by Tzky** [comment]
> Are developers still allowed to fork and use it?

Bukkit Yes, CraftBukkit No. Simple as that.

**Comment by ryantheleach** [comment]
For the record, server implementations of bukkit can do this themselves, there is absolutely no need for the Bukkit API to change for this.

**Pull request closed without merging**
