### PR TITLE
Added ServerReadyEvent and subevent ServerReloadEvent

### PR DESCRIPTION
**Pull request by feildmaster**
A simple event, which has been requested quite often. I believe this is a simple and working solution.

Off topic: I kind of want to know why this one worked as one commit, and not the CraftBukkit pull.

CB Pull: https://github.com/Bukkit/CraftBukkit/pull/491

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Use case?

**Comment by feildmaster** [comment]
Use case how? For ServerReload? I didn't feel like adding arguments to it. I actually had that way coded as well, but then used subevent.

I'm still a little confused as to "why" though.

**Comment by Dinnerbone** [comment]
Sorry, that's to be read as, "what is the use case for these events"? What are examples of these being used?

**Comment by iffa** [comment]
If you want to make a sexy logging plugin

**Comment by kmoses22** [comment]
Also if you want to execute something as soon as all other plugins are loaded.

**Comment by feildmaster** [comment]
Ah, I see. Iffa asked that as well.

For tasks that need to be called after all the plugins were loaded, Say:

A plugin has to update it's values, based on plugins enable status (PailPlus), Instead of calling a "delayed task," call this event.

There's probably more cases. I know "Pail" needs to know when a server is loaded/reloaded.. and some other plugins like to run various functions after all other plugins have been loaded (I thought I made a few more that had to, maybe I found hacky work-around). This would be a simple convenience event.

I'd love if I kept note of the people that wanted the event though. I know I've seen quite a few requests.

**Comment by Dinnerbone** [comment]
@escapeNT Then whatever problem you're trying to fix with that, you're going the wrong way about it.

@fieldmaster Same as above. If you need to do something based on when another plugin is loaded... listen for the event for it being loaded.

**Comment by feildmaster** [comment]
@Dinnerbone : But I can't get the results of if the plugin was enabled fully. PailPlus offers dynamic Enable/Disable of plugins. It also (wants to) disable plugins that weren't enabled before reload. It has to be called after all plugins have been loaded.

I also run (multiple) tasks on "server start" by making a "delayed sync task." But an event is so much nicer, no?

**Comment by CelticMinstrel** [comment]
The use case would be needing to do some special thing when certain plugins load, and then doing some other special thing if none of those plugins load.

**Comment by feildmaster** [comment]
This was closed on CraftBukkit so I'll close it here.

**Pull request closed without merging**
