### PR TITLE
Update src/main/java/org/bukkit/event/Event.java

### PR DESCRIPTION
**Pull request by petterroea**
It wrong method name?

### CODE REVIEW

**Comment by Top-Cat** [comment]
I'm not sure you can say a method name is wrong and as this is in the api (bukkit) changing it is likely to do more harm than good.

**Comment by gmcferrin** [comment]
Yeah... no. There's no such thing as the "wrong" method name, unless you're using the wrong name when calling it in your code. This method could be called "getAllTheHandlersForThisEvent" and would still be just as "right".

**Comment by jrtc27** [comment]
Agreed. The method name is plural, implying some form of array/list being returned. This is a breaking change without much point to it,

**Comment by feildmaster** [comment]
This breaks many plugins, and will not be renamed. The current name is fine.

**Comment by petterroea** [comment]
(Sorry, found the error that caused me to trace back and find this)

**Pull request closed without merging**
