### PR TITLE
Events Refactor

### PR DESCRIPTION
**Pull request by zml2008**
This pull request makes event registration and handling faster and more flexible for plugin developers writing plugins and adding custom events. Events are registered in a class implementing Listener with methods that have an EventHandler annotation, which is then registered with the plugin manager through getServer().getPluginManager().registerEvents(Listener, Plugin). An example of a listener class is available at https://gist.github.com/1280163 (from WorldEdit). This method is inspired by the event registration in @sk89q's server plugin. The other major change in this pull request is faster event handling. HashMap lookups are eliminated when calling events, being replaced with per-event HandlerLists and getters. I've gotten over 10 million events processed per second with this system. This change is the only change that immediately breaks plugins. Any plugin that has custom events will have to add a few lines to their custom events to make them work with the fastevents system.

```
private static final HandlerList handlers = new HandlerList();
public HandlerList getHandlers() { return handlers; }
public static HandlerList getHandlerList() { return handlers; }
```

Otherwise, events and plugins should continue to work as they did previously in non-updated plugins until the clases and methods I deprecated are removed.

### CODE REVIEW

**Comment by Afforess** [comment]
One of the other features of @lahwran's fast event system was the ability to create and use singleton events for frequent events (_cough_onPlayerMove_cough_) and avoid the penalty for creating and destroying an event object each time. Now, the downside is that the event becomes single threaded in nature, but in this case, that's not an issue. It would be nice to see a few of the more common events become singletons.

onVehicleMove is probably another good candidate.

**Comment by Rigby90** [comment]
Looks interesting.

Quick thing - If I recall @EvilSeph and such don't want @author tags.

I think this part is missing from the guidelines though, will try and pester someone to include it if it is so.

**Comment by lahwran** [comment]
there are @author tags in bukkit last I checked, I think in PlayerInteractEvent

**Comment by Rigby90** [comment]
@lahwran -- Yeh they are slowly being removed, @Dinnerbone had a huge commit not long ago which removed a bunch from Bukkit.

**Comment by zml2008** [comment]
Also, a test plugin for these events changes is available at https://github.com/zml2008/eventtest

**Comment by t3hk0d3** [comment]
/sign

Sad, but i think this PR will have same destiny as https://github.com/Bukkit/Bukkit/pull/279 :(

**Comment by fullwall** [comment]
Support for clean use of annotations, and possible speed improvements. Hopefully this gets pulled.

**Comment by petteyg** [comment]
vote++

**Comment by Dinnerbone** [comment]
Style guidelines are not uncommon (to not have any is actually very rare) in pretty much every project, open source or not.

**Comment by lahwran** [comment]
I believe git blame makes up for that, doesn't it? I mean, bukkit commits most pull requests manually, so git blame is less useful, but it can be used to look up commit messages, which contain the original authors...

**Comment by zml2008** [comment]
Does my PR really have to be alta's complaint forum? I don't mind not
having @author tags, as long as that policy is applied consistently.

**Comment by lahwran** [comment]
grum did not revert the dynamic command registering because it was inherently a bad idea, but because bukkit is not set up for it.

**Comment by ZachBora** [comment]
If this makes Events faster I'm all for it. But is it the event that are slow or what the events do... hmm...

**Comment by petteyg** [comment]
If nothing else, the ability to clear registrations could get a few more dead references left by /reload to go away...

**Comment by zml2008** [comment]
In the past event registrations could be removed all at once in a full
reload. I just added per-plugin event listener removal (for individual
plugin reloads, etc).

**Comment by tips48** [comment]
Looks interesting!

**Comment by fouram** [comment]
I'd love to see this in the bleeding edge builds - I can't check from where I am now - is anyone working on this?

**Comment by zml2008** [comment]
Updated for recent Bukkit changes

**Comment by Dinnerbone** [comment]
callEvent broke plugins that used it. I've reverted that back to normal. I'm also cleaning up some style issues, but I think this is a keeper.

**Comment by feildmaster** [comment]
Will love this to be pulled.. ^^

**Comment by Dinnerbone** [comment]
Okay this breaks plugins in its current form. I found this out by CommandBook, of which zml is an author of. :D

Let's see how to avoid that!

**Comment by zml2008** [comment]
I'd expect CommandBook to break because it uses custom events. The small bit of boilerplate at the bottom of each event is needed for the fast events system to work.

**Comment by Dinnerbone** [comment]
I fixed the issue, custom events now work fine. This should now be 100% backwards compatible, but I'm still testing it to be sure.

**Comment by zml2008** [comment]
Potential duplicates are #278 and #279

**Comment by grum** [comment]
Has been handled in Bleeding. You'll see it soon. Thanks!

**Pull request closed without merging**
