### PR TITLE
Added a refill method to the BlockDispenseEvent.

### PR DESCRIPTION
**Pull request by rrama**
Refills the dispenser with the item dispensed.

### CODE REVIEW

**Comment by jrtc27** [comment]
Is this really necessary?

**Comment by olliestanley** [comment]
Is there any reason not to have it? It's opinions like that which make Bukkit more limited / less convenient to use than it needs to be.

**Comment by jrtc27** [comment]
Well it's not like you can't register for the event and manually set the contents...

**Comment by rrama** [comment]
It was just in there with the things that I was going to add to the API. It was the first one ready and fit to be added, for obvious reasons.

**Comment by turt2live** [comment]
Potential duplication with this commit...

Make 12 (or however many) plugins that all call refill();

You now have 11 items extra.

**Comment by jrtc27** [comment]
The man makes a good point.

**Comment by rrama** [comment]
Very good point. Should probably make a setRefill(boolean) and an isRefill(). And make the setRefill(boolean) also not take place unless event is not canceled. This will make the refiller even more needed in the API to stop more than one plugin manually refilling.
This is what I love about the pull request system.

**Comment by amaranth** [comment]
Why not just clone the item and dispense the clone if you don't want the dispenser to lose the item? Also, the argument "is there any reason not to" is horrible, especially while talking about API. API, generally, cannot be taken away but only added to. This means every addition should go through extreme amounts of scrutiny.

**Comment by rrama** [comment]
Woops forgot to update people on my progress, I sorta gave up because the whole dispense buckets of water wasn't working. I looked in the code and everything has the least imaginative names possible (e.g. a was for a bucket and b was the item etc (just an example)). So I got confused how the water even get's dispensed or taken  back in and gave up. Shall I just commit what I got and maybe someone could just edit it for the buckets?

**Comment by riking** [comment]
If you still want this to be merged, you need to fix some things:
**First, check whether this functionality has been included** in the last half year.
I'm going to recommend abandoning the idea of implementing this wholly in Bukkit, and that you make a CraftBukkit PR that has the same functionality as that `setRefill(boolean) / isRefill()` suggestion.
You need a Leaky ticket.

**Comment by amaranth** [comment]
You're meant to be able to do this by modifying the ItemStack that gets dispensed or modifying the inventory after the event. If these aren't working file tickets and submit PRs for them, don't add new API to work around a bug.

**Pull request closed without merging**
