### PR TITLE
Wolf interface update - corresponds to methods added by my Craftbukkit Pull request

### PR DESCRIPTION
**Pull request by mikeprimm**
Adds methods for accessing the 'tame' state data on a Wolf, as well as the 'owner' state data.

Should NOT be accepted until the corresponding CraftBukkit request has been accepted.

### CODE REVIEW

**Comment by mikeprimm** [comment]
Tied to push https://github.com/Bukkit/CraftBukkit/pull/250 on CraftBukkit - that push needs to go first (or at the same time).

**Comment by CelticMinstrel** [comment]
Note: There's another pull request [related to this](https://github.com/Bukkit/Bukkit/pull/183) which may be superceded by it.

**Comment by mikeprimm** [comment]
This is now dependent upon pull request https://github.com/Bukkit/CraftBukkit/pull/255 - the previous dependency was closed for the sake of cleaning up the commits.

**Comment by mikeprimm** [comment]
Added feature request with link back to this pull (and 255 on CraftBukkit) - http://leaky.bukkit.org/issues/682

**Comment by mikeprimm** [comment]
Synced up with 1.5 code base - no changed actually needed on Bukkit side

**Pull request closed without merging**
