### PR TITLE
added getPlayer(UUID uid)

### PR DESCRIPTION
**Pull request by ghost**
This allows getting player from server by UUID.  Without this method Plugins must call getOnlinePlayers() and search the returned list for the player with UUID, uid.

### CODE REVIEW

**Comment by Wolvereness** [comment]
https://github.com/Bukkit/Bukkit/blob/master/CONTRIBUTING.md

Judging by the implementation and documentation, this isn't useful; player names would be used instead.

**Comment by ghost** [comment]
I'm not sure why this is not useful as any plugin that stores player data will need to switch to using the player's UUID instead of player name in order to avoid problems caused by player name changes.  Please explain.

Thanks.

**Comment by Wolvereness** [comment]
> Please explain.

That's exactly what _you_ need(ed) to do.

**Comment by ghost** [comment]
Oh. Completely missed the guidelines for commits.  I'm guessing I need to submit a new pull request once the request conforms to the guidelines, or should I simply update this request?

**Comment by Lunaphied** [comment]
Yes.

**Comment by ghost** [comment]
There are two questions there which one is the yes for?

**Comment by Lunaphied** [comment]
Submit a new PR conforming to the guidelines.

On Fri, Dec 6, 2013 at 11:10 AM, Renlar notifications@github.com wrote:

> There are two questions there which one is the yes for?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Bukkit/Bukkit/pull/980#issuecomment-30011114
> .

## 

Starbuck Johnson, Java Developer
www.modwiz.com | starbuck@modwiz.com

**Pull request closed without merging**
