### PR TITLE
BlockFace adjustments for "new" axes orientation; BUKKIT-1567

### PR DESCRIPTION
**Pull request by EdGruberman**
I'm sort of in shock this wasn't caught until now.

Big thanks to AlphaBlend for identifying the issue and opening the ticket!

### CODE REVIEW

**Comment by MisterVector** [comment]
The ticket is here. https://bukkit.atlassian.net/browse/BUKKIT-1567

**Comment by feildmaster** [comment]
Actually, this is already known... This commit only fixes a portion of the problem though.

**Comment by MisterVector** [comment]
It is a breaking change, I know.... I'm not certain how correcting it would even affect our own plugin. I don't think it would do too much though, but you never know...

**Comment by feildmaster** [comment]
It's not breaking. It's "fixing" a break. ;)

**Comment by EdGruberman** [comment]
@Wolvereness made the argument in IRC last night with us that it's "breaking" in that other plugins might be compensating for this broken nature.  Fixing this break, might then break those plugins.

I can't seem to agree with him on the caring about that though.  I would think all plugins would be highly interested in Bukkit reporting valid data as much as possible and gladly work to correct their plugins also to align with valid data.

@feildmaster what other related issues are there to the axes realignment?  Is it documented somewhere?

**Comment by mikeprimm** [comment]
... other than the fact that it does break the behavior of everything that does use it (I mean, its ALWAYS been this way, even back in the 'Notch says the sun rises in the North' days....with his 'fix' being to move the sun to rising in what he claimed was always East).  I guess my main concern here, as with many breaking changes, is the 'problem' really a practical problem that needs to be solved.... I know it'll break some stuff, but I'm at a bit of a loss to see what it fixes (beyond a programmer-visible symbol that could have just as easily been "X_PLUS" or "Z_MINUS").

**Comment by MisterVector** [comment]
I have adjusted my own values for the feature I'm working on. I like the fact that I'm working with valid values, and not false ones, or values that have remained the same despite a change in a system that required a second change, but no change was made.

This pull would be much appreciated.

**Comment by EdGruberman** [comment]
@mikeprimm This enum's purpose is to simplify magic numbers.  If the magic numbers are only obfuscated by it, I'm not sure it serves a purpose and I agree, X_PLUS and Z_MINUS would be actually better.

**Comment by MisterVector** [comment]
Also, a user to the wiki page for data values on blocks like ladders / signs / chests might attempt to implement this in a plugin, and come up with wrong values, if they are using the BlockFace class.

This is very mis-leading as a result.

**Comment by mikeprimm** [comment]
Just to more make my point about 'unintentional consequences', see https://github.com/Bukkit/CraftBukkit/blob/master/src/main/java/net/minecraft/server/BlockFlowing.java#L136.  In this case, the values used are quite important, as they influence what does and does not work ('quirks' that folks heavily depend upon in things like mob grinders and the like - behaviors sometimes referred to as the 'South-East Rule', previously known as the 'South-West Rule').  Even in the CB code, we need to review (and, in this case, fix) the code to prevent breaks and/or unintentional behavior changes due to what essentially is a fix for an otherwise irrelevant inaccuracy.  I'm not arguing that the change isn't 'more correct' - I just question whether the problem it solves is more important than the problems it creates.

**Comment by EdGruberman** [comment]
@mikeprimm Thank you for clarifying.  I incorrectly assumed the enum wasn't internally used. I should have checked.

I definitely agree there is more to this puzzle than this PR addresses.

For the record: there are 392 references to BlockFace in both Bukkit and CraftBukkit. omg.jpg

I think @Wolvereness suggested a new enum like StrictBlockFace... I foolishly groaned and disregarded the idea initially, but I almost wonder if that doesn't make more sense now?

**Comment by mikeprimm** [comment]
WOW - that's more than I would have guessed!  I was familiar with the one I cited only because I was doing work on some of the block physics code just recently, and I was aware of SOME others :)

If nothing, I think adding comments for each value to the effect of "This is now X, relative to sunrise and the minimap" would help with any developers that weren't already quite familiar with the quirks (or just don't need to care).  I haven't reviewed the public interfaces to see how practical a parallel interface would be (e.g. ProperFace getProperFace(), with a new ProperFace enum that would trivial map to/from the old).

**Comment by EdGruberman** [comment]
What about this latest commit?  Is this too crazy?

It combines with the existing enum in I think a fairly intuitive (as much as it'll probably get anyways) way.  I don't believe it breaks anything, and grants developers the tools to do their own translation if desired.

The biggest problem I had with the logic is the SELF value.  It almost doesn't belong.  I think the tri-state Boolean (true/false/null) value of sunBased is the most straight-forward solution to compensate for that without doing something more major like a dedicated CoordinateSystem enum or some such.

**Comment by mikeprimm** [comment]
It'd work for input side - but it creates big headaches for output (that is, if I get an event that tells me something happened on some face of a block, which one do I return (as Bukkit) or expect to have returned (as a plugin dev).  Lots of ambiguity that creates breaks in equivalence checks (e.g. if (event.getClickedFace() == Face.NORTH) doesn't match with a returned Face.SUN_BASED_EAST, even though its the same face; similar issues in switch statements).

**Comment by EdGruberman** [comment]
Well the concept was to add optional functionality if desired.  Developers could convert if they were aware and needed it.  Bukkit would simply continue to use the original system by default without any other changes.

Or is your point that a newer enum would make more sense to clarify what values Bukkit is returning?

You do bring up a good point about the == comparison though.  Perhaps an .equals() method override would be appropriate if a developer truly wanted to compare faces across coordinate systems?  That would still return as expected for original system comparisons and additionally provide comparison capability for the newer sun-based system.

**Comment by mikeprimm** [comment]
Still a bit concerned about the solution exceeding the problem - adding a need to use equals() on an enum kind of makes it not an enum anymore (and doesn't help switches).  Unfortunate weakness of java's enums versus C's is the fact that you cannot alias the same value with a second symbol, and I'm honestly more worried about folks having bugs and/or questions because of a kind of funky use of an enum than I am about the unfortunate-but-simple-and-bounded issue that Face.NORTH happens to refer to what is east relative to the sun.  I suppose we could add a true orientation enum 'TrueBlockFace' that could have methods on BlockFace (and vice versa) for returning the alternative (e.g. BlockFace.NORTH.trueFace() returns TrueBlockFace.EAST) - leave the internals alone, but kind of have the new enum and associated method on BlockFace to 'self-document' the behavior....

**Comment by EdGruberman** [comment]
Well a whole new enum seems a "larger" solution to me, but I see your point.

I think the equals() makes sense when you are comparing multiple values of an enum to determine equivalence, but I also agree it'd be very intuitive to have a BlockFaceSun.equals(BlockFace) type of syntax.  And yes, a BlockFace.toBlockFaceSun() and BlockFaceSun.toBlockFace() methods would also accomplish translation and probably be more intuitive.

Well, I tried at least... ;)

**Comment by MisterVector** [comment]
What crucial code exists in CraftBukkit/Bukkit that relies on specific BlockFace directions? Also, that when rotated 90 degrees to the left to obtain the true direction in accordance with vanilla minecraft, what problems can arise as a result?

**Comment by jrtc27** [comment]
@AlphaBlend Plugins linking against the old version of the enum.

**Comment by feildmaster** [comment]
Instead of all the new methods... I totally would have preferred breaking the plugins for an updated API...

**Comment by MisterVector** [comment]
That's what the new event system did as well...

**Comment by EdGruberman** [comment]
@feildmaster I agree, screw the plugins.  However, who is going to check all 392 references and update those as appropriate to ensure Minecraft quirks remain as they have been?  If you don't, it's akin to what Notch did to all of us by shifting our worlds 90 degrees just so handheld maps line up as expected... :/  I don't want to encourage that type of decision making.

**Comment by mikeprimm** [comment]
Without arguing how good/bad the event system break was, at least one can justify the notion that it served a functionally beneficial purpose (in that it resulted in the event system being faster and more efficient).  With respect, if this enum had said Z_PLUS instead of NORTH back when it was coded last year, we wouldn't be discussing this - this isn't a FUNCTIONAL issue, only one of source level syntax.  "Fixing" it offers no potential for functional improvement (actually, quite the opposite) - only the point that we might find some aesthetic satisfaction that a programming symbol's name matches what we think it should be now (and some 'self-documentation' for a few potential future plugin coders that happen to actually need to care about which value is which).

**Comment by EdGruberman** [comment]
An enum's primary purpose is to increase intuition/readability of the code.  If we didn't care what direction was NORTH, we'd just use as you suggest Z_PLUS, or no enum at all.  It'd be as bad as using magic numbers everywhere.  As it currently stands, this enum is at best misleading.  It is failing its primary purpose.

However, fixing it properly (adjusting/compensating for all 392 references) would take untold amounts of effort.  With the dawn of the new API for Minecraft upon us, I think it's going to be hard to sell someone on putting a huge amount of time into doing that.  A new enum would allow developers to regain the lost intuition that previously existed with this enum in Bukkit.  And in the end, isn't Bukkit's primary purpose to increase intuition for developing modifications to Minecraft?  Else we'd all be coding against obfuscated code...

**Comment by mikeprimm** [comment]
I'd argue that Bukkit's value is the same as any other API that has an existing community of applications - stability and reduction in the need for unnecessary redevelopment and ongoing maintenance.  The dominant folks benefiting from CraftBukkit aren't the dozen or so folks coding CB, nor the couple of hundred plugin developers coding mods to it - its the couple hundred thousands servers and their users using the resulting ecosystem.  Breaking changes are always a cost to that community - it doesn't mean that they never need to happen, but they always need to be considered in that light.  With a new API, there is no investment to be compromised, so you're free to mess around until you get it right - but once you've put it out there to be used, you've made a contract to respect the investment made by the folks coding to it and the customers using it.  With respect, saying 'screw the plugins' on an ecosystem where conservatively 95% of the value-add IS those plugins is just irresponsible.

**Comment by EdGruberman** [comment]
I should have worded my comment more carefully.  I meant to convey that Bukkit should maintain intuitive coding practices and keep up to date to reflect the current reality.  If it doesn't, it will simply slowly diverge to a point it is not useful.  Bukkit also has a development cycle that consists of plugin developers having access to test changes far in advance of the ecosystem employing them.  Plugin developers would have plenty of time to update their plugins to prepare for a Recommended Build.

If plugin developers need to spend extra time to bring their plugins up to date just like Bukkit does, so be it.  As you infer, the time loss is minimized to the 100s of developers, not the 100s of thousands of servers which will simply download the new jars.  And I'm pretty sure developers have signed on to do exactly that, maintain a current useful plugin that accurately interprets the current state of Minecraft.

**Comment by mikeprimm** [comment]
Right - all good.  Completely agree with the point on enums being desirable for helping improve readability and the like.  My main thing is that APIs have a lifecycle that results in a shift in the various priorities - they initially have zero need to protect 3rd-party investment in their definition and behavior, and can be strictly driven by development goals like readability and utility.  But, in their success, the value of an API becomes less about itself and starts being more in the code that depends upon it - if you're familiar with the Berkeley Sockets API, for example, there are LOADS of obsolete and obtuse defines in there, but when you have over 20 years of code wrapped around an API, you don't break stuff (and, conversely, not breaking stuff is HOW you get to having 20 years of code wrapped around you).  The thing with the Bukkit community is that, as it has matured, I know I've seen an ongoing drop in the level of activity and maintenance on many of the core plugins that lots of servers depend upon (natural consequence of folks working on things for fun versus for profit) - assuming that a server owner is going to be able to get updated versions of all 20-30 mods they are likely running is a lot to ask, and forcing the need for those updates isn't something we should pursue.  Much of our (CBs)) value is in the fact that, more often than not, most-to-nearly-all mods don't need to be updated for a new CB or even a new vanilla release (at least not in order to maintain existing functionality).

**Comment by EdGruberman** [comment]
With the theory that stability and reliability is more important than readability and utility at this point, I wonder how the new Minecraft API will do.  If you are right, few should migrate and it will fail with Bukkit maintaining its foothold.  But if people migrate, it means even a complete redesign from the ground up that causes widespread breaking changes is not only viable, but ideal enough to encourage people to migrate.

How can a slow migration of controlled, incremental breaking changes towards a better API overall not be better than a completely breaking redesign?

I understand your concern over plugins that are no longer supported being left behind, but it also seems odd to me let old and unsupported plugins dictate the landscape.

**Comment by DrakiaXYZ** [comment]
> Plugin developers would have plenty of time to update their plugins to prepare for a Recommended Build.

This would also mean plugin developers would have a version that works with CB-RB and a version that works with CB-Beta/Dev, causing a massive increase in support requests as users would assume the latest plugin version (For CB-Beta) works with the current CB-RB (Users aren't bright). 

Honestly, it's purely aesthetic, changing it would require massive internal changes to Bukkit to update the existing references, as well as massive amounts of plugin breakage, I don't see the point.

As for:

> the wiki page for data values on blocks like ladders / signs / chests might attempt to implement this in a plugin, and come up with wrong values, if they are using the BlockFace class.

Just update the wiki page(s) and add a small note about Bukkit's implementation in regards to Notchian implementation, less work, still gets the point across to new devs.

**Comment by mikeprimm** [comment]
I definitely appreciate the points there - clearly, my opinions and experiences with this sort of thing are my own (been doing API based products and frameworks for a very long time....), but I see a key strategy for us on Bukkit being to provide a smooth transition from the existing API to the new: that is, Bukkit should become an increasingly thin wrapper around the new API, while allowing mods to gracefully transition to the new API as they see appropriate (for new function, more efficiency, or the like).  As such, its value will be even more weighted towards compatibility/stability, since new function would likely be expressed in the new API only, with Bukkit's API shifting towards being in maintenance mode.  Ideally, I see us winding up with the native API being a new, and capability-wise improved, interface, with Bukkit providing a compatible-albeit-less-optimal wrapper.  

Honestly, if I were convinced that the Bukkit API was both willing to break anything I've done for no better reason than API aesthetics AND had no future post-native API, I'd consider walking from supporting my mods now (and would definitely not consider new mods until I felt that those issues were no longer the case)  Frankly, a good number of devs have already done this.

But, if the Bukkit API is on its way out, the value of it in the present is even more weighted towards the existing investment versus future mods that aren't going to happen (i.e. the theoretical advantage of cleaning it up is irrelevant, since most everything that will use it has already been written, so who exactly are we helping?).

**Comment by EdGruberman** [comment]
I also agree that if Bukkit is on its way out, there is very little/no gain in improving it anymore.

**Comment by feildmaster** [comment]
> I also agree that if Bukkit is on its way out, there is very little/no gain in improving it anymore.

What? On it's way out?

API correctness isn't  the same as API aesthetics.

When you use something in an API, you expect it to work correctly. Granted, it should have been fixed way back when.

**Comment by Fishrock123** [comment]
Why doesn't one of the Bukkit-Mojang guys just fix this for 1.3?

Because 380 someodd references would be a heck of work to update when 1.3 comes out.

**Comment by MisterVector** [comment]
A reasonable fix for this problem would not be trivial. Simply rotating each referenced blockface 90 degrees to the left, and updating the blockface enum iself, would fix it

@Fishrock123 vanilla doesn't have a blockface class. It wouldn't need to update, as the direction has already been corrected in this case. Bukkit is the only thing that needs updating.

**Pull request closed without merging**
