### PR TITLE
Loading plugins from classpath

### PR DESCRIPTION
**Pull request by Laeffe**
Letting JavaPluginLoader.java handle direct yml files. Perfect for dev env.

This will let a developer copy his/hers plugin.yml (rename if wanted) file to the plugins folder. Then the developer can add the plugin to the bukkit classpath (in eclipse or any IDE) then the pluginloader will load the plugin.

This gives the same feature as https://github.com/Bukkit/Bukkit/pull/61

Ps.
Sorry for "breaking" the formatting ;)

### CODE REVIEW

**Comment by lahwran** [comment]
ew. if you use maven, then building a jar is very easy. this is one thing I hope does not get merged.

**Comment by Laeffe** [comment]
Um... this is not suppose to replace building jar files with maven.. ofc that's easy.

This will help you to run your plugin in a "real" development environment so that you can (easier) to debugging and such.

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Comment by Laeffe** [comment]
No worries ;)

**Pull request closed without merging**
