### PR TITLE
Added createSection(String path, Map<String, object> map)

### PR DESCRIPTION
**Pull request by feildmaster**
Will create a new ConfigurationSection and apply the map values.

### CODE REVIEW

**Comment by Dinnerbone** [comment]
Thanks. Tweaked the test.

**Comment by feildmaster** [comment]
Oh... I wanted to tweak it as well. It wasn't what I wanted. But I'll see how you put it.

**Comment by Dinnerbone** [comment]
Then close it when you don't want it pulled :(

**Comment by feildmaster** [comment]
No... The code was fine. It was the "test" I wanted to tweak, but never got around to it. It's fine like this. :P

**Pull request closed without merging**
