### PR TITLE
Methods to register multiple events at once

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Adds methods to register every event to a single listener, and methods to register every event in a given category. Would be useful for plugins that (for example) provide logging functions.

### CODE REVIEW

**Comment by t3hk0d3** [comment]
Do you tested your commit? Do you know what usage of registerAllEvents with current Bukkit would lead to 100% ClassCastException?

Also you forgot to make appropriate methods in PluginManager interface.

**Comment by CelticMinstrel** [comment]
...right, duh, I'll fix that momentarily.

**Comment by CelticMinstrel** [comment]
As for the ClassCastException, I see what you mean. I'll give it some thought, but I'm really more interested in the full-category version than the all-events version, so I may elect to just reduce it this pull to those two.

**Comment by t3hk0d3** [comment]
well, i admit you to better look on #278 (#277) or #279

**Comment by Dinnerbone** [comment]
I'm currently cleaning old Pull Requests, and this one will be closed without being accepted.

I'm very sorry for the state that our Pull Requests have come to, and I hope you can all forgive us for letting them sit for so long. We're so undermanned for this, it's unbelievable. We hope that our new Bleeding system will allow for newer pull requests to be picked up and handled by much more people than just ourselves, which will speed up things tremendously.

If you wish to reopen your pull request, please make sure that it's 100% up to date with the current head, and feel free to resubmit whereupon one of our team will properly review it and give it the attention it deserves.

Again, I'm very sorry for letting these pulls sit for so long. Thanks for your patience.

**Pull request closed without merging**
