### PR TITLE
Correcting minor typo in Javadoc for InventoryView.Property

### PR DESCRIPTION
**Pull request by Celeo**

### CODE REVIEW

**Comment by riking** [comment]
Is this still relevant? Is the typo still there?

**Comment by Celeo** [comment]
Yes, it appears so.

**Comment by riking** [comment]
@Celeo Well, in that case, you're going to need to squash these commits into one. Use the `git rebase -i <Current bukkit commit>` command and follow the directions.

**Comment by feildmaster** [comment]
In queue.. thanks

**Pull request closed without merging**
