### PR TITLE
[B] Rename Fish to FishHook - Add BUKKIT-3856

### PR DESCRIPTION
**Pull request by riking**
### Problem

Fish is a badly named class.
### Justification

Future-proofing against Mojang eventually adding actual fish to the game.
Additionally, all other classes in the entity package are very clear in their names, such as `Pig`, while Fish is actually misleading in its name.
### PR Description

This change creates the FishHook class for current use and future transitioning to.
This is a **non-breaking change**.

https://bukkit.atlassian.net/browse/BUKKIT-3856

### CODE REVIEW

**Comment by thomassross** [comment]
What about the event?

**Comment by riking** [comment]
@Th0masR0ss This has nothing to do with any event - PRs should generally be single-issue

**Comment by thomassross** [comment]
@riking PlayerFishEvent-?
PlayerFishEvent currently uses Fish, instead of FishHook.

**Comment by ST-DDT** [comment]
I guess you have to update this PR.
There have been a lot of changes in "Fish" Code

**Comment by ST-DDT** [comment]
I guess we have to pull this request a long time before 1.6. Otherwise this will cause horrible naming conflicts.
"Jon Kagstrom commented on Reddit that he would like to add more animals, such as **fish**, birds, and tree animals, to make the game seem more alive.[23] Later, Jeb stated in a tweet[24] that new mobs are planned for the 1.6 major update."
Source: http://www.minecraftwiki.net/wiki/Upcoming_features

**Comment by feildmaster** [comment]
You need to move the methods from Fish into FishHook...

**Comment by turt2live** [comment]
Pulled via https://github.com/Bukkit/Bukkit/commit/f3a23c49855d5e6ea9fee642f720a34dab08aa0c

Thanks for your contribution! 

(note: the diff is different due to https://github.com/Bukkit/Bukkit/pull/817#issuecomment-51033877 )

**Pull request closed without merging**
