### PR TITLE
Expose locale to plugin developers. Adds BUKKIT-4507

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Wolvereness** [comment]
it is an explicit duplicate PR

**Comment by Wolvereness** [comment]
You closed them after I was already closing the duplicates.

**Comment by Bestle** [comment]
The whole Bukkit PR system is stupid. Your original one sat there for 6 months which is completely unacceptable for something so simple.

**Comment by TheE** [comment]
Could this be reopened or something? Or at least receive any clear feedback explaining why this was not pulled in the last six months?

**Comment by Wolvereness** [comment]
@Steveice10 Do it yourself...

**Comment by Wolvereness** [comment]
It does on the ones that you closed.

**Comment by Wolvereness** [comment]
Open, push to the branch `locale` even if it doesn't exist.

**Comment by Lunaphied** [comment]
You could also make a new PR if it's too damaged to work on from this
point, GitHub doesn't seem to provide an easy way to clear a PR and switch
it to the undamaged state.

On Fri, Jan 3, 2014 at 7:09 PM, Steven Smith notifications@github.comwrote:

> I can't get those updated to 1.7 though, I had previously deleted the
> forks I used to make them because it had been a long time without response.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Bukkit/Bukkit/pull/999#issuecomment-31567042
> .

## 

Starbuck Johnson, Java Developer
www.modwiz.com | starbuck@modwiz.com

**Comment by Lunaphied** [comment]
Well unfortunately you may have to do it again :( I have still got to
create a new PR and branches and everything for the villager api, which I
screwed up with a forced push and don't know how or if I can repair the
existing one.

On Fri, Jan 3, 2014 at 7:14 PM, Steven Smith notifications@github.comwrote:

> I can't seem to reopen the old one either...
> 
> Also, that's what this one was intended for modwiz
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Bukkit/Bukkit/pull/999#issuecomment-31567242
> .

## 

Starbuck Johnson, Java Developer
www.modwiz.com | starbuck@modwiz.com

**Pull request closed without merging**
