### PR TITLE
Added toDimension property to PlayerPortalEvent.

### PR DESCRIPTION
**Pull request by jrtc27**
I have added a "toDimension" property to PlayerPortalEvent as it is now impossible to find out to which dimension the player is travelling - previously (as there were two) it was just the opposite of the one the player was in.

Corresponding CraftBukkit pull: https://github.com/Bukkit/CraftBukkit/pull/554

### CODE REVIEW

**Comment by tips48** [comment]
Nice job :)

**Comment by fernferret** [comment]
As @Rigby90 said in the implementation PR, this is not needed. Pulling this will break all events that use the PlayerPortalEvent.

**Comment by jrtc27** [comment]
As I have explained in the implementation, you can only use event.getTo().getWorld().getEnvironment() if you have a non-null location - unfortunately this only occurs when you portal in the main world. Try creating a simple plugin that just logs event.getTo().getWorld().getEnvironment().getId() on every portal event and you will find you get an NPE for non-server.properties worlds. As you can see I have also deprecated the old constructor, so any events that still use a PlayerPortalEvent will work perfectly - you just have to check for a non-null toDimension. What events are there that use the PlayerPortalEvent, anyway - I could only find one reference to it (NMS.ServerConfigurationManager.a())?

**Comment by jrtc27** [comment]
Ignore the "Merge remote-tracking branch 'upstream/master'" commit - that was just me updating my local git repo with the new commits to Bukkit so I can keep up to date.

**Comment by jrtc27** [comment]
New enum version at https://github.com/Bukkit/Bukkit/pull/478

**Pull request closed without merging**
