### PR TITLE
Add BlockState.applyPhysics()

### PR DESCRIPTION
**Pull request by eisental**
When changing a lever on/off state by updating its block data, applyPhysics() is not called as it does when interacting with the lever. This can cause some blocks around the lever to not react to the change. It would be useful to have this method available.

Implementation: https://github.com/Bukkit/CraftBukkit/pull/618

### CODE REVIEW

**Comment by Jaker232** [comment]
I have to agree on this pull request. Add it, bukkit.

**Comment by tahg** [comment]
BlockState.update() does exactly what you want.  I don't see any reason for this addition, unless there's some reason you don't want update the data of the block.

**Comment by eisental** [comment]
By looking at the code, it seems that CraftBlockState.update() is not calling applyPhysics(). I'm not sure why it doesn't do that but in any case calling BlockState.update() doesn't fix the issue.

**Comment by eisental** [comment]
Are there any opinions about this?

The only workaround I found for applying physics on a block is this:

``` java
Block b = loc.getBlock();
byte oldData = b.getData();
byte notData;
if (oldData>1) notData = (byte)(oldData-1);
else if (oldData<15) notData = (byte)(oldData+1);
else notData = 0;
b.setData(notData, true);
b.setData(oldData, true);
```

It seems rather wasteful to go through all that just to call a method that could be easily exposed in the API. Is there any reason not to pull this request? Should I make some changes?

**Comment by Majiir** [comment]
I think it's more appropriate to make `CraftBlockState.update()` call `applyPhysics()` and avoid changing the API. As @tahg alluded to, there's no good reason to apply physics _without_ updating the block. The two should go hand-in-hand, always.

**Comment by eisental** [comment]
I think `applyPhysics()` is already called on `CraftBlockState.update()` in `net.minecraft.server.World.setData()` that's called by `CraftBlock.setData()` but only when the new block data is different from the old. When both are the same `net.minecraft.server.Chunk.b()` returns false and applyPhysics is not called. So this would require some more internal changes... 

I don't need to change the block data or type, just applyPhysics on the block after changing the data of a lever block or the material type of a redstone torch that are attached to it so other blocks that are attached will update accordingly (like a piston for ex.).

**Comment by Majiir** [comment]
Perhaps add an overload for `update()` which accepts a boolean flag that will force applying physics. If the flag is set `false` (or not specified) then use the existing behavior. If this means refactoring CraftBukkit code to fix a poor design, so be it.

I think it's important that the API not confuse people by exposing a call (`applyPhysics()`) which isn't typically useful in isolation.

**Comment by eisental** [comment]
There's already an `update(boolean force)` method. If anything would be confusing it would be to add `update(boolean, boolean)` on top of that. 

This pr is for the rare cases when it's necessary to apply physics on a block without changing the material or data just before. Unless there's a way to simulate a proper lever state change (this means updating the physics of the lever block, as well as the block the lever is attached to. That block doesn't need any other changes besides updating physics), it looks like the only option is to manually apply physics.

So, I don't really understand why not just add the method. Maybe it should be in the Block class instead of BlockState but for me at least it looks very clear.

**Comment by Majiir** [comment]
> This pr is for the rare cases when it's necessary to apply physics on a block without changing the material or data just before.

Said a different way: you want a way _other than changing the material or data_ to apply physics. However, I see no reason to apply physics _without_ performing a normal block update. In any event, it seems that what you want is a proper way to toggle a lever.

It seems to be an oversight (you could even consider it a bug) that updating a lever block does not cause physics to apply to its attached block. The solution to such an oversight is not to force API users to make an additional call; this leads to an inconsistent treatment of levers among new plugins and neglects already-existing plugins. Applying physics is something that plugins should ultimately be agnostic to.

**Comment by eisental** [comment]
Well, in a perfect world Bukkit would have a Lever class that extends Block or something similar and it would have a Lever.setState() method which would take care of all that. Unfortunately at the moment the only way to change a lever is by updating its data and that's why only the lever block applyPhysics() is called and not the block it's attached to, so I would hardly call it a bug. In any case, since no one can say what would be acceptable, I guess I'll have to stick with the ugly code for a bit longer.

**Comment by EdGruberman** [comment]
> I don't need to change the block data or type, just applyPhysics on the block after changing the data of a lever block or the material type of a redstone torch that are attached to it so other blocks that are attached will update accordingly

@eisental I'm still not sure what the problem with `BlockState.update` is if you are updating the data or material of a block?  Either of those scenarios will trigger the `applyPhysics` appropriately.  This PR is 9 months old, has something changed now that this PR is no longer relevant?

**Comment by eisental** [comment]
How time flies... I'm still using the workaround described above. I rechecked and the problem is still there. To hopefully make the issue finally clear, here's an image describing a setup for this problem:

applyphysics

Whenever I press the button on the iron block on the right the lever changes from on to off. When you click on the lever itself and turn it on or off the piston will be updated accordingly and open or close as you can see in the image. This expected behavior doesn't happen when you update the lever block so I need to apply physics on the gold block as well. Unfortunately calling update() on the gold block does nothing since the block did not change and therefore I need to make some unnecessary change to the gold block for the piston to open.

**Comment by EdGruberman** [comment]
I see more clearly now, thank you.  To me then this seems more of a bug than needing to implement `applyPhysics` directly.  I believe `BlockState.update` should cause the same result as a manual interaction with the lever directly.

**Comment by gmcferrin** [comment]
@eisental If you still want this implemented, please update it for the latest version of Bukkit.

**Comment by gmcferrin** [comment]
This needs be fixed on a higher level than this PR handles - the Core Team will be looking into other solutions.

**Pull request closed without merging**
