### PR TITLE
Added the hasPhysics method to the Material class

### PR DESCRIPTION
**Pull request by nitnelave**
Added the hasPhysics method to the Material class, to get the block that are affected by gravity.
Unit test : https://github.com/Bukkit/CraftBukkit/pull/1029

### CODE REVIEW

**Comment by Wolvereness** [comment]
Should be done with a switch, and have the respective unit test set up in CraftBukkit.

**Comment by nitnelave** [comment]
In that case the isEdible method should be corrected to a switch also. I'll see how to do set up the test.
And isEdible doesn't seem to have a test either. By the way, how could I test this? It's as simple as it can get.

**Comment by nitnelave** [comment]
Nevermind, I didn't have the latest version...

**Comment by nitnelave** [comment]
How's that? I updated it. I didn't add a unit test because I don't really see what is there to test... And the other comparable methods like is Edible or isTransparent don't seem to have tests either.

**Comment by Wolvereness** [comment]
They do actually: https://github.com/Bukkit/CraftBukkit/blob/master/src/test/java/org/bukkit/PerMaterialTest.java

**Comment by nitnelave** [comment]
Oh, in CraftBukkit! I'll do the corresponding PR and link.

**Comment by nitnelave** [comment]
I can't find how I can get the list of blocks affected by gravity, or even if a single block is affected by gravity...

**Comment by nitnelave** [comment]
Ok, found out. All falling blocks inherit from BlockSand.
https://github.com/Bukkit/CraftBukkit/pull/1029

**Comment by gmcferrin** [comment]
@nitnelave Please create a Leaky ticket for this PR and link it here. Also, you're missing a closing bracket, so this won't compile.

Also, this would be better named as hasGravity.

**Comment by nitnelave** [comment]
Updated. I put a better commit message in the second commit. Here's the Leaky ticket : 
https://bukkit.atlassian.net/browse/BUKKIT-3832

And I also updated the unit test.

**Comment by riking** [comment]
Thanks for submitting this pull request! It looks like you're almost done, and the idea behind it has been approved.

However, we need all of the changes to be in a single commit, as this makes it much easier for us to manage the changelog.
I think this is what you need to do: (Assuming that the `release` remote is Bukkit/(Craft)Bukkit)

``` bash
git checkout master
git pull release master
git checkout material
git rebase -i master
git push -f YOUR_REPO material
```

**Comment by gmcferrin** [comment]
Added.

**Pull request closed without merging**
